
	.align 2
gCryTable:: @ 869DCF4
	cry_not Cry_Bulbasaur  @ 869DCF4
	cry_not Cry_Ivysaur  @ 869DD00
	cry_not Cry_Venusaur  @ 869DD0C
	cry_not Cry_Charmander  @ 869DD18
	cry_not Cry_Charmeleon  @ 869DD24
	cry_not Cry_Charizard  @ 869DD30
	cry_not Cry_Squirtle  @ 869DD3C
	cry_not Cry_Wartortle  @ 869DD48
	cry_not Cry_Blastoise  @ 869DD54
	cry_not Cry_Caterpie  @ 869DD60
	cry_not Cry_Metapod  @ 869DD6C
	cry_not Cry_Butterfree  @ 869DD78
	cry_not Cry_Weedle  @ 869DD84
	cry_not Cry_Kakuna  @ 869DD90
	cry_not Cry_Beedrill  @ 869DD9C
	cry_not Cry_Pidgey  @ 869DDA8
	cry_not Cry_Pidgeotto  @ 869DDB4
	cry_not Cry_Pidgeot  @ 869DDC0
	cry_not Cry_Rattata  @ 869DDCC
	cry_not Cry_Raticate  @ 869DDD8
	cry_not Cry_Spearow  @ 869DDE4
	cry_not Cry_Fearow  @ 869DDF0
	cry_not Cry_Ekans  @ 869DDFC
	cry_not Cry_Arbok  @ 869DE08
	cry_not Cry_Pikachu  @ 869DE14
	cry_not Cry_Raichu  @ 869DE20
	cry_not Cry_Sandshrew  @ 869DE2C
	cry_not Cry_Sandslash  @ 869DE38
	cry_not Cry_NidoranF  @ 869DE44
	cry_not Cry_Nidorina  @ 869DE50
	cry_not Cry_Nidoqueen  @ 869DE5C
	cry_not Cry_NidoranM  @ 869DE68
	cry_not Cry_Nidorino  @ 869DE74
	cry_not Cry_Nidoking  @ 869DE80
	cry_not Cry_Clefairy  @ 869DE8C
	cry_not Cry_Clefable  @ 869DE98
	cry_not Cry_Vulpix  @ 869DEA4
	cry_not Cry_Ninetales  @ 869DEB0
	cry_not Cry_Jigglypuff  @ 869DEBC
	cry_not Cry_Wigglytuff  @ 869DEC8
	cry_not Cry_Zubat  @ 869DED4
	cry_not Cry_Golbat  @ 869DEE0
	cry_not Cry_Oddish  @ 869DEEC
	cry_not Cry_Gloom  @ 869DEF8
	cry_not Cry_Vileplume  @ 869DF04
	cry_not Cry_Paras  @ 869DF10
	cry_not Cry_Parasect  @ 869DF1C
	cry_not Cry_Venonat  @ 869DF28
	cry_not Cry_Venomoth  @ 869DF34
	cry_not Cry_Diglett  @ 869DF40
	cry_not Cry_Dugtrio  @ 869DF4C
	cry_not Cry_Meowth  @ 869DF58
	cry_not Cry_Persian  @ 869DF64
	cry_not Cry_Psyduck  @ 869DF70
	cry_not Cry_Golduck  @ 869DF7C
	cry_not Cry_Mankey  @ 869DF88
	cry_not Cry_Primeape  @ 869DF94
	cry_not Cry_Growlithe  @ 869DFA0
	cry_not Cry_Arcanine  @ 869DFAC
	cry_not Cry_Poliwag  @ 869DFB8
	cry_not Cry_Poliwhirl  @ 869DFC4
	cry_not Cry_Poliwrath  @ 869DFD0
	cry_not Cry_Abra  @ 869DFDC
	cry_not Cry_Kadabra  @ 869DFE8
	cry_not Cry_Alakazam  @ 869DFF4
	cry_not Cry_Machop  @ 869E000
	cry_not Cry_Machoke  @ 869E00C
	cry_not Cry_Machamp  @ 869E018
	cry_not Cry_Bellsprout  @ 869E024
	cry_not Cry_Weepinbell  @ 869E030
	cry_not Cry_Victreebel  @ 869E03C
	cry_not Cry_Tentacool  @ 869E048
	cry_not Cry_Tentacruel  @ 869E054
	cry_not Cry_Geodude  @ 869E060
	cry_not Cry_Graveler  @ 869E06C
	cry_not Cry_Golem  @ 869E078
	cry_not Cry_Ponyta  @ 869E084
	cry_not Cry_Rapidash  @ 869E090
	cry_not Cry_Slowpoke  @ 869E09C
	cry_not Cry_Slowbro  @ 869E0A8
	cry_not Cry_Magnemite  @ 869E0B4
	cry_not Cry_Magneton  @ 869E0C0
	cry_not Cry_Farfetchd  @ 869E0CC
	cry_not Cry_Doduo  @ 869E0D8
	cry_not Cry_Dodrio  @ 869E0E4
	cry_not Cry_Seel  @ 869E0F0
	cry_not Cry_Dewgong  @ 869E0FC
	cry_not Cry_Grimer  @ 869E108
	cry_not Cry_Muk  @ 869E114
	cry_not Cry_Shellder  @ 869E120
	cry_not Cry_Cloyster  @ 869E12C
	cry_not Cry_Gastly  @ 869E138
	cry_not Cry_Haunter  @ 869E144
	cry_not Cry_Gengar  @ 869E150
	cry_not Cry_Onix  @ 869E15C
	cry_not Cry_Drowzee  @ 869E168
	cry_not Cry_Hypno  @ 869E174
	cry_not Cry_Krabby  @ 869E180
	cry_not Cry_Kingler  @ 869E18C
	cry_not Cry_Voltorb  @ 869E198
	cry_not Cry_Electrode  @ 869E1A4
	cry_not Cry_Exeggcute  @ 869E1B0
	cry_not Cry_Exeggutor  @ 869E1BC
	cry_not Cry_Cubone  @ 869E1C8
	cry_not Cry_Marowak  @ 869E1D4
	cry_not Cry_Hitmonlee  @ 869E1E0
	cry_not Cry_Hitmonchan  @ 869E1EC
	cry_not Cry_Lickitung  @ 869E1F8
	cry_not Cry_Koffing  @ 869E204
	cry_not Cry_Weezing  @ 869E210
	cry_not Cry_Rhyhorn  @ 869E21C
	cry_not Cry_Rhydon  @ 869E228
	cry_not Cry_Chansey  @ 869E234
	cry_not Cry_Tangela  @ 869E240
	cry_not Cry_Kangaskhan  @ 869E24C
	cry_not Cry_Horsea  @ 869E258
	cry_not Cry_Seadra  @ 869E264
	cry_not Cry_Goldeen  @ 869E270
	cry_not Cry_Seaking  @ 869E27C
	cry_not Cry_Staryu  @ 869E288
	cry_not Cry_Starmie  @ 869E294
	cry_not Cry_MrMime  @ 869E2A0
	cry_not Cry_Scyther  @ 869E2AC
	cry_not Cry_Jynx  @ 869E2B8
	cry_not Cry_Electabuzz  @ 869E2C4
	cry_not Cry_Magmar  @ 869E2D0
	cry_not Cry_Pinsir  @ 869E2DC
	cry_not Cry_Tauros  @ 869E2E8
	cry_not Cry_Magikarp  @ 869E2F4
	cry_not Cry_Gyarados  @ 869E300
	cry_not Cry_Lapras  @ 869E30C
	cry_not Cry_Ditto  @ 869E318
	cry_not Cry_Eevee  @ 869E324
	cry_not Cry_Vaporeon  @ 869E330
	cry_not Cry_Jolteon  @ 869E33C
	cry_not Cry_Flareon  @ 869E348
	cry_not Cry_Porygon  @ 869E354
	cry_not Cry_Omanyte  @ 869E360
	cry_not Cry_Omastar  @ 869E36C
	cry_not Cry_Kabuto  @ 869E378
	cry_not Cry_Kabutops  @ 869E384
	cry_not Cry_Aerodactyl  @ 869E390
	cry_not Cry_Snorlax  @ 869E39C
	cry_not Cry_Articuno  @ 869E3A8
	cry_not Cry_Zapdos  @ 869E3B4
	cry_not Cry_Moltres  @ 869E3C0
	cry_not Cry_Dratini  @ 869E3CC
	cry_not Cry_Dragonair  @ 869E3D8
	cry_not Cry_Dragonite  @ 869E3E4
	cry_not Cry_Mewtwo  @ 869E3F0
	cry_not Cry_Mew  @ 869E3FC
	cry_not Cry_Chikorita  @ 869E408
	cry_not Cry_Bayleef  @ 869E414
	cry_not Cry_Meganium  @ 869E420
	cry_not Cry_Cyndaquil  @ 869E42C
	cry_not Cry_Quilava  @ 869E438
	cry_not Cry_Typhlosion  @ 869E444
	cry_not Cry_Totodile  @ 869E450
	cry_not Cry_Croconaw  @ 869E45C
	cry_not Cry_Feraligatr  @ 869E468
	cry_not Cry_Sentret  @ 869E474
	cry_not Cry_Furret  @ 869E480
	cry_not Cry_Hoothoot  @ 869E48C
	cry_not Cry_Noctowl  @ 869E498
	cry_not Cry_Ledyba  @ 869E4A4
	cry_not Cry_Ledian  @ 869E4B0
	cry_not Cry_Spinarak  @ 869E4BC
	cry_not Cry_Ariados  @ 869E4C8
	cry_not Cry_Crobat  @ 869E4D4
	cry_not Cry_Chinchou  @ 869E4E0
	cry_not Cry_Lanturn  @ 869E4EC
	cry_not Cry_Pichu  @ 869E4F8
	cry_not Cry_Cleffa  @ 869E504
	cry_not Cry_Igglybuff  @ 869E510
	cry_not Cry_Togepi  @ 869E51C
	cry_not Cry_Togetic  @ 869E528
	cry_not Cry_Natu  @ 869E534
	cry_not Cry_Xatu  @ 869E540
	cry_not Cry_Mareep  @ 869E54C
	cry_not Cry_Flaaffy  @ 869E558
	cry_not Cry_Ampharos  @ 869E564
	cry_not Cry_Bellossom  @ 869E570
	cry_not Cry_Marill  @ 869E57C
	cry_not Cry_Azumarill  @ 869E588
	cry_not Cry_Sudowoodo  @ 869E594
	cry_not Cry_Politoed  @ 869E5A0
	cry_not Cry_Hoppip  @ 869E5AC
	cry_not Cry_Skiploom  @ 869E5B8
	cry_not Cry_Jumpluff  @ 869E5C4
	cry_not Cry_Aipom  @ 869E5D0
	cry_not Cry_Sunkern  @ 869E5DC
	cry_not Cry_Sunflora  @ 869E5E8
	cry_not Cry_Yanma  @ 869E5F4
	cry_not Cry_Wooper  @ 869E600
	cry_not Cry_Quagsire  @ 869E60C
	cry_not Cry_Espeon  @ 869E618
	cry_not Cry_Umbreon  @ 869E624
	cry_not Cry_Murkrow  @ 869E630
	cry_not Cry_Slowking  @ 869E63C
	cry_not Cry_Misdreavus  @ 869E648
	cry_not Cry_Unown  @ 869E654
	cry_not Cry_Wobbuffet  @ 869E660
	cry_not Cry_Girafarig  @ 869E66C
	cry_not Cry_Pineco  @ 869E678
	cry_not Cry_Forretress  @ 869E684
	cry_not Cry_Dunsparce  @ 869E690
	cry_not Cry_Gligar  @ 869E69C
	cry_not Cry_Steelix  @ 869E6A8
	cry_not Cry_Snubbull  @ 869E6B4
	cry_not Cry_Granbull  @ 869E6C0
	cry_not Cry_Qwilfish  @ 869E6CC
	cry_not Cry_Scizor  @ 869E6D8
	cry_not Cry_Shuckle  @ 869E6E4
	cry_not Cry_Heracross  @ 869E6F0
	cry_not Cry_Sneasel  @ 869E6FC
	cry_not Cry_Teddiursa  @ 869E708
	cry_not Cry_Ursaring  @ 869E714
	cry_not Cry_Slugma  @ 869E720
	cry_not Cry_Magcargo  @ 869E72C
	cry_not Cry_Swinub  @ 869E738
	cry_not Cry_Piloswine  @ 869E744
	cry_not Cry_Corsola  @ 869E750
	cry_not Cry_Remoraid  @ 869E75C
	cry_not Cry_Octillery  @ 869E768
	cry_not Cry_Delibird  @ 869E774
	cry_not Cry_Mantine  @ 869E780
	cry_not Cry_Skarmory  @ 869E78C
	cry_not Cry_Houndour  @ 869E798
	cry_not Cry_Houndoom  @ 869E7A4
	cry_not Cry_Kingdra  @ 869E7B0
	cry_not Cry_Phanpy  @ 869E7BC
	cry_not Cry_Donphan  @ 869E7C8
	cry_not Cry_Porygon2  @ 869E7D4
	cry_not Cry_Stantler  @ 869E7E0
	cry_not Cry_Smeargle  @ 869E7EC
	cry_not Cry_Tyrogue  @ 869E7F8
	cry_not Cry_Hitmontop  @ 869E804
	cry_not Cry_Smoochum  @ 869E810
	cry_not Cry_Elekid  @ 869E81C
	cry_not Cry_Magby  @ 869E828
	cry_not Cry_Miltank  @ 869E834
	cry_not Cry_Blissey  @ 869E840
	cry_not Cry_Raikou  @ 869E84C
	cry_not Cry_Entei  @ 869E858
	cry_not Cry_Suicune  @ 869E864
	cry_not Cry_Larvitar  @ 869E870
	cry_not Cry_Pupitar  @ 869E87C
	cry_not Cry_Tyranitar  @ 869E888
	cry_not Cry_Lugia  @ 869E894
	cry_not Cry_HoOh  @ 869E8A0
	cry_not Cry_Celebi  @ 869E8AC
	cry_not Cry_Treecko
	cry_not Cry_Grovyle
	cry_not Cry_Sceptile
	cry_not Cry_Torchic
	cry_not Cry_Combusken
	cry_not Cry_Blaziken
	cry_not Cry_Mudkip
	cry_not Cry_Marshtomp
	cry_not Cry_Swampert
	cry_not Cry_Poochyena
	cry_not Cry_Mightyena
	cry_not Cry_Zigzagoon
	cry_not Cry_Linoone
	cry_not Cry_Wurmple
	cry_not Cry_Silcoon
	cry_not Cry_Beautifly
	cry_not Cry_Cascoon
	cry_not Cry_Dustox
	cry_not Cry_Lotad
	cry_not Cry_Lombre
	cry_not Cry_Ludicolo
	cry_not Cry_Seedot
	cry_not Cry_Nuzleaf
	cry_not Cry_Shiftry
	cry_not Cry_Taillow
	cry_not Cry_Swellow
	cry_not Cry_Wingull
	cry_not Cry_Pelipper
	cry_not Cry_Ralts
	cry_not Cry_Kirlia
	cry_not Cry_Gardevoir
	cry_not Cry_Surskit
	cry_not Cry_Masquerain
	cry_not Cry_Shroomish
	cry_not Cry_Breloom
	cry_not Cry_Slakoth
	cry_not Cry_Vigoroth
	cry_not Cry_Slaking
	cry_not Cry_Nincada
	cry_not Cry_Ninjask
	cry_not Cry_Shedinja
	cry_not Cry_Whismur
	cry_not Cry_Loudred
	cry_not Cry_Exploud
	cry_not Cry_Makuhita
	cry_not Cry_Hariyama
	cry_not Cry_Azurill
	cry_not Cry_Nosepass
	cry_not Cry_Skitty
	cry_not Cry_Delcatty
	cry_not Cry_Sableye
	cry_not Cry_Mawile
	cry_not Cry_Aron
	cry_not Cry_Lairon
	cry_not Cry_Aggron
	cry_not Cry_Meditite
	cry_not Cry_Medicham
	cry_not Cry_Electrike
	cry_not Cry_Manectric
	cry_not Cry_Plusle
	cry_not Cry_Minun
	cry_not Cry_Volbeat
	cry_not Cry_Illumise
	cry_not Cry_Roselia
	cry_not Cry_Gulpin
	cry_not Cry_Swalot
	cry_not Cry_Carvanha
	cry_not Cry_Sharpedo
	cry_not Cry_Wailmer
	cry_not Cry_Wailord
	cry_not Cry_Numel
	cry_not Cry_Camerupt
	cry_not Cry_Torkoal
	cry_not Cry_Spoink
	cry_not Cry_Grumpig
	cry_not Cry_Spinda
	cry_not Cry_Trapinch
	cry_not Cry_Vibrava
	cry_not Cry_Flygon
	cry_not Cry_Cacnea
	cry_not Cry_Cacturne
	cry_not Cry_Swablu
	cry_not Cry_Altaria
	cry_not Cry_Zangoose
	cry_not Cry_Seviper
	cry_not Cry_Lunatone
	cry_not Cry_Solrock
	cry_not Cry_Barboach
	cry_not Cry_Whiscash
	cry_not Cry_Corphish
	cry_not Cry_Crawdaunt
	cry_not Cry_Baltoy
	cry_not Cry_Claydol
	cry_not Cry_Lileep
	cry_not Cry_Cradily
	cry_not Cry_Anorith
	cry_not Cry_Armaldo
	cry_not Cry_Feebas
	cry_not Cry_Milotic
	cry_not Cry_Castform
	cry_not Cry_Kecleon
	cry_not Cry_Shuppet
	cry_not Cry_Banette
	cry_not Cry_Duskull
	cry_not Cry_Dusclops
	cry_not Cry_Tropius
	cry_not Cry_Onix
	cry_not Cry_Absol
	cry_not Cry_Wynaut
	cry_not Cry_Snorunt
	cry_not Cry_Glalie
	cry_not Cry_Spheal
	cry_not Cry_Sealeo
	cry_not Cry_Walrein
	cry_not Cry_Clamperl
	cry_not Cry_Huntail
	cry_not Cry_Gorebyss
	cry_not Cry_Relicanth
	cry_not Cry_Luvdisc
	cry_not Cry_Bagon
	cry_not Cry_Shelgon
	cry_not Cry_Salamence
	cry_not Cry_Beldum
	cry_not Cry_Metang
	cry_not Cry_Metagross
	cry_not Cry_Regirock
	cry_not Cry_Regice
	cry_not Cry_Registeel
	cry_not Cry_Latias
	cry_not Cry_Latios
	cry_not Cry_Kyogre
	cry_not Cry_Groudon
	cry_not Cry_Rayquaza
	cry_not Cry_Jirachi
	cry_not Cry_Deoxys
	cry_not Cry_Turtwig
	cry_not Cry_Grotle
	cry_not Cry_Torterra
	cry_not Cry_Chimchar
	cry_not Cry_Monferno
	cry_not Cry_Infernape
	cry_not Cry_Piplup
	cry_not Cry_Prinplup
	cry_not Cry_Empoleon
	cry_not Cry_Starly
	cry_not Cry_Staravia
	cry_not Cry_Staraptor
	cry_not Cry_Bidoof
	cry_not Cry_Bibarel
	cry_not Cry_Kricketot
	cry_not Cry_Kricketune
	cry_not Cry_Shinx
	cry_not Cry_Luxio
	cry_not Cry_Luxray
	cry_not Cry_Budew
	cry_not Cry_Roserade
	cry_not Cry_Cranidos
	cry_not Cry_Rampardos
	cry_not Cry_Shieldon
	cry_not Cry_Bastiodon
	cry_not Cry_Burmy
	cry_not Cry_Wormadam
	cry_not Cry_Mothim
	cry_not Cry_Combee
	cry_not Cry_Vespiquen
	cry_not Cry_Pachirisu
	cry_not Cry_Buizel
	cry_not Cry_Floatzel
	cry_not Cry_Cherubi
	cry_not Cry_Cherrim
	cry_not Cry_Shellos
	cry_not Cry_Gastrodon
	cry_not Cry_Ambipom
	cry_not Cry_Drifloon
	cry_not Cry_Drifblim
	cry_not Cry_Buneary
	cry_not Cry_Lopunny
	cry_not Cry_Mismagius
	cry_not Cry_Honchkrow
	cry_not Cry_Glameow
	cry_not Cry_Purugly
	cry_not Cry_Chingling
	cry_not Cry_Stunky
	cry_not Cry_Skuntank
	cry_not Cry_Bronzor
	cry_not Cry_Bronzong
	cry_not Cry_Bonsly
	cry_not Cry_Mimejr
	cry_not Cry_Happiny
	cry_not Cry_Chatot
	cry_not Cry_Spiritomb
	cry_not Cry_Gible
	cry_not Cry_Gabite
	cry_not Cry_Garchomp
	cry_not Cry_Munchlax
	cry_not Cry_Riolu
	cry_not Cry_Lucario
	cry_not Cry_Hippopotas
	cry_not Cry_Hippowdon
	cry_not Cry_Skorupi
	cry_not Cry_Drapion
	cry_not Cry_Croagunk
	cry_not Cry_Toxicroak
	cry_not Cry_Carnivine
	cry_not Cry_Finneon
	cry_not Cry_Lumineon
	cry_not Cry_Mantyke
	cry_not Cry_Snover
	cry_not Cry_Abomasnow
	cry_not Cry_Weavile
	cry_not Cry_Magnezone
	cry_not Cry_Lickilicky
	cry_not Cry_Rhyperior
	cry_not Cry_Tangrowth
	cry_not Cry_Electivire
	cry_not Cry_Magmortar
	cry_not Cry_Togekiss
	cry_not Cry_Yanmega
	cry_not Cry_Leafeon
	cry_not Cry_Glaceon
	cry_not Cry_Gliscor
	cry_not Cry_Mamoswine
	cry_not Cry_PorygonZ
	cry_not Cry_Gallade
	cry_not Cry_Probopass
	cry_not Cry_Dusknoir
	cry_not Cry_Froslass
	cry_not Cry_Rotom
	cry_not Cry_Uxie
	cry_not Cry_Mesprit
	cry_not Cry_Azelf
	cry_not Cry_Dialga
	cry_not Cry_Palkia
	cry_not Cry_Heatran
	cry_not Cry_Regigigas
	cry_not Cry_Giratina
	cry_not Cry_Cresselia
	cry_not Cry_Phione
	cry_not Cry_Manaphy
	cry_not Cry_Darkrai
	cry_not Cry_Shaymin
	cry_not Cry_Arceus
	cry_not Cry_Victini
	cry_not Cry_Snivy
	cry_not Cry_Servine
	cry_not Cry_Serperior
	cry_not Cry_Tepig
	cry_not Cry_Pignite
	cry_not Cry_Emboar
	cry_not Cry_Oshawott
	cry_not Cry_Dewott
	cry_not Cry_Samurott
	cry_not Cry_Patrat
	cry_not Cry_Watchog
	cry_not Cry_Lillipup
	cry_not Cry_Herdier
	cry_not Cry_Stoutland
	cry_not Cry_Purrloin
	cry_not Cry_Liepard
	cry_not Cry_Pansage
	cry_not Cry_Simisage
	cry_not Cry_Pansear
	cry_not Cry_Simisear
	cry_not Cry_Panpour
	cry_not Cry_Simipour
	cry_not Cry_Munna
	cry_not Cry_Musharna
	cry_not Cry_Pidove
	cry_not Cry_Tranquill
	cry_not Cry_Unfezant
	cry_not Cry_Blitzle
	cry_not Cry_Zebstrika
	cry_not Cry_Roggenrola
	cry_not Cry_Boldore
	cry_not Cry_Gigalith
	cry_not Cry_Woobat
	cry_not Cry_Swoobat
	cry_not Cry_Drilbur
	cry_not Cry_Excadrill
	cry_not Cry_Audino
	cry_not Cry_Timburr
	cry_not Cry_Gurdurr
	cry_not Cry_Conkeldurr
	cry_not Cry_Tympole
	cry_not Cry_Palpitoad
	cry_not Cry_Seismitoad
	cry_not Cry_Throh
	cry_not Cry_Sawk
	cry_not Cry_Sewaddle
	cry_not Cry_Swadloon
	cry_not Cry_Leavanny
	cry_not Cry_Venipede
	cry_not Cry_Whirlipede
	cry_not Cry_Scolipede
	cry_not Cry_Cottonee
	cry_not Cry_Whimsicott
	cry_not Cry_Petilil
	cry_not Cry_Lilligant
	cry_not Cry_Basculin
	cry_not Cry_Sandile
	cry_not Cry_Krokorok
	cry_not Cry_Krookodile
	cry_not Cry_Darumaka
	cry_not Cry_Darmanitan
	cry_not Cry_Maractus
	cry_not Cry_Dwebble
	cry_not Cry_Crustle
	cry_not Cry_Scraggy
	cry_not Cry_Scrafty
	cry_not Cry_Sigilyph
	cry_not Cry_Yamask
	cry_not Cry_Cofagrigus
	cry_not Cry_Tirtouga
	cry_not Cry_Carracosta
	cry_not Cry_Archen
	cry_not Cry_Archeops
	cry_not Cry_Trubbish
	cry_not Cry_Garbodor
	cry_not Cry_Zorua
	cry_not Cry_Zoroark
	cry_not Cry_Minccino
	cry_not Cry_Cinccino
	cry_not Cry_Gothita
	cry_not Cry_Gothorita
	cry_not Cry_Gothitelle
	cry_not Cry_Solosis
	cry_not Cry_Duosion
	cry_not Cry_Reuniclus
	cry_not Cry_Ducklett
	cry_not Cry_Swanna
	cry_not Cry_Vanillite
	cry_not Cry_Vanillish
	cry_not Cry_Vanilluxe
	cry_not Cry_Deerling
	cry_not Cry_Sawsbuck
	cry_not Cry_Emolga
	cry_not Cry_Karrablast
	cry_not Cry_Escavalier
	cry_not Cry_Foongus
	cry_not Cry_Amoonguss
	cry_not Cry_Frillish
	cry_not Cry_Jellicent
	cry_not Cry_Alomomola
	cry_not Cry_Joltik
	cry_not Cry_Galvantula
	cry_not Cry_Ferroseed
	cry_not Cry_Ferrothorn
	cry_not Cry_Klink
	cry_not Cry_Klang
	cry_not Cry_Klinklang
	cry_not Cry_Tynamo
	cry_not Cry_Eelektrik
	cry_not Cry_Eelektross
	cry_not Cry_Elgyem
	cry_not Cry_Beheeyem
	cry_not Cry_Litwick
	cry_not Cry_Lampent
	cry_not Cry_Chandelure
	cry_not Cry_Axew
	cry_not Cry_Fraxure
	cry_not Cry_Haxorus
	cry_not Cry_Cubchoo
	cry_not Cry_Beartic
	cry_not Cry_Cryogonal
	cry_not Cry_Shelmet
	cry_not Cry_Accelgor
	cry_not Cry_Stunfisk
	cry_not Cry_Mienfoo
	cry_not Cry_Mienshao
	cry_not Cry_Druddigon
	cry_not Cry_Golett
	cry_not Cry_Golurk
	cry_not Cry_Pawniard
	cry_not Cry_Bisharp
	cry_not Cry_Bouffalant
	cry_not Cry_Rufflet
	cry_not Cry_Braviary
	cry_not Cry_Vullaby
	cry_not Cry_Mandibuzz
	cry_not Cry_Heatmor
	cry_not Cry_Durant
	cry_not Cry_Deino
	cry_not Cry_Zweilous
	cry_not Cry_Hydreigon
	cry_not Cry_Larvesta
	cry_not Cry_Volcarona
	cry_not Cry_Cobalion
	cry_not Cry_Terrakion
	cry_not Cry_Virizion
	cry_not Cry_Tornadus
	cry_not Cry_Thundurus
	cry_not Cry_Reshiram
	cry_not Cry_Zekrom
	cry_not Cry_Landorus
	cry_not Cry_Kyurem
	cry_not Cry_Keldeo
	cry_not Cry_Meloetta
	cry_not Cry_Genesect
	cry_not Cry_Chespin
	cry_not Cry_Quilladin
	cry_not Cry_Chesnaught
	cry_not Cry_Fennekin
	cry_not Cry_Braixen
	cry_not Cry_Delphox
	cry_not Cry_Froakie
	cry_not Cry_Frogadier
	cry_not Cry_Greninja
	cry_not Cry_Bunnelby
	cry_not Cry_Diggersby
	cry_not Cry_Fletchling
	cry_not Cry_Fletchinder
	cry_not Cry_Talonflame
	cry_not Cry_Scatterbug
	cry_not Cry_Spewpa
	cry_not Cry_Vivillon
	cry_not Cry_Litleo
	cry_not Cry_Pyroar
	cry_not Cry_Flabebe
	cry_not Cry_Floette
	cry_not Cry_Florges
	cry_not Cry_Skiddo
	cry_not Cry_Gogoat
	cry_not Cry_Pancham
	cry_not Cry_Pangoro
	cry_not Cry_Furfrou
	cry_not Cry_Espurr
	cry_not Cry_Meowstic
	cry_not Cry_Honedge
	cry_not Cry_Doublade
	cry_not Cry_Aegislash
	cry_not Cry_Spritzee
	cry_not Cry_Aromatisse
	cry_not Cry_Swirlix
	cry_not Cry_Slurpuff
	cry_not Cry_Inkay
	cry_not Cry_Malamar
	cry_not Cry_Binacle
	cry_not Cry_Barbaracle
	cry_not Cry_Skrelp
	cry_not Cry_Dragalge
	cry_not Cry_Clauncher
	cry_not Cry_Clawitzer
	cry_not Cry_Helioptile
	cry_not Cry_Heliolisk
	cry_not Cry_Tyrunt
	cry_not Cry_Tyrantrum
	cry_not Cry_Amaura
	cry_not Cry_Aurorus
	cry_not Cry_Sylveon
	cry_not Cry_Hawlucha
	cry_not Cry_Dedenne
	cry_not Cry_Carbink
	cry_not Cry_Goomy
	cry_not Cry_Sliggoo
	cry_not Cry_Goodra
	cry_not Cry_Klefki
	cry_not Cry_Phantump
	cry_not Cry_Trevenant
	cry_not Cry_Pumpkaboo
	cry_not Cry_Gourgeist
	cry_not Cry_Bergmite
	cry_not Cry_Avalugg
	cry_not Cry_Noibat
	cry_not Cry_Noivern
	cry_not Cry_Xerneas
	cry_not Cry_Yveltal
	cry_not Cry_Zygarde
	cry_not Cry_Diancie
	cry_not Cry_Hoopa
	cry_not Cry_Volcanion
	cry_not Cry_Rowlet
	cry_not Cry_Dartrix
	cry_not Cry_Decidueye
	cry_not Cry_Litten
	cry_not Cry_Torracat
	cry_not Cry_Incineroar
	cry_not Cry_Popplio
	cry_not Cry_Brionne
	cry_not Cry_Primarina
	cry_not Cry_Pikipek
	cry_not Cry_Trumbeak
	cry_not Cry_Toucannon
	cry_not Cry_Yungoos
	cry_not Cry_Gumshoos
	cry_not Cry_Grubbin
	cry_not Cry_Charjabug
	cry_not Cry_Vikavolt
	cry_not Cry_Crabrawler
	cry_not Cry_Crabominable
	cry_not Cry_Oricorio
	cry_not Cry_Cutiefly
	cry_not Cry_Ribombee
	cry_not Cry_Rockruff
	cry_not Cry_Lycanroc
	cry_not Cry_Wishiwashi
	cry_not Cry_Mareanie
	cry_not Cry_Toxapex
	cry_not Cry_Mudbray
	cry_not Cry_Mudsdale
	cry_not Cry_Dewpider
	cry_not Cry_Araquanid
	cry_not Cry_Fomantis
	cry_not Cry_Lurantis
	cry_not Cry_Morelull
	cry_not Cry_Shiinotic
	cry_not Cry_Salandit
	cry_not Cry_Salazzle
	cry_not Cry_Stufful
	cry_not Cry_Bewear
	cry_not Cry_Bounsweet
	cry_not Cry_Steenee
	cry_not Cry_Tsareena
	cry_not Cry_Comfey
	cry_not Cry_Oranguru
	cry_not Cry_Passimian
	cry_not Cry_Wimpod
	cry_not Cry_Golisopod
	cry_not Cry_Sandygast
	cry_not Cry_Palossand
	cry_not Cry_Pyukumuku
	cry_not Cry_Type_null
	cry_not Cry_Silvally
	cry_not Cry_Minior
	cry_not Cry_Komala
	cry_not Cry_Turtonator
	cry_not Cry_Togedemaru
	cry_not Cry_Mimikyu
	cry_not Cry_Bruxish
	cry_not Cry_Drampa
	cry_not Cry_Dhelmise
	cry_not Cry_Jangmo_o
	cry_not Cry_Hakamo_o
	cry_not Cry_Kommo_o
	cry_not Cry_Tapu_koko
	cry_not Cry_Tapu_lele
	cry_not Cry_Tapu_bulu
	cry_not Cry_Tapu_fini
	cry_not Cry_Cosmog
	cry_not Cry_Cosmoem
	cry_not Cry_Solgaleo
	cry_not Cry_Lunala
	cry_not Cry_Nihilego
	cry_not Cry_Buzzwole
	cry_not Cry_Pheromosa
	cry_not Cry_Xurkitree
	cry_not Cry_Celesteela
	cry_not Cry_Kartana
	cry_not Cry_Guzzlord
	cry_not Cry_Necrozma
	cry_not Cry_Magearna
	cry_not Cry_Marshadow
	cry_not Cry_Poipole
	cry_not Cry_Naganadel
	cry_not Cry_Stakataka
	cry_not Cry_Blacephalon
	cry_not Cry_Zeraora
	cry_not Cry_Meltan
	cry_not Cry_Melmetal
	@ Megas
	cry_not Cry_Ampharos
	cry_not Cry_Venusaur
	cry_not Cry_Charizard
	cry_not Cry_Charizard
	cry_not Cry_Mewtwo
	cry_not Cry_Mewtwo
	cry_not Cry_Blaziken
	cry_not Cry_Medicham
	cry_not Cry_Houndoom
	cry_not Cry_Aggron
	cry_not Cry_Banette
	cry_not Cry_Tyranitar
	cry_not Cry_Scizor
	cry_not Cry_Pinsir
	cry_not Cry_Aerodactyl
	cry_not Cry_Lucario
	cry_not Cry_Abomasnow
	cry_not Cry_Blastoise
	cry_not Cry_Kangaskhan
	cry_not Cry_Gyarados
	cry_not Cry_Absol
	cry_not Cry_Alakazam
	cry_not Cry_Heracross
	cry_not Cry_Mawile
	cry_not Cry_Manectric
	cry_not Cry_Garchomp
	cry_not Cry_Latios
	cry_not Cry_Latias
	cry_not Cry_Swampert
	cry_not Cry_Sceptile
	cry_not Cry_Sableye
	cry_not Cry_Altaria
	cry_not Cry_Gallade
	cry_not Cry_Audino
	cry_not Cry_Sharpedo
	cry_not Cry_Slowbro
	cry_not Cry_Steelix
	cry_not Cry_Pidgeot
	cry_not Cry_Glalie
	cry_not Cry_Diancie
	cry_not Cry_Metagross
	cry_not Cry_Rayquaza
	cry_not Cry_Camerupt
	cry_not Cry_Lopunny
	cry_not Cry_Salamence
	cry_not Cry_Beedrill
	cry_not Cry_Gengar
	cry_not Cry_Gardevoir
	@ Forms
	cry_not Cry_Burmy_Sandy
	cry_not Cry_Burmy_Trash
	cry_not Cry_Wormadam_Sandy
	cry_not Cry_Wormadam_Trash
	cry_not Cry_Rotom_Heat
	cry_not Cry_Rotom_Wash
	cry_not Cry_Rotom_Frost
	cry_not Cry_Rotom_Fan
	cry_not Cry_Rotom_Mow
	cry_not Cry_Kyurem_Black
	cry_not Cry_Kyurem_White
	cry_not Cry_Meowstic_F
	@ Alolan Forms
	cry_not Cry_Alolan_Rattata
	cry_not Cry_Alolan_Raticate
	cry_not Cry_Alolan_Raichu
	cry_not Cry_Alolan_Sandshrew
	cry_not Cry_Alolan_Sandslash
	cry_not Cry_Alolan_Vulpix
	cry_not Cry_Alolan_Ninetales
	cry_not Cry_Alolan_Diglett
	cry_not Cry_Alolan_Dugtrio
	cry_not Cry_Alolan_Meowth
	cry_not Cry_Alolan_Persian
	cry_not Cry_Alolan_Geodude
	cry_not Cry_Alolan_Graveler
	cry_not Cry_Alolan_Golem
	cry_not Cry_Alolan_Grimer
	cry_not Cry_Alolan_Muk
	cry_not Cry_Alolan_Exeggutor
	cry_not Cry_Alolan_Marowak
	@ Form Changes
	cry_not Cry_Primal_Kyogre
	cry_not Cry_Primal_Groudon
	cry_not Cry_Shaymin_Sky
	cry_not Cry_Giratina_Origin
	cry_not Cry_Darmanitan_Zen
	cry_not Cry_Tornadus_Therian
	cry_not Cry_Thundurus_Therian
	cry_not Cry_Landorus_Therian
	cry_not Cry_Meloetta_Pirouette
	cry_not Cry_Aegislash_Blade
	cry_not Cry_Hoopa_Unbound
	cry_not Cry_Minior_Core
	cry_not Cry_Unown_School
	cry_not Cry_Mimikyu_Busted
	cry_not Cry_Lycanroc_Midnight
	cry_not Cry_Lycanroc_Dusk
	cry_not Cry_Zygarde_10
	cry_not Cry_Zygarde_Complete
	cry Cry_Deoxys_Attack
	cry Cry_Deoxys_Defense
	cry Cry_Deoxys_Speed

	.align 2
gCryTable2:: @ 869EF24
	cry2_not Cry_Bulbasaur  @ 869EF24
	cry2_not Cry_Ivysaur  @ 869EF30
	cry2_not Cry_Venusaur  @ 869EF3C
	cry2_not Cry_Charmander  @ 869EF48
	cry2_not Cry_Charmeleon  @ 869EF54
	cry2_not Cry_Charizard  @ 869EF60
	cry2_not Cry_Squirtle  @ 869EF6C
	cry2_not Cry_Wartortle  @ 869EF78
	cry2_not Cry_Blastoise  @ 869EF84
	cry2_not Cry_Caterpie  @ 869EF90
	cry2_not Cry_Metapod  @ 869EF9C
	cry2_not Cry_Butterfree  @ 869EFA8
	cry2_not Cry_Weedle  @ 869EFB4
	cry2_not Cry_Kakuna  @ 869EFC0
	cry2_not Cry_Beedrill  @ 869EFCC
	cry2_not Cry_Pidgey  @ 869EFD8
	cry2_not Cry_Pidgeotto  @ 869EFE4
	cry2_not Cry_Pidgeot  @ 869EFF0
	cry2_not Cry_Rattata  @ 869EFFC
	cry2_not Cry_Raticate  @ 869F008
	cry2_not Cry_Spearow  @ 869F014
	cry2_not Cry_Fearow  @ 869F020
	cry2_not Cry_Ekans  @ 869F02C
	cry2_not Cry_Arbok  @ 869F038
	cry2_not Cry_Pikachu  @ 869F044
	cry2_not Cry_Raichu  @ 869F050
	cry2_not Cry_Sandshrew  @ 869F05C
	cry2_not Cry_Sandslash  @ 869F068
	cry2_not Cry_NidoranF  @ 869F074
	cry2_not Cry_Nidorina  @ 869F080
	cry2_not Cry_Nidoqueen  @ 869F08C
	cry2_not Cry_NidoranM  @ 869F098
	cry2_not Cry_Nidorino  @ 869F0A4
	cry2_not Cry_Nidoking  @ 869F0B0
	cry2_not Cry_Clefairy  @ 869F0BC
	cry2_not Cry_Clefable  @ 869F0C8
	cry2_not Cry_Vulpix  @ 869F0D4
	cry2_not Cry_Ninetales  @ 869F0E0
	cry2_not Cry_Jigglypuff  @ 869F0EC
	cry2_not Cry_Wigglytuff  @ 869F0F8
	cry2_not Cry_Zubat  @ 869F104
	cry2_not Cry_Golbat  @ 869F110
	cry2_not Cry_Oddish  @ 869F11C
	cry2_not Cry_Gloom  @ 869F128
	cry2_not Cry_Vileplume  @ 869F134
	cry2_not Cry_Paras  @ 869F140
	cry2_not Cry_Parasect  @ 869F14C
	cry2_not Cry_Venonat  @ 869F158
	cry2_not Cry_Venomoth  @ 869F164
	cry2_not Cry_Diglett  @ 869F170
	cry2_not Cry_Dugtrio  @ 869F17C
	cry2_not Cry_Meowth  @ 869F188
	cry2_not Cry_Persian  @ 869F194
	cry2_not Cry_Psyduck  @ 869F1A0
	cry2_not Cry_Golduck  @ 869F1AC
	cry2_not Cry_Mankey  @ 869F1B8
	cry2_not Cry_Primeape  @ 869F1C4
	cry2_not Cry_Growlithe  @ 869F1D0
	cry2_not Cry_Arcanine  @ 869F1DC
	cry2_not Cry_Poliwag  @ 869F1E8
	cry2_not Cry_Poliwhirl  @ 869F1F4
	cry2_not Cry_Poliwrath  @ 869F200
	cry2_not Cry_Abra  @ 869F20C
	cry2_not Cry_Kadabra  @ 869F218
	cry2_not Cry_Alakazam  @ 869F224
	cry2_not Cry_Machop  @ 869F230
	cry2_not Cry_Machoke  @ 869F23C
	cry2_not Cry_Machamp  @ 869F248
	cry2_not Cry_Bellsprout  @ 869F254
	cry2_not Cry_Weepinbell  @ 869F260
	cry2_not Cry_Victreebel  @ 869F26C
	cry2_not Cry_Tentacool  @ 869F278
	cry2_not Cry_Tentacruel  @ 869F284
	cry2_not Cry_Geodude  @ 869F290
	cry2_not Cry_Graveler  @ 869F29C
	cry2_not Cry_Golem  @ 869F2A8
	cry2_not Cry_Ponyta  @ 869F2B4
	cry2_not Cry_Rapidash  @ 869F2C0
	cry2_not Cry_Slowpoke  @ 869F2CC
	cry2_not Cry_Slowbro  @ 869F2D8
	cry2_not Cry_Magnemite  @ 869F2E4
	cry2_not Cry_Magneton  @ 869F2F0
	cry2_not Cry_Farfetchd  @ 869F2FC
	cry2_not Cry_Doduo  @ 869F308
	cry2_not Cry_Dodrio  @ 869F314
	cry2_not Cry_Seel  @ 869F320
	cry2_not Cry_Dewgong  @ 869F32C
	cry2_not Cry_Grimer  @ 869F338
	cry2_not Cry_Muk  @ 869F344
	cry2_not Cry_Shellder  @ 869F350
	cry2_not Cry_Cloyster  @ 869F35C
	cry2_not Cry_Gastly  @ 869F368
	cry2_not Cry_Haunter  @ 869F374
	cry2_not Cry_Gengar  @ 869F380
	cry2_not Cry_Onix  @ 869F38C
	cry2_not Cry_Drowzee  @ 869F398
	cry2_not Cry_Hypno  @ 869F3A4
	cry2_not Cry_Krabby  @ 869F3B0
	cry2_not Cry_Kingler  @ 869F3BC
	cry2_not Cry_Voltorb  @ 869F3C8
	cry2_not Cry_Electrode  @ 869F3D4
	cry2_not Cry_Exeggcute  @ 869F3E0
	cry2_not Cry_Exeggutor  @ 869F3EC
	cry2_not Cry_Cubone  @ 869F3F8
	cry2_not Cry_Marowak  @ 869F404
	cry2_not Cry_Hitmonlee  @ 869F410
	cry2_not Cry_Hitmonchan  @ 869F41C
	cry2_not Cry_Lickitung  @ 869F428
	cry2_not Cry_Koffing  @ 869F434
	cry2_not Cry_Weezing  @ 869F440
	cry2_not Cry_Rhyhorn  @ 869F44C
	cry2_not Cry_Rhydon  @ 869F458
	cry2_not Cry_Chansey  @ 869F464
	cry2_not Cry_Tangela  @ 869F470
	cry2_not Cry_Kangaskhan  @ 869F47C
	cry2_not Cry_Horsea  @ 869F488
	cry2_not Cry_Seadra  @ 869F494
	cry2_not Cry_Goldeen  @ 869F4A0
	cry2_not Cry_Seaking  @ 869F4AC
	cry2_not Cry_Staryu  @ 869F4B8
	cry2_not Cry_Starmie  @ 869F4C4
	cry2_not Cry_MrMime  @ 869F4D0
	cry2_not Cry_Scyther  @ 869F4DC
	cry2_not Cry_Jynx  @ 869F4E8
	cry2_not Cry_Electabuzz  @ 869F4F4
	cry2_not Cry_Magmar  @ 869F500
	cry2_not Cry_Pinsir  @ 869F50C
	cry2_not Cry_Tauros  @ 869F518
	cry2_not Cry_Magikarp  @ 869F524
	cry2_not Cry_Gyarados  @ 869F530
	cry2_not Cry_Lapras  @ 869F53C
	cry2_not Cry_Ditto  @ 869F548
	cry2_not Cry_Eevee  @ 869F554
	cry2_not Cry_Vaporeon  @ 869F560
	cry2_not Cry_Jolteon  @ 869F56C
	cry2_not Cry_Flareon  @ 869F578
	cry2_not Cry_Porygon  @ 869F584
	cry2_not Cry_Omanyte  @ 869F590
	cry2_not Cry_Omastar  @ 869F59C
	cry2_not Cry_Kabuto  @ 869F5A8
	cry2_not Cry_Kabutops  @ 869F5B4
	cry2_not Cry_Aerodactyl  @ 869F5C0
	cry2_not Cry_Snorlax  @ 869F5CC
	cry2_not Cry_Articuno  @ 869F5D8
	cry2_not Cry_Zapdos  @ 869F5E4
	cry2_not Cry_Moltres  @ 869F5F0
	cry2_not Cry_Dratini  @ 869F5FC
	cry2_not Cry_Dragonair  @ 869F608
	cry2_not Cry_Dragonite  @ 869F614
	cry2_not Cry_Mewtwo  @ 869F620
	cry2_not Cry_Mew  @ 869F62C
	cry2_not Cry_Chikorita  @ 869F638
	cry2_not Cry_Bayleef  @ 869F644
	cry2_not Cry_Meganium  @ 869F650
	cry2_not Cry_Cyndaquil  @ 869F65C
	cry2_not Cry_Quilava  @ 869F668
	cry2_not Cry_Typhlosion  @ 869F674
	cry2_not Cry_Totodile  @ 869F680
	cry2_not Cry_Croconaw  @ 869F68C
	cry2_not Cry_Feraligatr  @ 869F698
	cry2_not Cry_Sentret  @ 869F6A4
	cry2_not Cry_Furret  @ 869F6B0
	cry2_not Cry_Hoothoot  @ 869F6BC
	cry2_not Cry_Noctowl  @ 869F6C8
	cry2_not Cry_Ledyba  @ 869F6D4
	cry2_not Cry_Ledian  @ 869F6E0
	cry2_not Cry_Spinarak  @ 869F6EC
	cry2_not Cry_Ariados  @ 869F6F8
	cry2_not Cry_Crobat  @ 869F704
	cry2_not Cry_Chinchou  @ 869F710
	cry2_not Cry_Lanturn  @ 869F71C
	cry2_not Cry_Pichu  @ 869F728
	cry2_not Cry_Cleffa  @ 869F734
	cry2_not Cry_Igglybuff  @ 869F740
	cry2_not Cry_Togepi  @ 869F74C
	cry2_not Cry_Togetic  @ 869F758
	cry2_not Cry_Natu  @ 869F764
	cry2_not Cry_Xatu  @ 869F770
	cry2_not Cry_Mareep  @ 869F77C
	cry2_not Cry_Flaaffy  @ 869F788
	cry2_not Cry_Ampharos  @ 869F794
	cry2_not Cry_Bellossom  @ 869F7A0
	cry2_not Cry_Marill  @ 869F7AC
	cry2_not Cry_Azumarill  @ 869F7B8
	cry2_not Cry_Sudowoodo  @ 869F7C4
	cry2_not Cry_Politoed  @ 869F7D0
	cry2_not Cry_Hoppip  @ 869F7DC
	cry2_not Cry_Skiploom  @ 869F7E8
	cry2_not Cry_Jumpluff  @ 869F7F4
	cry2_not Cry_Aipom  @ 869F800
	cry2_not Cry_Sunkern  @ 869F80C
	cry2_not Cry_Sunflora  @ 869F818
	cry2_not Cry_Yanma  @ 869F824
	cry2_not Cry_Wooper  @ 869F830
	cry2_not Cry_Quagsire  @ 869F83C
	cry2_not Cry_Espeon  @ 869F848
	cry2_not Cry_Umbreon  @ 869F854
	cry2_not Cry_Murkrow  @ 869F860
	cry2_not Cry_Slowking  @ 869F86C
	cry2_not Cry_Misdreavus  @ 869F878
	cry2_not Cry_Unown  @ 869F884
	cry2_not Cry_Wobbuffet  @ 869F890
	cry2_not Cry_Girafarig  @ 869F89C
	cry2_not Cry_Pineco  @ 869F8A8
	cry2_not Cry_Forretress  @ 869F8B4
	cry2_not Cry_Dunsparce  @ 869F8C0
	cry2_not Cry_Gligar  @ 869F8CC
	cry2_not Cry_Steelix  @ 869F8D8
	cry2_not Cry_Snubbull  @ 869F8E4
	cry2_not Cry_Granbull  @ 869F8F0
	cry2_not Cry_Qwilfish  @ 869F8FC
	cry2_not Cry_Scizor  @ 869F908
	cry2_not Cry_Shuckle  @ 869F914
	cry2_not Cry_Heracross  @ 869F920
	cry2_not Cry_Sneasel  @ 869F92C
	cry2_not Cry_Teddiursa  @ 869F938
	cry2_not Cry_Ursaring  @ 869F944
	cry2_not Cry_Slugma  @ 869F950
	cry2_not Cry_Magcargo  @ 869F95C
	cry2_not Cry_Swinub  @ 869F968
	cry2_not Cry_Piloswine  @ 869F974
	cry2_not Cry_Corsola  @ 869F980
	cry2_not Cry_Remoraid  @ 869F98C
	cry2_not Cry_Octillery  @ 869F998
	cry2_not Cry_Delibird  @ 869F9A4
	cry2_not Cry_Mantine  @ 869F9B0
	cry2_not Cry_Skarmory  @ 869F9BC
	cry2_not Cry_Houndour  @ 869F9C8
	cry2_not Cry_Houndoom  @ 869F9D4
	cry2_not Cry_Kingdra  @ 869F9E0
	cry2_not Cry_Phanpy  @ 869F9EC
	cry2_not Cry_Donphan  @ 869F9F8
	cry2_not Cry_Porygon2  @ 869FA04
	cry2_not Cry_Stantler  @ 869FA10
	cry2_not Cry_Smeargle  @ 869FA1C
	cry2_not Cry_Tyrogue  @ 869FA28
	cry2_not Cry_Hitmontop  @ 869FA34
	cry2_not Cry_Smoochum  @ 869FA40
	cry2_not Cry_Elekid  @ 869FA4C
	cry2_not Cry_Magby  @ 869FA58
	cry2_not Cry_Miltank  @ 869FA64
	cry2_not Cry_Blissey  @ 869FA70
	cry2_not Cry_Raikou  @ 869FA7C
	cry2_not Cry_Entei  @ 869FA88
	cry2_not Cry_Suicune  @ 869FA94
	cry2_not Cry_Larvitar  @ 869FAA0
	cry2_not Cry_Pupitar  @ 869FAAC
	cry2_not Cry_Tyranitar  @ 869FAB8
	cry2_not Cry_Lugia  @ 869FAC4
	cry2_not Cry_HoOh  @ 869FAD0
	cry2_not Cry_Celebi  @ 869FADC
	cry2_not Cry_Treecko
	cry2_not Cry_Grovyle
	cry2_not Cry_Sceptile
	cry2_not Cry_Torchic
	cry2_not Cry_Combusken
	cry2_not Cry_Blaziken
	cry2_not Cry_Mudkip
	cry2_not Cry_Marshtomp
	cry2_not Cry_Swampert
	cry2_not Cry_Poochyena
	cry2_not Cry_Mightyena
	cry2_not Cry_Zigzagoon
	cry2_not Cry_Linoone
	cry2_not Cry_Wurmple
	cry2_not Cry_Silcoon
	cry2_not Cry_Beautifly
	cry2_not Cry_Cascoon
	cry2_not Cry_Dustox
	cry2_not Cry_Lotad
	cry2_not Cry_Lombre
	cry2_not Cry_Ludicolo
	cry2_not Cry_Seedot
	cry2_not Cry_Nuzleaf
	cry2_not Cry_Shiftry
	cry2_not Cry_Taillow
	cry2_not Cry_Swellow
	cry2_not Cry_Wingull
	cry2_not Cry_Pelipper
	cry2_not Cry_Ralts
	cry2_not Cry_Kirlia
	cry2_not Cry_Gardevoir
	cry2_not Cry_Surskit
	cry2_not Cry_Masquerain
	cry2_not Cry_Shroomish
	cry2_not Cry_Breloom
	cry2_not Cry_Slakoth
	cry2_not Cry_Vigoroth
	cry2_not Cry_Slaking
	cry2_not Cry_Nincada
	cry2_not Cry_Ninjask
	cry2_not Cry_Shedinja
	cry2_not Cry_Whismur
	cry2_not Cry_Loudred
	cry2_not Cry_Exploud
	cry2_not Cry_Makuhita
	cry2_not Cry_Hariyama
	cry2_not Cry_Azurill
	cry2_not Cry_Nosepass
	cry2_not Cry_Skitty
	cry2_not Cry_Delcatty
	cry2_not Cry_Sableye
	cry2_not Cry_Mawile
	cry2_not Cry_Aron
	cry2_not Cry_Lairon
	cry2_not Cry_Aggron
	cry2_not Cry_Meditite
	cry2_not Cry_Medicham
	cry2_not Cry_Electrike
	cry2_not Cry_Manectric
	cry2_not Cry_Plusle
	cry2_not Cry_Minun
	cry2_not Cry_Volbeat
	cry2_not Cry_Illumise
	cry2_not Cry_Roselia
	cry2_not Cry_Gulpin
	cry2_not Cry_Swalot
	cry2_not Cry_Carvanha
	cry2_not Cry_Sharpedo
	cry2_not Cry_Wailmer
	cry2_not Cry_Wailord
	cry2_not Cry_Numel
	cry2_not Cry_Camerupt
	cry2_not Cry_Torkoal
	cry2_not Cry_Spoink
	cry2_not Cry_Grumpig
	cry2_not Cry_Spinda
	cry2_not Cry_Trapinch
	cry2_not Cry_Vibrava
	cry2_not Cry_Flygon
	cry2_not Cry_Cacnea
	cry2_not Cry_Cacturne
	cry2_not Cry_Swablu
	cry2_not Cry_Altaria
	cry2_not Cry_Zangoose
	cry2_not Cry_Seviper
	cry2_not Cry_Lunatone
	cry2_not Cry_Solrock
	cry2_not Cry_Barboach
	cry2_not Cry_Whiscash
	cry2_not Cry_Corphish
	cry2_not Cry_Crawdaunt
	cry2_not Cry_Baltoy
	cry2_not Cry_Claydol
	cry2_not Cry_Lileep
	cry2_not Cry_Cradily
	cry2_not Cry_Anorith
	cry2_not Cry_Armaldo
	cry2_not Cry_Feebas
	cry2_not Cry_Milotic
	cry2_not Cry_Castform
	cry2_not Cry_Kecleon
	cry2_not Cry_Shuppet
	cry2_not Cry_Banette
	cry2_not Cry_Duskull
	cry2_not Cry_Dusclops
	cry2_not Cry_Tropius
	cry2_not Cry_Onix
	cry2_not Cry_Absol
	cry2_not Cry_Wynaut
	cry2_not Cry_Snorunt
	cry2_not Cry_Glalie
	cry2_not Cry_Spheal
	cry2_not Cry_Sealeo
	cry2_not Cry_Walrein
	cry2_not Cry_Clamperl
	cry2_not Cry_Huntail
	cry2_not Cry_Gorebyss
	cry2_not Cry_Relicanth
	cry2_not Cry_Luvdisc
	cry2_not Cry_Bagon
	cry2_not Cry_Shelgon
	cry2_not Cry_Salamence
	cry2_not Cry_Beldum
	cry2_not Cry_Metang
	cry2_not Cry_Metagross
	cry2_not Cry_Regirock
	cry2_not Cry_Regice
	cry2_not Cry_Registeel
	cry2_not Cry_Latias
	cry2_not Cry_Latios
	cry2_not Cry_Kyogre
	cry2_not Cry_Groudon
	cry2_not Cry_Rayquaza
	cry2_not Cry_Jirachi
	cry2_not Cry_Deoxys
	cry2_not Cry_Turtwig
	cry2_not Cry_Grotle
	cry2_not Cry_Torterra
	cry2_not Cry_Chimchar
	cry2_not Cry_Monferno
	cry2_not Cry_Infernape
	cry2_not Cry_Piplup
	cry2_not Cry_Prinplup
	cry2_not Cry_Empoleon
	cry2_not Cry_Starly
	cry2_not Cry_Staravia
	cry2_not Cry_Staraptor
	cry2_not Cry_Bidoof
	cry2_not Cry_Bibarel
	cry2_not Cry_Kricketot
	cry2_not Cry_Kricketune
	cry2_not Cry_Shinx
	cry2_not Cry_Luxio
	cry2_not Cry_Luxray
	cry2_not Cry_Budew
	cry2_not Cry_Roserade
	cry2_not Cry_Cranidos
	cry2_not Cry_Rampardos
	cry2_not Cry_Shieldon
	cry2_not Cry_Bastiodon
	cry2_not Cry_Burmy
	cry2_not Cry_Wormadam
	cry2_not Cry_Mothim
	cry2_not Cry_Combee
	cry2_not Cry_Vespiquen
	cry2_not Cry_Pachirisu
	cry2_not Cry_Buizel
	cry2_not Cry_Floatzel
	cry2_not Cry_Cherubi
	cry2_not Cry_Cherrim
	cry2_not Cry_Shellos
	cry2_not Cry_Gastrodon
	cry2_not Cry_Ambipom
	cry2_not Cry_Drifloon
	cry2_not Cry_Drifblim
	cry2_not Cry_Buneary
	cry2_not Cry_Lopunny
	cry2_not Cry_Mismagius
	cry2_not Cry_Honchkrow
	cry2_not Cry_Glameow
	cry2_not Cry_Purugly
	cry2_not Cry_Chingling
	cry2_not Cry_Stunky
	cry2_not Cry_Skuntank
	cry2_not Cry_Bronzor
	cry2_not Cry_Bronzong
	cry2_not Cry_Bonsly
	cry2_not Cry_Mimejr
	cry2_not Cry_Happiny
	cry2_not Cry_Chatot
	cry2_not Cry_Spiritomb
	cry2_not Cry_Gible
	cry2_not Cry_Gabite
	cry2_not Cry_Garchomp
	cry2_not Cry_Munchlax
	cry2_not Cry_Riolu
	cry2_not Cry_Lucario
	cry2_not Cry_Hippopotas
	cry2_not Cry_Hippowdon
	cry2_not Cry_Skorupi
	cry2_not Cry_Drapion
	cry2_not Cry_Croagunk
	cry2_not Cry_Toxicroak
	cry2_not Cry_Carnivine
	cry2_not Cry_Finneon
	cry2_not Cry_Lumineon
	cry2_not Cry_Mantyke
	cry2_not Cry_Snover
	cry2_not Cry_Abomasnow
	cry2_not Cry_Weavile
	cry2_not Cry_Magnezone
	cry2_not Cry_Lickilicky
	cry2_not Cry_Rhyperior
	cry2_not Cry_Tangrowth
	cry2_not Cry_Electivire
	cry2_not Cry_Magmortar
	cry2_not Cry_Togekiss
	cry2_not Cry_Yanmega
	cry2_not Cry_Leafeon
	cry2_not Cry_Glaceon
	cry2_not Cry_Gliscor
	cry2_not Cry_Mamoswine
	cry2_not Cry_PorygonZ
	cry2_not Cry_Gallade
	cry2_not Cry_Probopass
	cry2_not Cry_Dusknoir
	cry2_not Cry_Froslass
	cry2_not Cry_Rotom
	cry2_not Cry_Uxie
	cry2_not Cry_Mesprit
	cry2_not Cry_Azelf
	cry2_not Cry_Dialga
	cry2_not Cry_Palkia
	cry2_not Cry_Heatran
	cry2_not Cry_Regigigas
	cry2_not Cry_Giratina
	cry2_not Cry_Cresselia
	cry2_not Cry_Phione
	cry2_not Cry_Manaphy
	cry2_not Cry_Darkrai
	cry2_not Cry_Shaymin
	cry2_not Cry_Arceus
	cry2_not Cry_Victini
	cry2_not Cry_Snivy
	cry2_not Cry_Servine
	cry2_not Cry_Serperior
	cry2_not Cry_Tepig
	cry2_not Cry_Pignite
	cry2_not Cry_Emboar
	cry2_not Cry_Oshawott
	cry2_not Cry_Dewott
	cry2_not Cry_Samurott
	cry2_not Cry_Patrat
	cry2_not Cry_Watchog
	cry2_not Cry_Lillipup
	cry2_not Cry_Herdier
	cry2_not Cry_Stoutland
	cry2_not Cry_Purrloin
	cry2_not Cry_Liepard
	cry2_not Cry_Pansage
	cry2_not Cry_Simisage
	cry2_not Cry_Pansear
	cry2_not Cry_Simisear
	cry2_not Cry_Panpour
	cry2_not Cry_Simipour
	cry2_not Cry_Munna
	cry2_not Cry_Musharna
	cry2_not Cry_Pidove
	cry2_not Cry_Tranquill
	cry2_not Cry_Unfezant
	cry2_not Cry_Blitzle
	cry2_not Cry_Zebstrika
	cry2_not Cry_Roggenrola
	cry2_not Cry_Boldore
	cry2_not Cry_Gigalith
	cry2_not Cry_Woobat
	cry2_not Cry_Swoobat
	cry2_not Cry_Drilbur
	cry2_not Cry_Excadrill
	cry2_not Cry_Audino
	cry2_not Cry_Timburr
	cry2_not Cry_Gurdurr
	cry2_not Cry_Conkeldurr
	cry2_not Cry_Tympole
	cry2_not Cry_Palpitoad
	cry2_not Cry_Seismitoad
	cry2_not Cry_Throh
	cry2_not Cry_Sawk
	cry2_not Cry_Sewaddle
	cry2_not Cry_Swadloon
	cry2_not Cry_Leavanny
	cry2_not Cry_Venipede
	cry2_not Cry_Whirlipede
	cry2_not Cry_Scolipede
	cry2_not Cry_Cottonee
	cry2_not Cry_Whimsicott
	cry2_not Cry_Petilil
	cry2_not Cry_Lilligant
	cry2_not Cry_Basculin
	cry2_not Cry_Sandile
	cry2_not Cry_Krokorok
	cry2_not Cry_Krookodile
	cry2_not Cry_Darumaka
	cry2_not Cry_Darmanitan
	cry2_not Cry_Maractus
	cry2_not Cry_Dwebble
	cry2_not Cry_Crustle
	cry2_not Cry_Scraggy
	cry2_not Cry_Scrafty
	cry2_not Cry_Sigilyph
	cry2_not Cry_Yamask
	cry2_not Cry_Cofagrigus
	cry2_not Cry_Tirtouga
	cry2_not Cry_Carracosta
	cry2_not Cry_Archen
	cry2_not Cry_Archeops
	cry2_not Cry_Trubbish
	cry2_not Cry_Garbodor
	cry2_not Cry_Zorua
	cry2_not Cry_Zoroark
	cry2_not Cry_Minccino
	cry2_not Cry_Cinccino
	cry2_not Cry_Gothita
	cry2_not Cry_Gothorita
	cry2_not Cry_Gothitelle
	cry2_not Cry_Solosis
	cry2_not Cry_Duosion
	cry2_not Cry_Reuniclus
	cry2_not Cry_Ducklett
	cry2_not Cry_Swanna
	cry2_not Cry_Vanillite
	cry2_not Cry_Vanillish
	cry2_not Cry_Vanilluxe
	cry2_not Cry_Deerling
	cry2_not Cry_Sawsbuck
	cry2_not Cry_Emolga
	cry2_not Cry_Karrablast
	cry2_not Cry_Escavalier
	cry2_not Cry_Foongus
	cry2_not Cry_Amoonguss
	cry2_not Cry_Frillish
	cry2_not Cry_Jellicent
	cry2_not Cry_Alomomola
	cry2_not Cry_Joltik
	cry2_not Cry_Galvantula
	cry2_not Cry_Ferroseed
	cry2_not Cry_Ferrothorn
	cry2_not Cry_Klink
	cry2_not Cry_Klang
	cry2_not Cry_Klinklang
	cry2_not Cry_Tynamo
	cry2_not Cry_Eelektrik
	cry2_not Cry_Eelektross
	cry2_not Cry_Elgyem
	cry2_not Cry_Beheeyem
	cry2_not Cry_Litwick
	cry2_not Cry_Lampent
	cry2_not Cry_Chandelure
	cry2_not Cry_Axew
	cry2_not Cry_Fraxure
	cry2_not Cry_Haxorus
	cry2_not Cry_Cubchoo
	cry2_not Cry_Beartic
	cry2_not Cry_Cryogonal
	cry2_not Cry_Shelmet
	cry2_not Cry_Accelgor
	cry2_not Cry_Stunfisk
	cry2_not Cry_Mienfoo
	cry2_not Cry_Mienshao
	cry2_not Cry_Druddigon
	cry2_not Cry_Golett
	cry2_not Cry_Golurk
	cry2_not Cry_Pawniard
	cry2_not Cry_Bisharp
	cry2_not Cry_Bouffalant
	cry2_not Cry_Rufflet
	cry2_not Cry_Braviary
	cry2_not Cry_Vullaby
	cry2_not Cry_Mandibuzz
	cry2_not Cry_Heatmor
	cry2_not Cry_Durant
	cry2_not Cry_Deino
	cry2_not Cry_Zweilous
	cry2_not Cry_Hydreigon
	cry2_not Cry_Larvesta
	cry2_not Cry_Volcarona
	cry2_not Cry_Cobalion
	cry2_not Cry_Terrakion
	cry2_not Cry_Virizion
	cry2_not Cry_Tornadus
	cry2_not Cry_Thundurus
	cry2_not Cry_Reshiram
	cry2_not Cry_Zekrom
	cry2_not Cry_Landorus
	cry2_not Cry_Kyurem
	cry2_not Cry_Keldeo
	cry2_not Cry_Meloetta
	cry2_not Cry_Genesect
	cry2_not Cry_Chespin
	cry2_not Cry_Quilladin
	cry2_not Cry_Chesnaught
	cry2_not Cry_Fennekin
	cry2_not Cry_Braixen
	cry2_not Cry_Delphox
	cry2_not Cry_Froakie
	cry2_not Cry_Frogadier
	cry2_not Cry_Greninja
	cry2_not Cry_Bunnelby
	cry2_not Cry_Diggersby
	cry2_not Cry_Fletchling
	cry2_not Cry_Fletchinder
	cry2_not Cry_Talonflame
	cry2_not Cry_Scatterbug
	cry2_not Cry_Spewpa
	cry2_not Cry_Vivillon
	cry2_not Cry_Litleo
	cry2_not Cry_Pyroar
	cry2_not Cry_Flabebe
	cry2_not Cry_Floette
	cry2_not Cry_Florges
	cry2_not Cry_Skiddo
	cry2_not Cry_Gogoat
	cry2_not Cry_Pancham
	cry2_not Cry_Pangoro
	cry2_not Cry_Furfrou
	cry2_not Cry_Espurr
	cry2_not Cry_Meowstic
	cry2_not Cry_Honedge
	cry2_not Cry_Doublade
	cry2_not Cry_Aegislash
	cry2_not Cry_Spritzee
	cry2_not Cry_Aromatisse
	cry2_not Cry_Swirlix
	cry2_not Cry_Slurpuff
	cry2_not Cry_Inkay
	cry2_not Cry_Malamar
	cry2_not Cry_Binacle
	cry2_not Cry_Barbaracle
	cry2_not Cry_Skrelp
	cry2_not Cry_Dragalge
	cry2_not Cry_Clauncher
	cry2_not Cry_Clawitzer
	cry2_not Cry_Helioptile
	cry2_not Cry_Heliolisk
	cry2_not Cry_Tyrunt
	cry2_not Cry_Tyrantrum
	cry2_not Cry_Amaura
	cry2_not Cry_Aurorus
	cry2_not Cry_Sylveon
	cry2_not Cry_Hawlucha
	cry2_not Cry_Dedenne
	cry2_not Cry_Carbink
	cry2_not Cry_Goomy
	cry2_not Cry_Sliggoo
	cry2_not Cry_Goodra
	cry2_not Cry_Klefki
	cry2_not Cry_Phantump
	cry2_not Cry_Trevenant
	cry2_not Cry_Pumpkaboo
	cry2_not Cry_Gourgeist
	cry2_not Cry_Bergmite
	cry2_not Cry_Avalugg
	cry2_not Cry_Noibat
	cry2_not Cry_Noivern
	cry2_not Cry_Xerneas
	cry2_not Cry_Yveltal
	cry2_not Cry_Zygarde
	cry2_not Cry_Diancie
	cry2_not Cry_Hoopa
	cry2_not Cry_Volcanion
	cry2_not Cry_Rowlet
	cry2_not Cry_Dartrix
	cry2_not Cry_Decidueye
	cry2_not Cry_Litten
	cry2_not Cry_Torracat
	cry2_not Cry_Incineroar
	cry2_not Cry_Popplio
	cry2_not Cry_Brionne
	cry2_not Cry_Primarina
	cry2_not Cry_Pikipek
	cry2_not Cry_Trumbeak
	cry2_not Cry_Toucannon
	cry2_not Cry_Yungoos
	cry2_not Cry_Gumshoos
	cry2_not Cry_Grubbin
	cry2_not Cry_Charjabug
	cry2_not Cry_Vikavolt
	cry2_not Cry_Crabrawler
	cry2_not Cry_Crabominable
	cry2_not Cry_Oricorio
	cry2_not Cry_Cutiefly
	cry2_not Cry_Ribombee
	cry2_not Cry_Rockruff
	cry2_not Cry_Lycanroc
	cry2_not Cry_Wishiwashi
	cry2_not Cry_Mareanie
	cry2_not Cry_Toxapex
	cry2_not Cry_Mudbray
	cry2_not Cry_Mudsdale
	cry2_not Cry_Dewpider
	cry2_not Cry_Araquanid
	cry2_not Cry_Fomantis
	cry2_not Cry_Lurantis
	cry2_not Cry_Morelull
	cry2_not Cry_Shiinotic
	cry2_not Cry_Salandit
	cry2_not Cry_Salazzle
	cry2_not Cry_Stufful
	cry2_not Cry_Bewear
	cry2_not Cry_Bounsweet
	cry2_not Cry_Steenee
	cry2_not Cry_Tsareena
	cry2_not Cry_Comfey
	cry2_not Cry_Oranguru
	cry2_not Cry_Passimian
	cry2_not Cry_Wimpod
	cry2_not Cry_Golisopod
	cry2_not Cry_Sandygast
	cry2_not Cry_Palossand
	cry2_not Cry_Pyukumuku
	cry2_not Cry_Type_null
	cry2_not Cry_Silvally
	cry2_not Cry_Minior
	cry2_not Cry_Komala
	cry2_not Cry_Turtonator
	cry2_not Cry_Togedemaru
	cry2_not Cry_Mimikyu
	cry2_not Cry_Bruxish
	cry2_not Cry_Drampa
	cry2_not Cry_Dhelmise
	cry2_not Cry_Jangmo_o
	cry2_not Cry_Hakamo_o
	cry2_not Cry_Kommo_o
	cry2_not Cry_Tapu_koko
	cry2_not Cry_Tapu_lele
	cry2_not Cry_Tapu_bulu
	cry2_not Cry_Tapu_fini
	cry2_not Cry_Cosmog
	cry2_not Cry_Cosmoem
	cry2_not Cry_Solgaleo
	cry2_not Cry_Lunala
	cry2_not Cry_Nihilego
	cry2_not Cry_Buzzwole
	cry2_not Cry_Pheromosa
	cry2_not Cry_Xurkitree
	cry2_not Cry_Celesteela
	cry2_not Cry_Kartana
	cry2_not Cry_Guzzlord
	cry2_not Cry_Necrozma
	cry2_not Cry_Magearna
	cry2_not Cry_Marshadow
	cry2_not Cry_Poipole
	cry2_not Cry_Naganadel
	cry2_not Cry_Stakataka
	cry2_not Cry_Blacephalon
	cry2_not Cry_Zeraora
	cry2_not Cry_Meltan
	cry2_not Cry_Melmetal
	@ Megas
	cry2_not Cry_Ampharos
	cry2_not Cry_Venusaur
	cry2_not Cry_Charizard
	cry2_not Cry_Charizard
	cry2_not Cry_Mewtwo
	cry2_not Cry_Mewtwo
	cry2_not Cry_Blaziken
	cry2_not Cry_Medicham
	cry2_not Cry_Houndoom
	cry2_not Cry_Aggron
	cry2_not Cry_Banette
	cry2_not Cry_Tyranitar
	cry2_not Cry_Scizor
	cry2_not Cry_Pinsir
	cry2_not Cry_Aerodactyl
	cry2_not Cry_Lucario
	cry2_not Cry_Abomasnow
	cry2_not Cry_Blastoise
	cry2_not Cry_Kangaskhan
	cry2_not Cry_Gyarados
	cry2_not Cry_Absol
	cry2_not Cry_Alakazam
	cry2_not Cry_Heracross
	cry2_not Cry_Mawile
	cry2_not Cry_Manectric
	cry2_not Cry_Garchomp
	cry2_not Cry_Latios
	cry2_not Cry_Latias
	cry2_not Cry_Swampert
	cry2_not Cry_Sceptile
	cry2_not Cry_Sableye
	cry2_not Cry_Altaria
	cry2_not Cry_Gallade
	cry2_not Cry_Audino
	cry2_not Cry_Sharpedo
	cry2_not Cry_Slowbro
	cry2_not Cry_Steelix
	cry2_not Cry_Pidgeot
	cry2_not Cry_Glalie
	cry2_not Cry_Diancie
	cry2_not Cry_Metagross
	cry2_not Cry_Rayquaza
	cry2_not Cry_Camerupt
	cry2_not Cry_Lopunny
	cry2_not Cry_Salamence
	cry2_not Cry_Beedrill
	cry2_not Cry_Gengar
	cry2_not Cry_Gardevoir
	@ Forms
	cry2_not Cry_Burmy_Sandy
	cry2_not Cry_Burmy_Trash
	cry2_not Cry_Wormadam_Sandy
	cry2_not Cry_Wormadam_Trash
	cry2_not Cry_Rotom_Heat
	cry2_not Cry_Rotom_Wash
	cry2_not Cry_Rotom_Frost
	cry2_not Cry_Rotom_Fan
	cry2_not Cry_Rotom_Mow
	cry2_not Cry_Kyurem_Black
	cry2_not Cry_Kyurem_White
	cry2_not Cry_Meowstic_F
	@ Alolan Forms
	cry2_not Cry_Alolan_Rattata
	cry2_not Cry_Alolan_Raticate
	cry2_not Cry_Alolan_Raichu
	cry2_not Cry_Alolan_Sandshrew
	cry2_not Cry_Alolan_Sandslash
	cry2_not Cry_Alolan_Vulpix
	cry2_not Cry_Alolan_Ninetales
	cry2_not Cry_Alolan_Diglett
	cry2_not Cry_Alolan_Dugtrio
	cry2_not Cry_Alolan_Meowth
	cry2_not Cry_Alolan_Persian
	cry2_not Cry_Alolan_Geodude
	cry2_not Cry_Alolan_Graveler
	cry2_not Cry_Alolan_Golem
	cry2_not Cry_Alolan_Grimer
	cry2_not Cry_Alolan_Muk
	cry2_not Cry_Alolan_Exeggutor
	cry2_not Cry_Alolan_Marowak
	@ Form Changes
	cry2_not Cry_Primal_Kyogre
	cry2_not Cry_Primal_Groudon
	cry2_not Cry_Shaymin_Sky
	cry2_not Cry_Giratina_Origin
	cry2_not Cry_Darmanitan_Zen
	cry2_not Cry_Tornadus_Therian
	cry2_not Cry_Thundurus_Therian
	cry2_not Cry_Landorus_Therian
	cry2_not Cry_Meloetta_Pirouette
	cry2_not Cry_Aegislash_Blade
	cry2_not Cry_Hoopa_Unbound
	cry2_not Cry_Minior_Core
	cry2_not Cry_Unown_School
	cry2_not Cry_Mimikyu_Busted
	cry2_not Cry_Lycanroc_Midnight
	cry2_not Cry_Lycanroc_Dusk
	cry2_not Cry_Zygarde_10
	cry2_not Cry_Zygarde_Complete
	cry2 Cry_Deoxys_Attack
	cry2 Cry_Deoxys_Defense
	cry2 Cry_Deoxys_Speed
