	.align 2

gSongTable:: @ 86B49F0
	song mus_dummy, 0, 0
	song se_use_item, 1, 1
	song se_pc_login, 1, 1
	song se_pc_off, 1, 1
	song se_pc_on, 1, 1
	song se_select, 2, 2
	song se_win_open, 1, 1
	song se_wall_hit, 2, 2
	song se_door, 1, 1
	song se_exit, 1, 1
	song se_ledge, 1, 1
	song se_bike_bell, 1, 1
	song se_not_effective, 1, 1
	song se_effective, 1, 1
	song se_super_effective, 1, 1
	song se_ball_open, 1, 1
	song se_faint, 1, 1
	song se_flee, 1, 1
	song se_sliding_door, 1, 1
	song se_ship, 1, 1
	song se_bang, 1, 1
	song se_pin, 1, 1
	song se_boo, 1, 1
	song se_ball, 1, 1
	song se_contest_place, 2, 2
	song se_a, 1, 1
	song se_i, 1, 1
	song se_u, 1, 1
	song se_e, 1, 1
	song se_o, 1, 1
	song se_n, 1, 1
	song se_success, 1, 1
	song se_failure, 1, 1
	song se_exp, 1, 1
	song se_bike_hop, 1, 1
	song se_switch, 1, 1
	song se_click, 1, 1
	song se_fu_zaku, 1, 1
	song se_contest_condition_lose, 1, 1
	song se_lavaridge_fall_warp, 1, 1
	song se_ice_stairs, 1, 1
	song se_ice_break, 1, 1
	song se_ice_crack, 1, 1
	song se_fall, 1, 1
	song se_unlock, 2, 2
	song se_warp_in, 1, 1
	song se_warp_out, 1, 1
	song se_repel, 1, 1
	song se_rotating_gate, 1, 1
	song se_truck_move, 1, 1
	song se_truck_stop, 1, 1
	song se_truck_unload, 2, 2
	song se_truck_door, 1, 1
	song se_berry_blender, 2, 2
	song se_card, 1, 1
	song se_save, 1, 1
	song se_ball_bounce_1, 1, 1
	song se_ball_bounce_2, 1, 1
	song se_ball_bounce_3, 1, 1
	song se_ball_bounce_4, 1, 1
	song se_ball_trade, 2, 2
	song se_ball_throw, 1, 1
	song se_note_c, 2, 2
	song se_note_d, 2, 2
	song se_note_e, 2, 2
	song se_note_f, 2, 2
	song se_note_g, 2, 2
	song se_note_a, 2, 2
	song se_note_b, 2, 2
	song se_note_c_high, 2, 2
	song se_puddle, 2, 2
	song se_bridge_walk, 2, 2
	song se_itemfinder, 1, 1
	song se_ding_dong, 1, 1
	song se_balloon_red, 2, 2
	song se_balloon_blue, 2, 2
	song se_balloon_yellow, 2, 2
	song se_breakable_door, 2, 2
	song se_mud_ball, 2, 2
	song se_field_poison, 1, 1
	song se_escalator, 1, 1
	song se_thunderstorm, 3, 3
	song se_thunderstorm_stop, 3, 3
	song se_downpour, 3, 3
	song se_downpour_stop, 3, 3
	song se_rain, 3, 3
	song se_rain_stop, 3, 3
	song se_thunder, 1, 1
	song se_thunder2, 1, 1
	song se_elevator, 1, 1
	song se_low_health, 3, 3
	song se_exp_max, 1, 1
	song se_roulette_ball, 2, 2
	song se_roulette_ball2, 2, 2
	song se_taillow_wing_flap, 1, 1
	song se_shop, 1, 1
	song se_contest_heart, 1, 1
	song se_contest_curtain_rise, 1, 1
	song se_contest_curtain_fall, 1, 1
	song se_contest_icon_change, 1, 1
	song se_contest_icon_clear, 1, 1
	song se_contest_mons_turn, 1, 1
	song se_shiny, 1, 1
	song se_intro_blast, 1, 1
	song se_mugshot, 1, 1
	song se_applause, 1, 1
	song se_vend, 1, 1
	song se_orb, 1, 1
	song se_dex_scroll, 1, 1
	song se_dex_page, 1, 1
	song se_pokenav_on, 1, 1
	song se_pokenav_off, 1, 1
	song se_dex_search, 1, 1
	song se_egg_hatch, 1, 1
	song se_ball_tray_enter, 1, 1
	song se_ball_tray_ball, 1, 1
	song se_ball_tray_exit, 2, 2
	song se_glass_flute, 1, 1
	song se_m_thunderbolt, 2, 2
	song se_m_thunderbolt2, 1, 1
	song se_m_harden, 1, 1
	song se_m_nightmare, 1, 1
	song se_m_vital_throw, 1, 1
	song se_m_vital_throw2, 1, 1
	song se_m_bubble, 1, 1
	song se_m_bubble2, 1, 1
	song se_m_bubble3, 1, 1
	song se_m_rain_dance, 1, 1
	song se_m_cut, 1, 1
	song se_m_string_shot, 1, 1
	song se_m_string_shot2, 1, 1
	song se_m_rock_throw, 1, 1
	song se_m_gust, 2, 2
	song se_m_gust2, 2, 2
	song se_m_double_slap, 1, 1
	song se_m_double_team, 1, 1
	song se_m_razor_wind, 1, 1
	song se_m_icy_wind, 1, 1
	song se_m_thunder_wave, 1, 1
	song se_m_comet_punch, 1, 1
	song se_m_mega_kick, 1, 1
	song se_m_mega_kick2, 1, 1
	song se_m_crabhammer, 1, 1
	song se_m_jump_kick, 1, 1
	song se_m_flame_wheel, 1, 1
	song se_m_flame_wheel2, 1, 1
	song se_m_flamethrower, 1, 1
	song se_m_fire_punch, 1, 1
	song se_m_toxic, 1, 1
	song se_m_sacred_fire, 1, 1
	song se_m_sacred_fire2, 2, 2
	song se_m_ember, 1, 1
	song se_m_take_down, 2, 2
	song se_m_blizzard, 1, 1
	song se_m_blizzard2, 1, 1
	song se_m_scratch, 1, 1
	song se_m_vicegrip, 1, 1
	song se_m_wing_attack, 1, 1
	song se_m_fly, 1, 1
	song se_m_sand_attack, 1, 1
	song se_m_razor_wind2, 1, 1
	song se_m_bite, 1, 1
	song se_m_headbutt, 1, 1
	song se_m_surf, 1, 1
	song se_m_hydro_pump, 1, 1
	song se_m_whirlpool, 1, 1
	song se_m_horn_attack, 1, 1
	song se_m_tail_whip, 2, 2
	song se_m_mist, 1, 1
	song se_m_poison_powder, 1, 1
	song se_m_bind, 2, 2
	song se_m_dragon_rage, 1, 1
	song se_m_sing, 1, 1
	song se_m_perish_song, 1, 1
	song se_m_pay_day, 1, 1
	song se_m_dig, 1, 1
	song se_m_dizzy_punch, 1, 1
	song se_m_self_destruct, 1, 1
	song se_m_explosion, 1, 1
	song se_m_absorb_2, 1, 1
	song se_m_absorb, 1, 1
	song se_m_screech, 1, 1
	song se_m_bubble_beam, 1, 1
	song se_m_bubble_beam2, 1, 1
	song se_m_supersonic, 1, 1
	song se_m_belly_drum, 1, 1
	song se_m_metronome, 1, 1
	song se_m_bonemerang, 1, 1
	song se_m_lick, 1, 1
	song se_m_psybeam, 1, 1
	song se_m_faint_attack, 1, 1
	song se_m_swords_dance, 1, 1
	song se_m_leer, 1, 1
	song se_m_swagger, 1, 1
	song se_m_swagger2, 1, 1
	song se_m_heal_bell, 1, 1
	song se_m_confuse_ray, 1, 1
	song se_m_snore, 1, 1
	song se_m_brick_break, 1, 1
	song se_m_giga_drain, 1, 1
	song se_m_psybeam2, 1, 1
	song se_m_solar_beam, 2, 2
	song se_m_petal_dance, 1, 1
	song se_m_teleport, 1, 1
	song se_m_minimize, 1, 1
	song se_m_sketch, 1, 1
	song se_m_swift, 1, 1
	song se_m_reflect, 1, 1
	song se_m_barrier, 1, 1
	song se_m_detect, 2, 2
	song se_m_lock_on, 1, 1
	song se_m_moonlight, 1, 1
	song se_m_charm, 1, 1
	song se_m_charge, 1, 1
	song se_m_strength, 1, 1
	song se_m_hyper_beam, 1, 1
	song se_m_waterfall, 1, 1
	song se_m_reversal, 1, 1
	song se_m_acid_armor, 1, 1
	song se_m_sandstorm, 1, 1
	song se_m_tri_attack, 1, 1
	song se_m_tri_attack2, 1, 1
	song se_m_encore, 1, 1
	song se_m_encore2, 2, 2
	song se_m_baton_pass, 1, 1
	song se_m_milk_drink, 1, 1
	song se_m_attract, 1, 1
	song se_m_attract2, 1, 1
	song se_m_morning_sun, 1, 1
	song se_m_flatter, 1, 1
	song se_m_sand_tomb, 1, 1
	song se_m_grasswhistle, 1, 1
	song se_m_spit_up, 1, 1
	song se_m_dive, 1, 1
	song se_m_earthquake, 2, 2
	song se_m_twister, 2, 2
	song se_m_sweet_scent, 1, 1
	song se_m_yawn, 1, 1
	song se_m_sky_uppercut, 2, 2
	song se_m_stat_increase, 1, 1
	song se_m_heat_wave, 1, 1
	song se_m_uproar, 1, 1
	song se_m_hail, 1, 1
	song se_m_cosmic_power, 2, 2
	song se_m_teeter_dance, 1, 1
	song se_m_stat_decrease, 1, 1
	song se_m_haze, 1, 1
	song se_m_hyper_beam2, 1, 1
	song se_rg_door, 1, 1
	song se_rg_card_flip, 1, 1
	song se_rg_card_flipping, 1, 1
	song se_rg_card_open, 1, 1
	song se_rg_bag_cursor, 1, 1
	song se_rg_bag_pocket, 1, 1
	song se_rg_ball_click, 1, 1
	song se_rg_shop, 1, 1
	song se_rg_ss_anne_horn, 1, 1
	song se_rg_help_open, 1, 1
	song se_rg_help_close, 1, 1
	song se_rg_help_error, 1, 1
	song se_rg_deoxys_move, 1, 1
	song se_rg_poke_jump_success, 1, 1
	song se_rg_poke_jump_failure, 1, 1
	song se_pokenav_call, 1, 1
	song se_pokenav_hang_up, 1, 1
	song se_arena_timeup1, 1, 1
	song se_arena_timeup2, 1, 1
	song se_pike_curtain_close, 1, 1
	song se_pike_curtain_open, 1, 1
	song se_sudowoodo_shake, 1, 1
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song mus_tetsuji, 0, 0          @ Unused - TETSUJI
	song mus_field13, 0, 0          @ Unused - Route 38
	song mus_kachi22, 0, 2          @ Victory! (Wild Pokémon) (No Intro)
	song mus_kachi2, 0, 2           @ Victory! (Wild Pokémon)
	song mus_kachi3, 0, 2           @ Victory! (Gym Leader)
	song mus_kachi5, 0, 2           @ Victory! (Wallace)
	song mus_pcc, 0, 0              @ Unused - Pokémon Center (2)
	song mus_nibi, 0, 0             @ Unused - Viridian City
	song mus_suikun, 0, 0           @ Unused - Battle! (Entei/Raikou/Suicune)
	song mus_dooro1, 0, 0           @ Route 101
	song mus_dooro_x1, 0, 0         @ Route 110
	song mus_dooro_x3, 0, 0         @ Route 120
	song mus_machi_s2, 0, 0         @ Petalburg City
	song mus_machi_s4, 0, 0         @ Oldale Town
	song mus_gim, 0, 0              @ Pokémon Gym
	song mus_naminori, 0, 0         @ Surf
	song mus_dan01, 0, 0            @ Petalburg Woods
	song mus_fanfa1, 2, 2           @ Level Up!
	song mus_me_asa, 2, 2           @ Pokémon Healed
	song mus_me_bachi, 2, 2         @ Obtained a Badge!
	song mus_fanfa4, 2, 2           @ Obtained an Item!
	song mus_fanfa5, 2, 2           @ Congratulations! Your Pokémon Evolved!
	song mus_me_waza, 2, 2          @ Obtained a TM!
	song mus_bijyutu, 0, 0          @ Museum
	song mus_dooro_x4, 0, 0         @ Introductions
	song mus_fune_kan, 0, 0         @ Oceanic Museum
	song mus_me_shinka, 2, 2        @ Evolution (Intro)
	song mus_shinka, 0, 2           @ Evolution
	song mus_me_wasure, 2, 2        @ Move Deleted
	song mus_syoujoeye, 0, 0        @ Trainers' Eyes Meet (Tuber♀)
	song mus_boyeye, 0, 0           @ Trainers' Eyes Meet (Youngster)
	song mus_dan02, 0, 0            @ Abandoned Ship
	song mus_machi_s3, 0, 0         @ Fortree City
	song mus_odamaki, 0, 0          @ Birch Pokémon Lab
	song mus_b_tower, 0, 0          @ Battle Tower (RS)
	song mus_swimeye, 0, 0          @ Trainers' Eyes Meet (Swimmer♀)
	song mus_dan03, 0, 0            @ Cave of Origin
	song mus_me_kinomi, 2, 2        @ Obtained a Berry!
	song mus_me_tama, 2, 2          @ The Super-Ancient Pokémon Awaken!
	song mus_me_b_big, 2, 2         @ Jackpot
	song mus_me_b_small, 2, 2       @ Win
	song mus_me_zannen, 2, 2        @ Lose
	song mus_bd_time, 0, 2          @ Reel Time
	song mus_test1, 0, 2            @ Pokémon Contest! (Multiplayer - Player 1)
	song mus_test2, 0, 2            @ Pokémon Contest! (Multiplayer - Player 2)
	song mus_test3, 0, 2            @ Pokémon Contest! (Multiplayer - Player 3)
	song mus_test4, 0, 2            @ Pokémon Contest! (Multiplayer - Player 4)
	song mus_test, 0, 2             @ Trainers' Eyes Meet (Gentleman)
	song mus_gomachi0, 0, 0         @ Verdanturf Town
	song mus_gotown, 0, 0           @ Rustboro City
	song mus_pokecen, 0, 0          @ Pokémon Center
	song mus_nextroad, 0, 0         @ Route 104
	song mus_granroad, 0, 0         @ Route 119
	song mus_cycling, 0, 0          @ Cycling
	song mus_friendly, 0, 0         @ Poké Mart
	song mus_mishiro, 0, 0          @ Littleroot Town
	song mus_tozan, 0, 0            @ Mt. Chimney
	song mus_girleye, 0, 0          @ Trainers' Eyes Meet (Lass)
	song mus_minamo, 0, 0           @ Lilycove City
	song mus_ashroad, 0, 0          @ Route 111
	song mus_event0, 0, 2           @ H-Help Me!
	song mus_deepdeep, 0, 0         @ Dive
	song mus_kachi1, 0, 2           @ Victory! (Trainer Battle)
	song mus_title3, 0, 2           @ Title Screen
	song mus_demo1, 0, 2            @ Opening Movie: Setting out on a Journey in the Hoenn Region
	song mus_girl_sup, 0, 0         @ May
	song mus_hageshii, 0, 0         @ Trainers' Eyes Meet (Psychic)
	song mus_kakkoii, 0, 0          @ Trainers' Eyes Meet (Cooltrainer)
	song mus_kazanbai, 0, 0         @ Route 113
	song mus_aqa_0, 0, 0            @ Team Aqua Appears!
	song mus_tsuretek, 0, 0         @ Hurry Along
	song mus_boy_sup, 0, 0          @ Brendan
	song mus_rainbow, 0, 0          @ Evergrande City
	song mus_ayasii, 0, 0           @ Trainers' Eyes Meet (Hex Maniac)
	song mus_kachi4, 0, 2           @ Victory! (Team Aqua / Team Magma)
	song mus_ropeway, 0, 2          @ Cable Car
	song mus_casino, 0, 0           @ Game Corner
	song mus_hightown, 0, 0         @ Dewford Town
	song mus_safari, 0, 0           @ Safari Zone
	song mus_c_road, 0, 0           @ Victory Road
	song mus_ajito, 0, 0            @ Hideout
	song mus_m_boat, 0, 0           @ Crossing the Sea
	song mus_m_dungon, 0, 0         @ Mt. Pyre
	song mus_finecity, 0, 0         @ Slateport City
	song mus_machupi, 0, 0          @ Mt. Pyre Exterior
	song mus_p_school, 0, 0         @ Trainers' School
	song mus_dendou, 0, 0           @ The Hall of Fame
	song mus_tonekusa, 0, 0         @ Fallarbor Town
	song mus_maborosi, 0, 0         @ Sealed Chamber
	song mus_con_fan, 0, 2          @ Contest Winner
	song mus_contest0, 0, 2         @ Pokémon Contest!
	song mus_mgm0, 0, 0             @ Team Magma Appears!
	song mus_t_battle, 0, 0         @ Opening Movie: Double Battles
	song mus_ooame, 0, 0            @ Heavy Rain
	song mus_hideri, 0, 0           @ The Drought
	song mus_runecity, 0, 0         @ Sootopolis City
	song mus_con_k, 0, 0            @ Results Announcement
	song mus_eikou_r, 0, 0          @ Room of Glory
	song mus_karakuri, 0, 0         @ The Trick House
	song mus_hutago, 0, 0           @ Twins
	song mus_sitennou, 0, 0         @ The Elite Four Appear!
	song mus_yama_eye, 0, 0         @ Trainers' Eyes Meet (Hiker)
	song mus_conlobby, 0, 0         @ Contest Lobby
	song mus_inter_v, 0, 0          @ Interviewers
	song mus_daigo, 0, 0            @ Champion Wallace
	song mus_thankfor, 0, 0         @ Ending Theme
	song mus_end, 0, 0              @ The End
	song mus_b_frontier, 0, 0       @ Battle Frontier
	song mus_b_arena, 0, 0          @ Battle Arena
	song mus_me_pointget, 2, 2      @ Obtained a Battle Point!
	song mus_me_tore_eye, 2, 2      @ Registered Trainer!
	song mus_pyramid, 0, 0          @ Battle Pyramid
	song mus_pyramid_top, 0, 0      @ Battle Pyramid Summit
	song mus_b_palace, 0, 0         @ Battle Palace
	song mus_rekkuu_kourin, 0, 2    @ Rayquaza Enters!
	song mus_sattower, 0, 2         @ Battle Tower
	song mus_me_symbolget, 2, 2     @ Obtained a Frontier Symbol!
	song mus_b_dome, 0, 0           @ Battle Dome
	song mus_b_tube, 0, 0           @ Battle Pike
	song mus_b_factory, 0, 0        @ Battle Factory
	song mus_vs_rekku, 0, 0         @ Battle! (Rayquaza)
	song mus_vs_front, 0, 0         @ Battle! (Frontier Brain)
	song mus_vs_mew, 0, 0           @ Battle! (Mew)
	song mus_b_dome1, 0, 0          @ Battle Dome Lobby
	song mus_battle27, 0, 0         @ Battle! (Wild Pokémon)
	song mus_battle31, 0, 0         @ Battle! (Team Aqua / Team Magma)
	song mus_battle20, 0, 0         @ Battle! (Trainer Battle)
	song mus_battle32, 0, 0         @ Battle! (Gym Leader)
	song mus_battle33, 0, 0         @ Battle! (Champion Wallace)
	song mus_battle36, 0, 0         @ Battle! (Regirock/Regice/Registeel)
	song mus_battle34, 0, 0         @ Battle! (Groudon/Kyogre)
	song mus_battle35, 0, 0         @ Battle! (Brendan/May/Steven)
	song mus_battle38, 0, 0         @ Battle! (Elite Four)
	song mus_battle30, 0, 0         @ Battle! (Team Aqua/Team Magma Leaders)
	song mus_rg_annai, 0, 0         @ Guide (FRLG)
	song mus_rg_slot, 0, 0          @ Rocket Game Corner (FRLG)
	song mus_rg_ajito, 0, 0         @ Rocket Hideout (FRLG)
	song mus_rg_gym, 0, 0           @ Pokémon Gym (FRLG)
	song mus_rg_purin, 2, 2         @ Jigglypuff's Song (FRLG)
	song mus_rg_demo, 0, 2          @ Opening Movie (FRLG)
	song mus_rg_title, 0, 0         @ Title Screen (FRLG)
	song mus_rg_guren, 0, 0         @ Cinnabar Island Theme (FRLG)
	song mus_rg_shion, 0, 0         @ Lavender Town Theme (FRLG)
	song mus_rg_kaihuku, 0, 2       @ Pokémon Healed (FRLG)
	song mus_rg_cycling, 0, 0       @ Cycling (FRLG)
	song mus_rg_rocket, 0, 0        @ A Trainer Appears (Bad Guy Version) (FRLG)
	song mus_rg_shoujo, 0, 0        @ A Trainer Appears (Girl Version) (FRLG)
	song mus_rg_shounen, 0, 0       @ A Trainer Appears (Boy Version) (FRLG)
	song mus_rg_dendou, 0, 0        @ Hall of Fame (FRLG)
	song mus_rg_t_mori, 0, 0        @ Viridian Forest (FRLG)
	song mus_rg_otsukimi, 0, 0      @ Navel Rock
	song mus_rg_pokeyashi, 0, 0     @ Pokémon Mansion (FRLG)
	song mus_rg_ending, 0, 0        @ Ending Theme (FRLG)
	song mus_rg_load01, 0, 0        @ Road to Viridian City: Leaving Pallet Town (FRLG)
	song mus_rg_opening, 0, 0       @ Welcome to the World of Pokémon! (FRLG)
	song mus_rg_load02, 0, 0        @ Road to Cerulean City: Leaving Mt. Moon (FRLG)
	song mus_rg_load03, 0, 0        @ Road to Fuchsia City: Leaving Lavender Town (FRLG)
	song mus_rg_champ_r, 0, 0       @ The Final Road (FRLG)
	song mus_rg_vs_gym, 0, 0        @ Battle! (Gym Leader Battle) (FRLG)
	song mus_rg_vs_tore, 0, 0       @ Battle! (Trainer Battle) (FRLG)
	song mus_rg_vs_yasei, 0, 0      @ Battle! (Wild Pokémon) (FRLG)
	song mus_rg_vs_last, 0, 0       @ Final Battle! (Rival) (FRLG)
	song mus_rg_masara, 0, 0        @ Pallet Town Theme (FRLG)
	song mus_rg_kenkyu, 0, 0        @ Professor Oak's Laboratory (FRLG)
	song mus_rg_ohkido, 0, 0        @ Professor Oak (FRLG)
	song mus_rg_pokecen, 0, 0       @ Pokémon Center (FRLG)
	song mus_rg_santoan, 0, 0       @ The S.S. Anne (FRLG)
	song mus_rg_naminori, 0, 0      @ The Sea (FRLG)
	song mus_rg_p_tower, 0, 0       @ Pokémon Tower (FRLG)
	song mus_rg_shiruhu, 0, 0       @ Silph Co. (FRLG)
	song mus_rg_hanada, 0, 0        @ Fuchsia City Theme (FRLG)
	song mus_rg_tamamusi, 0, 0      @ Celadon City Theme (FRLG)
	song mus_rg_win_tre, 0, 2       @ Victory! (Trainer Battle) (FRLG)
	song mus_rg_win_yasei, 0, 2     @ Victory! (Wild Pokémon) (FRLG)
	song mus_rg_win_gym, 0, 2       @ Victory! (Gym Leader Battle) (FRLG)
	song mus_rg_kuchiba, 0, 0       @ Vermillion City Theme (FRLG)
	song mus_rg_nibi, 0, 0          @ Pewter City Theme (FRLG)
	song mus_rg_rival1, 0, 0        @ A Rival Appears (FRLG)
	song mus_rg_rival2, 0, 0        @ A Rival Appears (No Intro) (FRLG)
	song mus_rg_fan2, 2, 2          @ Fanfare: Professor Oak's Evaluation (FRLG)
	song mus_rg_fan5, 2, 2          @ Fanfare: Pokémon Obtained (FRLG)
	song mus_rg_fan6, 2, 2          @ Fanfare: Pokémon Caught
	song mus_me_rg_photo, 2, 2      @ Pokémon Printer (FRLG)
	song mus_rg_titlerog, 0, 2      @ Game Freak Logo (FRLG)
	song mus_rg_get_yasei, 0, 2     @ Fanfare: Pokémon Caught (No Intro) (FRLG)
	song mus_rg_sousa, 0, 2         @ Game Tutorial (1) (FRLG)
	song mus_rg_sekaikan, 0, 2      @ Game Tutorial (2) (FRLG)
	song mus_rg_seibetu, 0, 2       @ Game Tutorial (3) (FRLG)
	song mus_rg_jump, 0, 0          @ Pokémon Jump (FRLG)
	song mus_rg_union, 0, 0         @ The Union Room (FRLG)
	song mus_rg_network, 0, 0       @ Pokémon Net Center (FRLG)
	song mus_rg_okurimono, 0, 0     @ Mystery Gift (FRLG)
	song mus_rg_kinomikui, 0, 0     @ Dodrio Berry Picking (FRLG)
	song mus_rg_nanadungeon, 0, 0   @ Mt. Ember (FRLG)
	song mus_rg_oshie_tv, 0, 0      @ Teachy TV Lesson (FRLG)
	song mus_rg_nanashima, 0, 0     @ Sevii Islands (FRLG)
	song mus_rg_nanaiseki, 0, 0     @ Tanoby Chambers (FRLG)
	song mus_rg_nana123, 0, 0       @ Sevii Islands: One, Two & Three Islands (FRLG)
	song mus_rg_nana45, 0, 0        @ Sevii Islands: Four & Five Islands (FRLG)
	song mus_rg_nana67, 0, 0        @ Sevii Islands: Six & Seven Islands (FRLG)
	song mus_rg_pokefue, 2, 2       @ The Poké Flute (FRLG)
	song mus_rg_vs_deo, 0, 0        @ Battle! (Deoxys)
	song mus_rg_vs_myu2, 0, 0       @ Battle! (Mewtwo) (FRLG)
	song mus_rg_vs_den, 0, 0        @ Battle! (Ho-Oh/Lugia)
	song mus_rg_exeye, 0, 0         @ Tense Battle! (FRLG)
	song mus_rg_deoeye, 0, 0        @ Deoxys Appears
	song mus_rg_t_tower, 0, 0       @ Trainer Tower (FRLG)
	song mus_rg_slowmasara, 0, 0    @ Epilogue (FRLG)
	song mus_rg_tvnoize, 0, 0       @ Teachy TV Menu (FRLG)
	song ph_trap_blend, 2, 2
	song ph_trap_held, 2, 2
	song ph_trap_solo, 2, 2
	song ph_face_blend, 2, 2
	song ph_face_held, 2, 2
	song ph_face_solo, 2, 2
	song ph_cloth_blend, 2, 2
	song ph_cloth_held, 2, 2
	song ph_cloth_solo, 2, 2
	song ph_dress_blend, 2, 2
	song ph_dress_held, 2, 2
	song ph_dress_solo, 2, 2
	song ph_fleece_blend, 2, 2
	song ph_fleece_held, 2, 2
	song ph_fleece_solo, 2, 2
	song ph_kit_blend, 2, 2
	song ph_kit_held, 2, 2
	song ph_kit_solo, 2, 2
	song ph_price_blend, 2, 2
	song ph_price_held, 2, 2
	song ph_price_solo, 2, 2
	song ph_lot_blend, 2, 2
	song ph_lot_held, 2, 2
	song ph_lot_solo, 2, 2
	song ph_goat_blend, 2, 2
	song ph_goat_held, 2, 2
	song ph_goat_solo, 2, 2
	song ph_thought_blend, 2, 2
	song ph_thought_held, 2, 2
	song ph_thought_solo, 2, 2
	song ph_choice_blend, 2, 2
	song ph_choice_held, 2, 2
	song ph_choice_solo, 2, 2
	song ph_mouth_blend, 2, 2
	song ph_mouth_held, 2, 2
	song ph_mouth_solo, 2, 2
	song ph_foot_blend, 2, 2
	song ph_foot_held, 2, 2
	song ph_foot_solo, 2, 2
	song ph_goose_blend, 2, 2
	song ph_goose_held, 2, 2
	song ph_goose_solo, 2, 2
	song ph_strut_blend, 2, 2
	song ph_strut_held, 2, 2
	song ph_strut_solo, 2, 2
	song ph_cure_blend, 2, 2
	song ph_cure_held, 2, 2
	song ph_cure_solo, 2, 2
	song ph_nurse_blend, 2, 2
	song ph_nurse_held, 2, 2
	song ph_nurse_solo, 2, 2

	.align 2
dummy_song_header: @ 86B5D00
	.byte 0, 0, 0, 0
