#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MON_IVYSAUR                               0
#define FRONTIER_MON_PIKACHU                               1
#define FRONTIER_MON_CLEFAIRY                              2
#define FRONTIER_MON_GOLBAT                                3
#define FRONTIER_MON_GLOOM                                 4
#define FRONTIER_MON_KADABRA                               5
#define FRONTIER_MON_MACHOKE                               6
#define FRONTIER_MON_WEEPINBELL                            7
#define FRONTIER_MON_MAGNETON                              8
#define FRONTIER_MON_HAUNTER                               9
#define FRONTIER_MON_TANGELA                               10
#define FRONTIER_MON_ELECTABUZZ                            11
#define FRONTIER_MON_MAGMAR                                12
#define FRONTIER_MON_BAYLEEF                               13
#define FRONTIER_MON_QUILAVA                               14
#define FRONTIER_MON_CROCONAW                              15
#define FRONTIER_MON_TOGETIC                               16
#define FRONTIER_MON_MARILL                                17
#define FRONTIER_MON_MURKROW                               18
#define FRONTIER_MON_SNEASEL                               19
#define FRONTIER_MON_PILOSWINE                             20
#define FRONTIER_MON_COMBUSKEN                             21
#define FRONTIER_MON_MARSHTOMP                             22
#define FRONTIER_MON_WINGULL                               23
#define FRONTIER_MON_VIBRAVA                               24
#define FRONTIER_MON_SEALEO                                25
#define FRONTIER_MON_DUSCLOPS                              26
#define FRONTIER_MON_ROSELIA                               27
#define FRONTIER_MON_LAIRON                                28
#define FRONTIER_MON_LILEEP                                29
#define FRONTIER_MON_ANORITH                               30
#define FRONTIER_MON_SHELGON                               31
#define FRONTIER_MON_METANG                                32
#define FRONTIER_MON_MONFERNO                              33
#define FRONTIER_MON_PRINPLUP                              34
#define FRONTIER_MON_STARAVIA                              35
#define FRONTIER_MON_LUXIO                                 36
#define FRONTIER_MON_CRANIDOS                              37
#define FRONTIER_MON_SHIELDON                              38
#define FRONTIER_MON_GABITE                                39
#define FRONTIER_MON_MUNCHLAX                              40
#define FRONTIER_MON_RIOLU                                 41
#define FRONTIER_MON_HIPPOPOTAS                            42
#define FRONTIER_MON_SERVINE                               43
#define FRONTIER_MON_GURDURR                               44
#define FRONTIER_MON_PALPITOAD                             45
#define FRONTIER_MON_WHIRLIPEDE                            46
#define FRONTIER_MON_KROKOROK                              47
#define FRONTIER_MON_ARCHEN                                48
#define FRONTIER_MON_DUOSION                               49
#define FRONTIER_MON_FERROSEED                             50
#define FRONTIER_MON_EELEKTRIK                             51
#define FRONTIER_MON_LAMPENT                               52
#define FRONTIER_MON_FRAXURE                               53
#define FRONTIER_MON_MIENFOO                               54
#define FRONTIER_MON_PAWNIARD                              55
#define FRONTIER_MON_RUFFLET                               56
#define FRONTIER_MON_ZWEILOUS                              57
#define FRONTIER_MON_QUILLADIN                             58
#define FRONTIER_MON_FROGADIER                             59
#define FRONTIER_MON_FLETCHINDER                           60
#define FRONTIER_MON_TYRUNT                                61
#define FRONTIER_MON_SLIGGOO                               62
#define FRONTIER_MON_PUMPKABOO                             63
#define FRONTIER_MON_DARTRIX                               64
#define FRONTIER_MON_TORRACAT                              65
#define FRONTIER_MON_TRUMBEAK                              66
#define FRONTIER_MON_CRABRAWLER                            67
#define FRONTIER_MON_MAREANIE                              68
#define FRONTIER_MON_MUDBRAY                               69
#define FRONTIER_MON_DEWPIDER                              70
#define FRONTIER_MON_HAKAMO_O                              71

#define FRONTIER_MON_DUNSPARCE                             72
#define FRONTIER_MON_CORSOLA                               73
#define FRONTIER_MON_DELIBIRD                              74
#define FRONTIER_MON_SPINDA                                75
#define FRONTIER_MON_LUVDISC                               76
#define FRONTIER_MON_FARFETCHD                             77
#define FRONTIER_MON_SMEARGLE                              78
#define FRONTIER_MON_DITTO                                 79
#define FRONTIER_MON_UNOWN                                 80

#define FRONTIER_MON_BUTTERFREE_1                          81
#define FRONTIER_MON_BUTTERFREE_2                          82
#define FRONTIER_MON_BEEDRILL_1                            83
#define FRONTIER_MON_BEEDRILL_2                            84
#define FRONTIER_MON_LEDIAN_1                              85
#define FRONTIER_MON_LEDIAN_2                              86
#define FRONTIER_MON_ARIADOS_1                             87
#define FRONTIER_MON_ARIADOS_2                             88
#define FRONTIER_MON_BEAUTIFLY_1                           89
#define FRONTIER_MON_BEAUTIFLY_2                           90
#define FRONTIER_MON_DUSTOX_1                              91
#define FRONTIER_MON_DUSTOX_2                              92
#define FRONTIER_MON_NINJASK_1                             93
#define FRONTIER_MON_NINJASK_2                             94
#define FRONTIER_MON_SHEDINJA_1                            95
#define FRONTIER_MON_SHEDINJA_2                            96

#define FRONTIER_MON_MAWILE_1                              97
#define FRONTIER_MON_YANMEGA_1                             98
#define FRONTIER_MON_PROBOPASS_1                           99
#define FRONTIER_MON_DELCATTY_1                            100
#define FRONTIER_MON_SABLEYE_1                             101
#define FRONTIER_MON_LICKILICKY_1                          102
#define FRONTIER_MON_CHERRIM_1                             103
#define FRONTIER_MON_AUDINO_1                              104
#define FRONTIER_MON_DARMANITAN_ZEN_1                      105
#define FRONTIER_MON_WHIMSICOTT_1                          106
#define FRONTIER_MON_VOLBEAT_1                             107
#define FRONTIER_MON_ILLUMISE_1                            108
#define FRONTIER_MON_MARACTUS_1                            109
#define FRONTIER_MON_PARASECT_1                            110
#define FRONTIER_MON_GOGOAT_1                              111
#define FRONTIER_MON_WOBBUFFET_1                           112
#define FRONTIER_MON_PLUSLE_1                              113
#define FRONTIER_MON_MINUN_1                               114
#define FRONTIER_MON_LURANTIS_1                            115
#define FRONTIER_MON_AZUMARILL_1                           116
#define FRONTIER_MON_SUDOWOODO_1                           117
#define FRONTIER_MON_MAGCARGO_1                            118
#define FRONTIER_MON_RATICATE_1                            119
#define FRONTIER_MON_MASQUERAIN_1                          120
#define FRONTIER_MON_FURRET_1                              121
#define FRONTIER_MON_MIGHTYENA_1                           122
#define FRONTIER_MON_LINOONE_1                             123
#define FRONTIER_MON_CASTFORM_1                            124
#define FRONTIER_MON_WIGGLYTUFF_1                          125
#define FRONTIER_MON_SUNFLORA_1                            126
#define FRONTIER_MON_QWILFISH_1                            127
#define FRONTIER_MON_PELIPPER_1                            128
#define FRONTIER_MON_SWELLOW_1                             129
#define FRONTIER_MON_LILLIGANT_1                           130
#define FRONTIER_MON_ARBOK_1                               131
#define FRONTIER_MON_PERSIAN_1                             132
#define FRONTIER_MON_KECLEON_1                             133
#define FRONTIER_MON_SCRAFTY_1                             134
#define FRONTIER_MON_LUNATONE_1                            135
#define FRONTIER_MON_SOLROCK_1                             136
#define FRONTIER_MON_NOCTOWL_1                             137
#define FRONTIER_MON_SANDSLASH_1                           138
#define FRONTIER_MON_VENOMOTH_1                            139
#define FRONTIER_MON_BLISSEY_1                             140
#define FRONTIER_MON_SEAKING_1                             141
#define FRONTIER_MON_JUMPLUFF_1                            142
#define FRONTIER_MON_BASTIODON_1                           143
#define FRONTIER_MON_LIEPARD_1                             144
#define FRONTIER_MON_PRIMEAPE_1                            145
#define FRONTIER_MON_HITMONLEE_1                           146
#define FRONTIER_MON_HITMONCHAN_1                          147
#define FRONTIER_MON_GIRAFARIG_1                           148
#define FRONTIER_MON_HITMONTOP_1                           149
#define FRONTIER_MON_BANETTE_1                             150
#define FRONTIER_MON_SEVIPER_1                             151
#define FRONTIER_MON_ZANGOOSE_1                            152
#define FRONTIER_MON_CAMERUPT_1                            153
#define FRONTIER_MON_SHARPEDO_1                            154
#define FRONTIER_MON_TROPIUS_1                             155
#define FRONTIER_MON_MAGNEZONE_1                           156
#define FRONTIER_MON_MANTINE_1                             157
#define FRONTIER_MON_STANTLER_1                            158
#define FRONTIER_MON_ABSOL_1                               159
#define FRONTIER_MON_SWALOT_1                              160
#define FRONTIER_MON_CRAWDAUNT_1                           161
#define FRONTIER_MON_PIDGEOT_1                             162
#define FRONTIER_MON_GRUMPIG_1                             163
#define FRONTIER_MON_TORKOAL_1                             164
#define FRONTIER_MON_KINGLER_1                             165
#define FRONTIER_MON_CACTURNE_1                            166
#define FRONTIER_MON_BELLOSSOM_1                           167
#define FRONTIER_MON_OCTILLERY_1                           168
#define FRONTIER_MON_HUNTAIL_1                             169
#define FRONTIER_MON_GOREBYSS_1                            170
#define FRONTIER_MON_RELICANTH_1                           171
#define FRONTIER_MON_OMASTAR_1                             172
#define FRONTIER_MON_KABUTOPS_1                            173
#define FRONTIER_MON_POLIWRATH_1                           174
#define FRONTIER_MON_SCYTHER_1                             175
#define FRONTIER_MON_PINSIR_1                              176
#define FRONTIER_MON_POLITOED_1                            177
#define FRONTIER_MON_CLOYSTER_1                            178
#define FRONTIER_MON_ABOMASNOW_1                           179
#define FRONTIER_MON_AVALUGG_1                             180
#define FRONTIER_MON_BEARTIC_1                             181
#define FRONTIER_MON_CARBINK_1                             182
#define FRONTIER_MON_CARRACOSTA_1                          183
#define FRONTIER_MON_CRUSTLE_1                             184
#define FRONTIER_MON_CRYOGONAL_1                           185
#define FRONTIER_MON_CRABOMINABLE_1                        186
#define FRONTIER_MON_LUMINEON_1                            187
#define FRONTIER_MON_SAWSBUCK_1                            188
#define FRONTIER_MON_BASCULIN_1                            189
#define FRONTIER_MON_CARNIVINE_1                           190
#define FRONTIER_MON_STUNFISK_1                            191
#define FRONTIER_MON_PHIONE_1                              192
#define FRONTIER_MON_GLIGAR_1                              193
#define FRONTIER_MON_VIGOROTH_1                            194

#define FRONTIER_MON_MAWILE_2                              195
#define FRONTIER_MON_YANMEGA_2                             196
#define FRONTIER_MON_PROBOPASS_2                           197
#define FRONTIER_MON_DELCATTY_2                            198
#define FRONTIER_MON_SABLEYE_2                             199
#define FRONTIER_MON_LICKILICKY_2                          200
#define FRONTIER_MON_CHERRIM_2                             201
#define FRONTIER_MON_AUDINO_2                              202
#define FRONTIER_MON_DARMANITAN_ZEN_2                      203
#define FRONTIER_MON_WHIMSICOTT_2                          204
#define FRONTIER_MON_VOLBEAT_2                             205
#define FRONTIER_MON_ILLUMISE_2                            206
#define FRONTIER_MON_MARACTUS_2                            207
#define FRONTIER_MON_PARASECT_2                            208
#define FRONTIER_MON_GOGOAT_2                              209
#define FRONTIER_MON_WOBBUFFET_2                           210
#define FRONTIER_MON_PLUSLE_2                              211
#define FRONTIER_MON_MINUN_2                               212
#define FRONTIER_MON_LURANTIS_2                            213
#define FRONTIER_MON_AZUMARILL_2                           214
#define FRONTIER_MON_SUDOWOODO_2                           215
#define FRONTIER_MON_MAGCARGO_2                            216
#define FRONTIER_MON_RATICATE_2                            217
#define FRONTIER_MON_MASQUERAIN_2                          218
#define FRONTIER_MON_FURRET_2                              219
#define FRONTIER_MON_MIGHTYENA_2                           220
#define FRONTIER_MON_LINOONE_2                             221
#define FRONTIER_MON_CASTFORM_2                            222
#define FRONTIER_MON_WIGGLYTUFF_2                          223
#define FRONTIER_MON_SUNFLORA_2                            224
#define FRONTIER_MON_QWILFISH_2                            225
#define FRONTIER_MON_PELIPPER_2                            226
#define FRONTIER_MON_SWELLOW_2                             227
#define FRONTIER_MON_LILLIGANT_2                           228
#define FRONTIER_MON_ARBOK_2                               229
#define FRONTIER_MON_PERSIAN_2                             230
#define FRONTIER_MON_KECLEON_2                             231
#define FRONTIER_MON_SCRAFTY_2                             232
#define FRONTIER_MON_LUNATONE_2                            233
#define FRONTIER_MON_SOLROCK_2                             234
#define FRONTIER_MON_NOCTOWL_2                             235
#define FRONTIER_MON_SANDSLASH_2                           236
#define FRONTIER_MON_VENOMOTH_2                            237
#define FRONTIER_MON_BLISSEY_2                             238
#define FRONTIER_MON_SEAKING_2                             239
#define FRONTIER_MON_JUMPLUFF_2                            240
#define FRONTIER_MON_BASTIODON_2                           241
#define FRONTIER_MON_LIEPARD_2                             242
#define FRONTIER_MON_PRIMEAPE_2                            243
#define FRONTIER_MON_HITMONLEE_2                           244
#define FRONTIER_MON_HITMONCHAN_2                          245
#define FRONTIER_MON_GIRAFARIG_2                           246
#define FRONTIER_MON_HITMONTOP_2                           247
#define FRONTIER_MON_BANETTE_2                             248
#define FRONTIER_MON_SEVIPER_2                             249
#define FRONTIER_MON_ZANGOOSE_2                            250
#define FRONTIER_MON_CAMERUPT_2                            251
#define FRONTIER_MON_SHARPEDO_2                            252
#define FRONTIER_MON_TROPIUS_2                             253
#define FRONTIER_MON_MAGNEZONE_2                           254
#define FRONTIER_MON_MANTINE_2                             255
#define FRONTIER_MON_STANTLER_2                            256
#define FRONTIER_MON_ABSOL_2                               257
#define FRONTIER_MON_SWALOT_2                              258
#define FRONTIER_MON_CRAWDAUNT_2                           259
#define FRONTIER_MON_PIDGEOT_2                             260
#define FRONTIER_MON_GRUMPIG_2                             261
#define FRONTIER_MON_TORKOAL_2                             262
#define FRONTIER_MON_KINGLER_2                             263
#define FRONTIER_MON_CACTURNE_2                            264
#define FRONTIER_MON_BELLOSSOM_2                           265
#define FRONTIER_MON_OCTILLERY_2                           266
#define FRONTIER_MON_HUNTAIL_2                             267
#define FRONTIER_MON_GOREBYSS_2                            268
#define FRONTIER_MON_RELICANTH_2                           269
#define FRONTIER_MON_OMASTAR_2                             270
#define FRONTIER_MON_KABUTOPS_2                            271
#define FRONTIER_MON_POLIWRATH_2                           272
#define FRONTIER_MON_SCYTHER_2                             273
#define FRONTIER_MON_PINSIR_2                              274
#define FRONTIER_MON_POLITOED_2                            275
#define FRONTIER_MON_CLOYSTER_2                            276
#define FRONTIER_MON_ABOMASNOW_2                           277
#define FRONTIER_MON_AVALUGG_2                             278
#define FRONTIER_MON_BEARTIC_2                             279
#define FRONTIER_MON_CARBINK_2                             280
#define FRONTIER_MON_CARRACOSTA_2                          281
#define FRONTIER_MON_CRUSTLE_2                             282
#define FRONTIER_MON_CRYOGONAL_2                           283
#define FRONTIER_MON_CRABOMINABLE_2                        284
#define FRONTIER_MON_LUMINEON_2                            285
#define FRONTIER_MON_SAWSBUCK_2                            286
#define FRONTIER_MON_BASCULIN_2                            287
#define FRONTIER_MON_CARNIVINE_2                           288
#define FRONTIER_MON_STUNFISK_2                            289
#define FRONTIER_MON_PHIONE_2                              290
#define FRONTIER_MON_GLIGAR_2                              291
#define FRONTIER_MON_VIGOROTH_2                            292

#define FRONTIER_MON_BARBARACLE_1                          293
#define FRONTIER_MON_COFAGRIGUS_1                          294
#define FRONTIER_MON_PASSIMIAN_1                           295
#define FRONTIER_MON_ORANGURU_1                            296
#define FRONTIER_MON_MISDREAVUS_1                          297
#define FRONTIER_MON_DOUBLADE_1                            298
#define FRONTIER_MON_DUGTRIO_1                             299
#define FRONTIER_MON_HAWLUCHA_1                            300
#define FRONTIER_MON_MISMAGIUS_1                           301
#define FRONTIER_MON_TALONFLAME_1                          302
#define FRONTIER_MON_GRANBULL_1                            303
#define FRONTIER_MON_FROSLASS_1                            304
#define FRONTIER_MON_DUSKNOIR_1                            305
#define FRONTIER_MON_TOUCANNON_1                           306
#define FRONTIER_MON_MR_MIME_1                             307
#define FRONTIER_MON_ROTOM_FAN_1                           308
#define FRONTIER_MON_BRELOOM_1                             309
#define FRONTIER_MON_VIKAVOLT_1                            310
#define FRONTIER_MON_WHISCASH_1                            311
#define FRONTIER_MON_HONCHKROW_1                           312
#define FRONTIER_MON_SKARMORY_1                            313
#define FRONTIER_MON_RAMPARDOS_1                           314
#define FRONTIER_MON_QUAGSIRE_1                            315
#define FRONTIER_MON_AURORUS_1                             316
#define FRONTIER_MON_HARIYAMA_1                            317
#define FRONTIER_MON_EMOLGA_1                              318
#define FRONTIER_MON_DEWGONG_1                             319
#define FRONTIER_MON_ZEBSTRIKA_1                           320
#define FRONTIER_MON_VILEPLUME_1                           321
#define FRONTIER_MON_ROSERADE_1                            322
#define FRONTIER_MON_ELECTRODE_1                           323
#define FRONTIER_MON_ZOROARK_1                             324
#define FRONTIER_MON_SHIFTRY_1                             325
#define FRONTIER_MON_GLACEON_1                             326
#define FRONTIER_MON_LUDICOLO_1                            327
#define FRONTIER_MON_SPIRITOMB_1                           328
#define FRONTIER_MON_GOLEM_1                               329
#define FRONTIER_MON_LYCANROC_1                            330
#define FRONTIER_MON_ALAKAZAM_1                            331
#define FRONTIER_MON_DRAPION_1                             332
#define FRONTIER_MON_KANGASKHAN_1                          333
#define FRONTIER_MON_EELEKTROSS_1                          334
#define FRONTIER_MON_TAUROS_1                              335
#define FRONTIER_MON_REUNICLUS_1                           336
#define FRONTIER_MON_SLOWKING_1                            337
#define FRONTIER_MON_PORYGON_Z_1                           338
#define FRONTIER_MON_ALTARIA_1                             339
#define FRONTIER_MON_HIPPOWDON_1                           340
#define FRONTIER_MON_NIDOKING_1                            341
#define FRONTIER_MON_GOLURK_1                              342
#define FRONTIER_MON_CRADILY_1                             343
#define FRONTIER_MON_GOLISOPOD_1                           344
#define FRONTIER_MON_GOLDUCK_1                             345
#define FRONTIER_MON_AMBIPOM_1                             346
#define FRONTIER_MON_MUK_1                                 347
#define FRONTIER_MON_CHANDELURE_1                          348
#define FRONTIER_MON_AMPHAROS_1                            349
#define FRONTIER_MON_DURANT_1                              350
#define FRONTIER_MON_HERACROSS_1                           351
#define FRONTIER_MON_LUCARIO_1                             352
#define FRONTIER_MON_HOUNDOOM_1                            353
#define FRONTIER_MON_MUDSDALE_1                            354
#define FRONTIER_MON_CLAYDOL_1                             355
#define FRONTIER_MON_PYUKUMUKU_1                           356
#define FRONTIER_MON_NINETALES_1                           357
#define FRONTIER_MON_CONKELDURR_1                          358
#define FRONTIER_MON_SHUCKLE_1                             359
#define FRONTIER_MON_EXCADRILL_1                           360
#define FRONTIER_MON_TENTACRUEL_1                          361
#define FRONTIER_MON_ARCHEOPS_1                            362
#define FRONTIER_MON_PORYGON2_1                            363
#define FRONTIER_MON_SERPERIOR_1                           364
#define FRONTIER_MON_EXEGGUTOR_1                           365
#define FRONTIER_MON_BLAZIKEN_1                            366
#define FRONTIER_MON_FLYGON_1                              367
#define FRONTIER_MON_TORTERRA_1                            368
#define FRONTIER_MON_VAPOREON_1                            369
#define FRONTIER_MON_LUXRAY_1                              370
#define FRONTIER_MON_FLAREON_1                             371
#define FRONTIER_MON_CHESNAUGHT_1                          372
#define FRONTIER_MON_URSARING_1                            373
#define FRONTIER_MON_BISHARP_1                             374
#define FRONTIER_MON_BLASTOISE_1                           375
#define FRONTIER_MON_SAMUROTT_1                            376
#define FRONTIER_MON_AGGRON_1                              377
#define FRONTIER_MON_DELPHOX_1                             378
#define FRONTIER_MON_WALREIN_1                             379
#define FRONTIER_MON_DECIDUEYE_1                           380
#define FRONTIER_MON_CHARIZARD_1                           381
#define FRONTIER_MON_EMBOAR_1                              382
#define FRONTIER_MON_LAPRAS_1                              383
#define FRONTIER_MON_SALAZZLE_1                            384
#define FRONTIER_MON_SWAMPERT_1                            385
#define FRONTIER_MON_DRAGALGE_1                            386
#define FRONTIER_MON_SNORLAX_1                             387
#define FRONTIER_MON_ARAQUANID_1                           388
#define FRONTIER_MON_CHANSEY_1                             389
#define FRONTIER_MON_ROTOM_WASH_1                          390
#define FRONTIER_MON_ARCANINE_1                            391
#define FRONTIER_MON_GARCHOMP_1                            392
#define FRONTIER_MON_METAGROSS_1                           393
#define FRONTIER_MON_REGIGIGAS_1                           394

#define FRONTIER_MON_BRAVIARY_1                            395
#define FRONTIER_MON_DIGGERSBY_1                           396
#define FRONTIER_MON_DRIFBLIM_1                            397
#define FRONTIER_MON_GOURGEIST_1                           398
#define FRONTIER_MON_TYPE_NULL_1                           399
#define FRONTIER_MON_RHYDON_1                              400
#define FRONTIER_MON_GLISCOR_1                             401
#define FRONTIER_MON_MEDICHAM_1                            402
#define FRONTIER_MON_WEAVILE_1                             403
#define FRONTIER_MON_FEAROW_1                              404
#define FRONTIER_MON_SCOLIPEDE_1                           405
#define FRONTIER_MON_JYNX_1                                406
#define FRONTIER_MON_AEGISLASH_1                           407
#define FRONTIER_MON_DODRIO_1                              408
#define FRONTIER_MON_MIMIKYU_1                             409
#define FRONTIER_MON_LANTURN_1                             410
#define FRONTIER_MON_PANGORO_1                             411
#define FRONTIER_MON_FORRETRESS_1                          412
#define FRONTIER_MON_MAMOSWINE_1                           413
#define FRONTIER_MON_XATU_1                                414
#define FRONTIER_MON_STARAPTOR_1                           415
#define FRONTIER_MON_MAROWAK_1                             416
#define FRONTIER_MON_GASTRODON_1                           417
#define FRONTIER_MON_CLEFABLE_1                            418
#define FRONTIER_MON_MIENSHAO_1                            419
#define FRONTIER_MON_RAICHU_1                              420
#define FRONTIER_MON_ROTOM_FROST_1                         421
#define FRONTIER_MON_MANECTRIC_1                           422
#define FRONTIER_MON_TANGROWTH_1                           423
#define FRONTIER_MON_VICTREEBEL_1                          424
#define FRONTIER_MON_ROTOM_MOW_1                           425
#define FRONTIER_MON_EXPLOUD_1                             426
#define FRONTIER_MON_TREVENANT_1                           427
#define FRONTIER_MON_GLALIE_1                              428
#define FRONTIER_MON_LEAFEON_1                             429
#define FRONTIER_MON_HYPNO_1                               430
#define FRONTIER_MON_GIGALITH_1                            431
#define FRONTIER_MON_RHYPERIOR_1                           432
#define FRONTIER_MON_GALLADE_1                             433
#define FRONTIER_MON_WEEZING_1                             434
#define FRONTIER_MON_BEWEAR_1                              435
#define FRONTIER_MON_ELECTIVIRE_1                          436
#define FRONTIER_MON_LOPUNNY_1                             437
#define FRONTIER_MON_SLOWBRO_1                             438
#define FRONTIER_MON_BEHEEYEM_1                            439
#define FRONTIER_MON_MILTANK_1                             440
#define FRONTIER_MON_NOIVERN_1                             441
#define FRONTIER_MON_NIDOQUEEN_1                           442
#define FRONTIER_MON_KROOKODILE_1                          443
#define FRONTIER_MON_MAGMORTAR_1                           444
#define FRONTIER_MON_FERROTHORN_1                          445
#define FRONTIER_MON_ARMALDO_1                             446
#define FRONTIER_MON_CLAWITZER_1                           447
#define FRONTIER_MON_RAPIDASH_1                            448
#define FRONTIER_MON_TOXICROAK_1                           449
#define FRONTIER_MON_GENGAR_1                              450
#define FRONTIER_MON_TOGEDEMARU_1                          451
#define FRONTIER_MON_SCIZOR_1                              452
#define FRONTIER_MON_GALVANTULA_1                          453
#define FRONTIER_MON_ESPEON_1                              454
#define FRONTIER_MON_LYCANROC_MIDNIGHT_1                   455
#define FRONTIER_MON_DONPHAN_1                             456
#define FRONTIER_MON_PALOSSAND_1                           457
#define FRONTIER_MON_WAILORD_1                             458
#define FRONTIER_MON_TURTONATOR_1                          459
#define FRONTIER_MON_MACHAMP_1                             460
#define FRONTIER_MON_LYCANROC_DUSK_1                       461
#define FRONTIER_MON_STEELIX_1                             462
#define FRONTIER_MON_JELLICENT_1                           463
#define FRONTIER_MON_AERODACTYL_1                          464
#define FRONTIER_MON_CINCCINO_1                            465
#define FRONTIER_MON_GARDEVOIR_1                           466
#define FRONTIER_MON_TSAREENA_1                            467
#define FRONTIER_MON_STARMIE_1                             468
#define FRONTIER_MON_HAXORUS_1                             469
#define FRONTIER_MON_VENUSAUR_1                            470
#define FRONTIER_MON_SEISMITOAD_1                          471
#define FRONTIER_MON_JOLTEON_1                             472
#define FRONTIER_MON_DARMANITAN_1                          473
#define FRONTIER_MON_MEGANIUM_1                            474
#define FRONTIER_MON_SYLVEON_1                             475
#define FRONTIER_MON_UMBREON_1                             476
#define FRONTIER_MON_EMPOLEON_1                            477
#define FRONTIER_MON_FERALIGATR_1                          478
#define FRONTIER_MON_TYRANTRUM_1                           479
#define FRONTIER_MON_INCINEROAR_1                          480
#define FRONTIER_MON_VANILLUXE_1                           481
#define FRONTIER_MON_SCEPTILE_1                            482
#define FRONTIER_MON_INFERNAPE_1                           483
#define FRONTIER_MON_TYPHLOSION_1                          484
#define FRONTIER_MON_GRENINJA_1                            485
#define FRONTIER_MON_CROBAT_1                              486
#define FRONTIER_MON_PRIMARINA_1                           487
#define FRONTIER_MON_GYARADOS_1                            488
#define FRONTIER_MON_TOGEKISS_1                            489
#define FRONTIER_MON_KINGDRA_1                             490
#define FRONTIER_MON_TOXAPEX_1                             491
#define FRONTIER_MON_MILOTIC_1                             492
#define FRONTIER_MON_ROTOM_HEAT_1                          493
#define FRONTIER_MON_SALAMENCE_1                           494
#define FRONTIER_MON_KOMMO_O_1                             495
#define FRONTIER_MON_SLAKING_1                             496

#define FRONTIER_MON_BARBARACLE_2                          497
#define FRONTIER_MON_COFAGRIGUS_2                          498
#define FRONTIER_MON_PASSIMIAN_2                           499
#define FRONTIER_MON_ORANGURU_2                            500
#define FRONTIER_MON_MISDREAVUS_2                          501
#define FRONTIER_MON_DOUBLADE_2                            502
#define FRONTIER_MON_DUGTRIO_2                             503
#define FRONTIER_MON_HAWLUCHA_2                            504
#define FRONTIER_MON_MISMAGIUS_2                           505
#define FRONTIER_MON_TALONFLAME_2                          506
#define FRONTIER_MON_GRANBULL_2                            507
#define FRONTIER_MON_FROSLASS_2                            508
#define FRONTIER_MON_DUSKNOIR_2                            509
#define FRONTIER_MON_TOUCANNON_2                           510
#define FRONTIER_MON_MR_MIME_2                             511
#define FRONTIER_MON_ROTOM_FAN_2                           512
#define FRONTIER_MON_BRELOOM_2                             513
#define FRONTIER_MON_VIKAVOLT_2                            514
#define FRONTIER_MON_WHISCASH_2                            515
#define FRONTIER_MON_HONCHKROW_2                           516
#define FRONTIER_MON_SKARMORY_2                            517
#define FRONTIER_MON_RAMPARDOS_2                           518
#define FRONTIER_MON_QUAGSIRE_2                            519
#define FRONTIER_MON_AURORUS_2                             520
#define FRONTIER_MON_HARIYAMA_2                            521
#define FRONTIER_MON_EMOLGA_2                              522
#define FRONTIER_MON_DEWGONG_2                             523
#define FRONTIER_MON_ZEBSTRIKA_2                           524
#define FRONTIER_MON_VILEPLUME_2                           525
#define FRONTIER_MON_ROSERADE_2                            526
#define FRONTIER_MON_ELECTRODE_2                           527
#define FRONTIER_MON_ZOROARK_2                             528
#define FRONTIER_MON_SHIFTRY_2                             529
#define FRONTIER_MON_GLACEON_2                             530
#define FRONTIER_MON_LUDICOLO_2                            531
#define FRONTIER_MON_SPIRITOMB_2                           532
#define FRONTIER_MON_GOLEM_2                               533
#define FRONTIER_MON_LYCANROC_2                            534
#define FRONTIER_MON_ALAKAZAM_2                            535
#define FRONTIER_MON_DRAPION_2                             536
#define FRONTIER_MON_KANGASKHAN_2                          537
#define FRONTIER_MON_EELEKTROSS_2                          538
#define FRONTIER_MON_TAUROS_2                              539
#define FRONTIER_MON_REUNICLUS_2                           540
#define FRONTIER_MON_SLOWKING_2                            541
#define FRONTIER_MON_PORYGON_Z_2                           542
#define FRONTIER_MON_ALTARIA_2                             543
#define FRONTIER_MON_HIPPOWDON_2                           544
#define FRONTIER_MON_NIDOKING_2                            545
#define FRONTIER_MON_GOLURK_2                              546
#define FRONTIER_MON_CRADILY_2                             547
#define FRONTIER_MON_GOLISOPOD_2                           548
#define FRONTIER_MON_GOLDUCK_2                             549
#define FRONTIER_MON_AMBIPOM_2                             550
#define FRONTIER_MON_MUK_2                                 551
#define FRONTIER_MON_CHANDELURE_2                          552
#define FRONTIER_MON_AMPHAROS_2                            553
#define FRONTIER_MON_DURANT_2                              554
#define FRONTIER_MON_HERACROSS_2                           555
#define FRONTIER_MON_LUCARIO_2                             556
#define FRONTIER_MON_HOUNDOOM_2                            557
#define FRONTIER_MON_MUDSDALE_2                            558
#define FRONTIER_MON_CLAYDOL_2                             559
#define FRONTIER_MON_PYUKUMUKU_2                           560
#define FRONTIER_MON_NINETALES_2                           561
#define FRONTIER_MON_CONKELDURR_2                          562
#define FRONTIER_MON_SHUCKLE_2                             563
#define FRONTIER_MON_EXCADRILL_2                           564
#define FRONTIER_MON_TENTACRUEL_2                          565
#define FRONTIER_MON_ARCHEOPS_2                            566
#define FRONTIER_MON_PORYGON2_2                            567
#define FRONTIER_MON_SERPERIOR_2                           568
#define FRONTIER_MON_EXEGGUTOR_2                           569
#define FRONTIER_MON_BLAZIKEN_2                            570
#define FRONTIER_MON_FLYGON_2                              571
#define FRONTIER_MON_TORTERRA_2                            572
#define FRONTIER_MON_VAPOREON_2                            573
#define FRONTIER_MON_LUXRAY_2                              574
#define FRONTIER_MON_FLAREON_2                             575
#define FRONTIER_MON_CHESNAUGHT_2                          576
#define FRONTIER_MON_URSARING_2                            577
#define FRONTIER_MON_BISHARP_2                             578
#define FRONTIER_MON_BLASTOISE_2                           579
#define FRONTIER_MON_SAMUROTT_2                            580
#define FRONTIER_MON_AGGRON_2                              581
#define FRONTIER_MON_DELPHOX_2                             582
#define FRONTIER_MON_WALREIN_2                             583
#define FRONTIER_MON_DECIDUEYE_2                           584
#define FRONTIER_MON_CHARIZARD_2                           585
#define FRONTIER_MON_EMBOAR_2                              586
#define FRONTIER_MON_LAPRAS_2                              587
#define FRONTIER_MON_SALAZZLE_2                            588
#define FRONTIER_MON_SWAMPERT_2                            589
#define FRONTIER_MON_DRAGALGE_2                            590
#define FRONTIER_MON_SNORLAX_2                             591
#define FRONTIER_MON_ARAQUANID_2                           592
#define FRONTIER_MON_CHANSEY_2                             593
#define FRONTIER_MON_ROTOM_WASH_2                          594
#define FRONTIER_MON_ARCANINE_2                            595
#define FRONTIER_MON_GARCHOMP_2                            596
#define FRONTIER_MON_METAGROSS_2                           597
#define FRONTIER_MON_REGIGIGAS_2                           598

#define FRONTIER_MON_BRAVIARY_2                            599
#define FRONTIER_MON_DIGGERSBY_2                           600
#define FRONTIER_MON_DRIFBLIM_2                            601
#define FRONTIER_MON_GOURGEIST_2                           602
#define FRONTIER_MON_TYPE_NULL_2                           603
#define FRONTIER_MON_RHYDON_2                              604
#define FRONTIER_MON_GLISCOR_2                             605
#define FRONTIER_MON_MEDICHAM_2                            606
#define FRONTIER_MON_WEAVILE_2                             607
#define FRONTIER_MON_FEAROW_2                              608
#define FRONTIER_MON_SCOLIPEDE_2                           609
#define FRONTIER_MON_JYNX_2                                610
#define FRONTIER_MON_AEGISLASH_2                           611
#define FRONTIER_MON_DODRIO_2                              612
#define FRONTIER_MON_MIMIKYU_2                             613
#define FRONTIER_MON_LANTURN_2                             614
#define FRONTIER_MON_PANGORO_2                             615
#define FRONTIER_MON_FORRETRESS_2                          616
#define FRONTIER_MON_MAMOSWINE_2                           617
#define FRONTIER_MON_XATU_2                                618
#define FRONTIER_MON_STARAPTOR_2                           619
#define FRONTIER_MON_MAROWAK_2                             620
#define FRONTIER_MON_GASTRODON_2                           621
#define FRONTIER_MON_CLEFABLE_2                            622
#define FRONTIER_MON_MIENSHAO_2                            623
#define FRONTIER_MON_RAICHU_2                              624
#define FRONTIER_MON_ROTOM_FROST_2                         625
#define FRONTIER_MON_MANECTRIC_2                           626
#define FRONTIER_MON_TANGROWTH_2                           627
#define FRONTIER_MON_VICTREEBEL_2                          628
#define FRONTIER_MON_ROTOM_MOW_2                           629
#define FRONTIER_MON_EXPLOUD_2                             630
#define FRONTIER_MON_TREVENANT_2                           631
#define FRONTIER_MON_GLALIE_2                              632
#define FRONTIER_MON_LEAFEON_2                             633
#define FRONTIER_MON_HYPNO_2                               634
#define FRONTIER_MON_GIGALITH_2                            635
#define FRONTIER_MON_RHYPERIOR_2                           636
#define FRONTIER_MON_GALLADE_2                             637
#define FRONTIER_MON_WEEZING_2                             638
#define FRONTIER_MON_BEWEAR_2                              639
#define FRONTIER_MON_ELECTIVIRE_2                          640
#define FRONTIER_MON_LOPUNNY_2                             641
#define FRONTIER_MON_SLOWBRO_2                             642
#define FRONTIER_MON_BEHEEYEM_2                            643
#define FRONTIER_MON_MILTANK_2                             644
#define FRONTIER_MON_NOIVERN_2                             645
#define FRONTIER_MON_NIDOQUEEN_2                           646
#define FRONTIER_MON_KROOKODILE_2                          647
#define FRONTIER_MON_MAGMORTAR_2                           648
#define FRONTIER_MON_FERROTHORN_2                          649
#define FRONTIER_MON_ARMALDO_2                             650
#define FRONTIER_MON_CLAWITZER_2                           651
#define FRONTIER_MON_RAPIDASH_2                            652
#define FRONTIER_MON_TOXICROAK_2                           653
#define FRONTIER_MON_GENGAR_2                              654
#define FRONTIER_MON_TOGEDEMARU_2                          655
#define FRONTIER_MON_SCIZOR_2                              656
#define FRONTIER_MON_GALVANTULA_2                          657
#define FRONTIER_MON_ESPEON_2                              658
#define FRONTIER_MON_LYCANROC_MIDNIGHT_2                   659
#define FRONTIER_MON_DONPHAN_2                             660
#define FRONTIER_MON_PALOSSAND_2                           661
#define FRONTIER_MON_WAILORD_2                             662
#define FRONTIER_MON_TURTONATOR_2                          663
#define FRONTIER_MON_MACHAMP_2                             664
#define FRONTIER_MON_LYCANROC_DUSK_2                       665
#define FRONTIER_MON_STEELIX_2                             666
#define FRONTIER_MON_JELLICENT_2                           667
#define FRONTIER_MON_AERODACTYL_2                          668
#define FRONTIER_MON_CINCCINO_2                            669
#define FRONTIER_MON_GARDEVOIR_2                           670
#define FRONTIER_MON_TSAREENA_2                            671
#define FRONTIER_MON_STARMIE_2                             672
#define FRONTIER_MON_HAXORUS_2                             673
#define FRONTIER_MON_VENUSAUR_2                            674
#define FRONTIER_MON_SEISMITOAD_2                          675
#define FRONTIER_MON_JOLTEON_2                             676
#define FRONTIER_MON_DARMANITAN_2                          677
#define FRONTIER_MON_MEGANIUM_2                            678
#define FRONTIER_MON_SYLVEON_2                             679
#define FRONTIER_MON_UMBREON_2                             680
#define FRONTIER_MON_EMPOLEON_2                            681
#define FRONTIER_MON_FERALIGATR_2                          682
#define FRONTIER_MON_TYRANTRUM_2                           683
#define FRONTIER_MON_INCINEROAR_2                          684
#define FRONTIER_MON_VANILLUXE_2                           685
#define FRONTIER_MON_SCEPTILE_2                            686
#define FRONTIER_MON_INFERNAPE_2                           687
#define FRONTIER_MON_TYPHLOSION_2                          688
#define FRONTIER_MON_GRENINJA_2                            689
#define FRONTIER_MON_CROBAT_2                              690
#define FRONTIER_MON_PRIMARINA_2                           691
#define FRONTIER_MON_GYARADOS_2                            692
#define FRONTIER_MON_TOGEKISS_2                            693
#define FRONTIER_MON_KINGDRA_2                             694
#define FRONTIER_MON_TOXAPEX_2                             695
#define FRONTIER_MON_MILOTIC_2                             696
#define FRONTIER_MON_ROTOM_HEAT_2                          697
#define FRONTIER_MON_SALAMENCE_2                           698
#define FRONTIER_MON_KOMMO_O_2                             699
#define FRONTIER_MON_SLAKING_2                             700

#define FRONTIER_MON_COBALION_1                            701
#define FRONTIER_MON_TERRAKION_1                           702
#define FRONTIER_MON_VIRIZION_1                            703
#define FRONTIER_MON_RAIKOU_1                              704
#define FRONTIER_MON_ENTEI_1                               705
#define FRONTIER_MON_SUICUNE_1                             706
#define FRONTIER_MON_HEATRAN_1                             707
#define FRONTIER_MON_REGIROCK_1                            708
#define FRONTIER_MON_REGICE_1                              709
#define FRONTIER_MON_REGISTEEL_1                           710
#define FRONTIER_MON_LATIAS_1                              711
#define FRONTIER_MON_LATIOS_1                              712
#define FRONTIER_MON_COBALION_2                            713
#define FRONTIER_MON_TERRAKION_2                           714
#define FRONTIER_MON_VIRIZION_2                            715
#define FRONTIER_MON_RAIKOU_2                              716
#define FRONTIER_MON_ENTEI_2                               717
#define FRONTIER_MON_SUICUNE_2                             718
#define FRONTIER_MON_HEATRAN_2                             719
#define FRONTIER_MON_REGIROCK_2                            720
#define FRONTIER_MON_REGICE_2                              721
#define FRONTIER_MON_REGISTEEL_2                           722
#define FRONTIER_MON_LATIAS_2                              723
#define FRONTIER_MON_LATIOS_2                              724
#define FRONTIER_MON_COBALION_3                            725
#define FRONTIER_MON_TERRAKION_3                           726
#define FRONTIER_MON_VIRIZION_3                            727
#define FRONTIER_MON_RAIKOU_3                              728
#define FRONTIER_MON_ENTEI_3                               729
#define FRONTIER_MON_SUICUNE_3                             730
#define FRONTIER_MON_HEATRAN_3                             731
#define FRONTIER_MON_REGIROCK_3                            732
#define FRONTIER_MON_REGICE_3                              733
#define FRONTIER_MON_REGISTEEL_3                           734
#define FRONTIER_MON_LATIAS_3                              735
#define FRONTIER_MON_LATIOS_3                              736
#define FRONTIER_MON_COBALION_4                            737
#define FRONTIER_MON_TERRAKION_4                           738
#define FRONTIER_MON_VIRIZION_4                            739
#define FRONTIER_MON_RAIKOU_4                              740
#define FRONTIER_MON_ENTEI_4                               741
#define FRONTIER_MON_SUICUNE_4                             742
#define FRONTIER_MON_HEATRAN_4                             743
#define FRONTIER_MON_REGIROCK_4                            744
#define FRONTIER_MON_REGICE_4                              745
#define FRONTIER_MON_REGISTEEL_4                           746
#define FRONTIER_MON_LATIAS_4                              747
#define FRONTIER_MON_LATIOS_4                              748
#define FRONTIER_MON_GENGAR_3                              749
#define FRONTIER_MON_CHANDELURE_3                          750
#define FRONTIER_MON_GENGAR_4                              751
#define FRONTIER_MON_CHANDELURE_4                          752
#define FRONTIER_MON_ESPEON_3                              753
#define FRONTIER_MON_LUCARIO_3                             754
#define FRONTIER_MON_ESPEON_4                              755
#define FRONTIER_MON_LUCARIO_4                             756
#define FRONTIER_MON_MACHAMP_3                             757
#define FRONTIER_MON_CONKELDURR_3                          758
#define FRONTIER_MON_MACHAMP_4                             759
#define FRONTIER_MON_CONKELDURR_4                          760
#define FRONTIER_MON_GARDEVOIR_3                           761
#define FRONTIER_MON_SERPERIOR_3                           762
#define FRONTIER_MON_GARDEVOIR_4                           763
#define FRONTIER_MON_SERPERIOR_4                           764
#define FRONTIER_MON_STARMIE_3                             765
#define FRONTIER_MON_BLAZIKEN_3                            766
#define FRONTIER_MON_STARMIE_4                             767
#define FRONTIER_MON_BLAZIKEN_4                            768
#define FRONTIER_MON_LAPRAS_3                              769
#define FRONTIER_MON_GRENINJA_3                            770
#define FRONTIER_MON_LAPRAS_4                              771
#define FRONTIER_MON_GRENINJA_4                            772
#define FRONTIER_MON_SNORLAX_3                             773
#define FRONTIER_MON_TOGEKISS_3                            774
#define FRONTIER_MON_SNORLAX_4                             775
#define FRONTIER_MON_TOGEKISS_4                            776
#define FRONTIER_MON_SALAMENCE_3                           777
#define FRONTIER_MON_GARCHOMP_3                            778
#define FRONTIER_MON_SALAMENCE_4                           779
#define FRONTIER_MON_GARCHOMP_4                            780
#define FRONTIER_MON_METAGROSS_3                           781
#define FRONTIER_MON_KOMMO_O_3                             782
#define FRONTIER_MON_METAGROSS_4                           783
#define FRONTIER_MON_KOMMO_O_4                             784
#define FRONTIER_MON_REGIROCK_5                            785
#define FRONTIER_MON_REGIROCK_6                            786
#define FRONTIER_MON_REGICE_5                              787
#define FRONTIER_MON_REGICE_6                              788
#define FRONTIER_MON_REGISTEEL_5                           789
#define FRONTIER_MON_REGISTEEL_6                           790
#define FRONTIER_MON_LATIAS_5                              791
#define FRONTIER_MON_LATIAS_6                              792
#define FRONTIER_MON_LATIAS_7                              793
#define FRONTIER_MON_LATIAS_8                              794
#define FRONTIER_MON_LATIOS_5                              795
#define FRONTIER_MON_LATIOS_6                              796
#define FRONTIER_MON_LATIOS_7                              797
#define FRONTIER_MON_LATIOS_8                              798

// Mons above this point can only appear > level 50
#define FRONTIER_MONS_HIGH_TIER                            798

#define FRONTIER_MON_DRAGONITE_1                           799
#define FRONTIER_MON_DRAGONITE_2                           800
#define FRONTIER_MON_DRAGONITE_3                           801
#define FRONTIER_MON_DRAGONITE_4                           802
#define FRONTIER_MON_GOODRA_1                              803
#define FRONTIER_MON_GOODRA_2                              804
#define FRONTIER_MON_GOODRA_3                              805
#define FRONTIER_MON_GOODRA_4                              806
#define FRONTIER_MON_VOLCARONA_1                           807
#define FRONTIER_MON_VOLCARONA_2                           808
#define FRONTIER_MON_VOLCARONA_3                           809
#define FRONTIER_MON_VOLCARONA_4                           810
#define FRONTIER_MON_HYDREIGON_1                           811
#define FRONTIER_MON_HYDREIGON_2                           812
#define FRONTIER_MON_HYDREIGON_3                           813
#define FRONTIER_MON_HYDREIGON_4                           814
#define FRONTIER_MON_TYRANITAR_1                           815
#define FRONTIER_MON_TYRANITAR_2                           816
#define FRONTIER_MON_TYRANITAR_3                           817
#define FRONTIER_MON_TYRANITAR_4                           818
#define FRONTIER_MON_COBALION_5                            819
#define FRONTIER_MON_TERRAKION_5                           820
#define FRONTIER_MON_VIRIZION_5                            821
#define FRONTIER_MON_KELDEO_1                              822
#define FRONTIER_MON_KELDEO_2                              823
#define FRONTIER_MON_KELDEO_3                              824
#define FRONTIER_MON_RAIKOU_5                              825
#define FRONTIER_MON_RAIKOU_6                              826
#define FRONTIER_MON_ENTEI_5                               827
#define FRONTIER_MON_ENTEI_6                               828
#define FRONTIER_MON_SUICUNE_5                             829
#define FRONTIER_MON_SUICUNE_6                             830
#define FRONTIER_MON_HEATRAN_5                             831
#define FRONTIER_MON_HEATRAN_6                             832


//Custom Frontier Mons

//Memes
#define FRONTIER_MON_TRUBBISH                              833
#define FRONTIER_MON_SLAKOTH_1                             834
#define FRONTIER_MON_SLAKOTH_2                             835
//Megas
#define FRONTIER_MON_MEGA_VENUSAUR_1                       836
#define FRONTIER_MON_MEGA_VENUSAUR_2                       837
#define FRONTIER_MON_MEGA_CHARIZARD_X_1                    838
#define FRONTIER_MON_MEGA_CHARIZARD_X_2                    839
#define FRONTIER_MON_MEGA_CHARIZARD_Y_1                    840
#define FRONTIER_MON_MEGA_CHARIZARD_Y_2                    841
#define FRONTIER_MON_MEGA_BLASTOISE_1                      842
#define FRONTIER_MON_MEGA_BLASTOISE_2                      843
#define FRONTIER_MON_MEGA_BEEDRILL_1                       844
#define FRONTIER_MON_MEGA_BEEDRILL_2                       845
#define FRONTIER_MON_MEGA_PIDGEOT_1                        846
#define FRONTIER_MON_MEGA_PIDGEOT_2                        847
#define FRONTIER_MON_MEGA_ALAKAZAM_1                       848
#define FRONTIER_MON_MEGA_ALAKAZAM_2                       849
#define FRONTIER_MON_MEGA_SLOWBRO_1                        850
#define FRONTIER_MON_MEGA_SLOWBRO_2                        851
#define FRONTIER_MON_MEGA_GENGAR_1                         852
#define FRONTIER_MON_MEGA_GENGAR_2                         853
#define FRONTIER_MON_MEGA_KANGASKHAN_1                     854
#define FRONTIER_MON_MEGA_KANGASKHAN_2                     855
#define FRONTIER_MON_MEGA_PINSIR_1                         856
#define FRONTIER_MON_MEGA_PINSIR_2                         857
#define FRONTIER_MON_MEGA_GYARADOS_1                       858
#define FRONTIER_MON_MEGA_GYARADOS_2                       859
#define FRONTIER_MON_MEGA_AERODACTYL_1                     860
#define FRONTIER_MON_MEGA_AERODACTYL_2                     861
#define FRONTIER_MON_MEGA_MEWTWO_X_1                       862
#define FRONTIER_MON_MEGA_MEWTWO_X_2                       863
#define FRONTIER_MON_MEGA_MEWTWO_Y_1                       864
#define FRONTIER_MON_MEGA_MEWTWO_Y_2                       865
#define FRONTIER_MON_MEGA_AMPHAROS_1                       866
#define FRONTIER_MON_MEGA_AMPHAROS_2                       867
#define FRONTIER_MON_MEGA_STEELIX_1                        868
#define FRONTIER_MON_MEGA_STEELIX_2                        869
#define FRONTIER_MON_MEGA_SCIZOR_1                         870
#define FRONTIER_MON_MEGA_SCIZOR_2                         871
#define FRONTIER_MON_MEGA_HERACROSS_1                      872
#define FRONTIER_MON_MEGA_HERACROSS_2                      873
#define FRONTIER_MON_MEGA_HOUNDOOM_1                       874
#define FRONTIER_MON_MEGA_HOUNDOOM_2                       875
#define FRONTIER_MON_MEGA_TYRANITAR_1                      876
#define FRONTIER_MON_MEGA_TYRANITAR_2                      877
#define FRONTIER_MON_MEGA_SCEPTILE_1                       878
#define FRONTIER_MON_MEGA_SCEPTILE_2                       879
#define FRONTIER_MON_MEGA_BLAZIKEN_1                       880
#define FRONTIER_MON_MEGA_BLAZIKEN_2                       881
#define FRONTIER_MON_MEGA_SWAMPERT_1                       882
#define FRONTIER_MON_MEGA_SWAMPERT_2                       883
#define FRONTIER_MON_MEGA_GARDEVOIR_1                      884
#define FRONTIER_MON_MEGA_GARDEVOIR_2                      885
#define FRONTIER_MON_MEGA_SABLEYE_1                        886
#define FRONTIER_MON_MEGA_SABLEYE_2                        887
#define FRONTIER_MON_MEGA_MAWILE_1                         888
#define FRONTIER_MON_MEGA_MAWILE_2                         889
#define FRONTIER_MON_MEGA_AGGRON_1                         890
#define FRONTIER_MON_MEGA_AGGRON_2                         891
#define FRONTIER_MON_MEGA_MEDICHAM_1                       892
#define FRONTIER_MON_MEGA_MEDICHAM_2                       893
#define FRONTIER_MON_MEGA_MANECTRIC_1                      894
#define FRONTIER_MON_MEGA_MANECTRIC_2                      895
#define FRONTIER_MON_MEGA_SHARPEDO_1                       896
#define FRONTIER_MON_MEGA_SHARPEDO_2                       897
#define FRONTIER_MON_MEGA_CAMERUPT_1                       898
#define FRONTIER_MON_MEGA_CAMERUPT_2                       899
#define FRONTIER_MON_MEGA_ALTARIA_1                        900
#define FRONTIER_MON_MEGA_ALTARIA_2                        901
#define FRONTIER_MON_MEGA_BANETTE_1                        902
#define FRONTIER_MON_MEGA_BANETTE_2                        903
#define FRONTIER_MON_MEGA_ABSOL_1                          904
#define FRONTIER_MON_MEGA_ABSOL_2                          905
#define FRONTIER_MON_MEGA_GLALIE_1                         906
#define FRONTIER_MON_MEGA_GLALIE_2                         907
#define FRONTIER_MON_MEGA_SALAMENCE_1                      908
#define FRONTIER_MON_MEGA_SALAMENCE_2                      909
#define FRONTIER_MON_MEGA_METAGROSS_1                      910
#define FRONTIER_MON_MEGA_METAGROSS_2                      911
#define FRONTIER_MON_MEGA_LATIAS_1                         912
#define FRONTIER_MON_MEGA_LATIAS_2                         913
#define FRONTIER_MON_MEGA_LATIOS_1                         914
#define FRONTIER_MON_MEGA_LATIOS_2                         915
#define FRONTIER_MON_PRIMAL_GROUDON_1                      916
#define FRONTIER_MON_PRIMAL_GROUDON_2                      917
#define FRONTIER_MON_PRIMAL_KYOGRE_1                       918
#define FRONTIER_MON_PRIMAL_KYOGRE_2                       919
#define FRONTIER_MON_MEGA_RAYQUAZA_1                       920
#define FRONTIER_MON_MEGA_RAYQUAZA_2                       921
#define FRONTIER_MON_MEGA_LOPUNNY_1                        922
#define FRONTIER_MON_MEGA_LOPUNNY_2                        923
#define FRONTIER_MON_MEGA_GARCHOMP_1                       924
#define FRONTIER_MON_MEGA_GARCHOMP_2                       925
#define FRONTIER_MON_MEGA_LUCARIO_1                        926
#define FRONTIER_MON_MEGA_LUCARIO_2                        927
#define FRONTIER_MON_MEGA_ABOMASNOW_1                      928
#define FRONTIER_MON_MEGA_ABOMASNOW_2                      929
#define FRONTIER_MON_MEGA_GALLADE_1                        930
#define FRONTIER_MON_MEGA_GALLADE_2                        931
#define FRONTIER_MON_MEGA_AUDINO_1                         932
#define FRONTIER_MON_MEGA_AUDINO_2                         933
#define FRONTIER_MON_MEGA_DIANCIE_1                        934
#define FRONTIER_MON_MEGA_DIANCIE_2                        935
//Frontier starter teams
//Classic
#define FRONTIER_MON_ARIADOS_HYPER_OFFENSE                 936
#define FRONTIER_MON_TOXICROAK_HYPER_OFFENSE               937
#define FRONTIER_MON_ZANGOOSE_HYPER_OFFENSE                938
#define FRONTIER_MON_AURORUS_OFFENSE                       939
#define FRONTIER_MON_BEARTIC_OFFENSE                       940
#define FRONTIER_MON_MEGA_GALLADE_OFFENSE                  941
#define FRONTIER_MON_TYPHLOSION_BALANCE                    942
#define FRONTIER_MON_FERALIGATR_BALANCE                    943
#define FRONTIER_MON_VENUSAUR_BALANCE                      944
#define FRONTIER_MON_SWAMPERT_BULKY_OFFENSE                945
#define FRONTIER_MON_RHYDON_BULKY_OFFENSE                  946
#define FRONTIER_MON_MEGANIUM_BULKY_OFFENSE                947
#define FRONTIER_MON_REGICE_STALL                          948
#define FRONTIER_MON_SLOWBRO_STALL                         949
#define FRONTIER_MON_GLISCOR_STALL                         950
#define FRONTIER_MON_BLANK1_BLANK1                         951
#define FRONTIER_MON_BLANK2_BLANK1                         952
#define FRONTIER_MON_BLANK3_BLANK1                         953
#define FRONTIER_MON_BLANK1_BLANK2                         954
#define FRONTIER_MON_BLANK2_BLANK2                         955
#define FRONTIER_MON_BLANK3_BLANK2                         956
//Field Effects
#define FRONTIER_MON_WALREIN_HAIL                          957
#define FRONTIER_MON_DEWGONG_HAIL                          958
#define FRONTIER_MON_RAIKOU_HAIL                           959
#define FRONTIER_MON_LAPRAS_RAIN                           960
#define FRONTIER_MON_SEISMITOAD_RAIN                       961
#define FRONTIER_MON_ROTOM_FAN_RAIN                        962
#define FRONTIER_MON_MAGCARGO_SUN                          963
#define FRONTIER_MON_VICTREEBEL_SUN                        964
#define FRONTIER_MON_MEGA_HOUNDOOM_SUN                     965
#define FRONTIER_MON_GIGALITH_SANDSTORM                    966
#define FRONTIER_MON_EXCADRILL_SANDSTORM                   967
#define FRONTIER_MON_STOUTLAND_SANDSTORM                   968
#define FRONTIER_MON_ROTOM_MOW_GRASSY_TERRAIN              969
#define FRONTIER_MON_GOGOAT_GRASSY_TERRAIN                 970
#define FRONTIER_MON_SEVIPER_GRASSY_TERRAIN                971
#define FRONTIER_MON_BEHEEYEM_PSYCHIC_TERRAIN              972
#define FRONTIER_MON_DELPHOX_PSYCHIC_TERRAIN               973
#define FRONTIER_MON_MEGA_SHARPEDO_PSYCHIC_TERRAIN         974
#define FRONTIER_MON_OCTILLERY_TRICK_ROOM                  975
#define FRONTIER_MON_DARMANITAN_ZEN_TRICK_ROOM             976
#define FRONTIER_MON_RAMPARDOS_TRICK_ROOM                  977
//Special
#define FRONTIER_MON_JOLTEON_BATON_PASS                    978
#define FRONTIER_MON_VAPOREON_BATON_PASS                   979
#define FRONTIER_MON_ESPEON_BATON_PASS                     980
#define FRONTIER_MON_TOXICROAK_GIMMICK                     981
#define FRONTIER_MON_TOXAPEX_GIMMICK                       982
#define FRONTIER_MON_SKARMORY_GIMMICK                      983
#define FRONTIER_MON_NINJASK_EGGTACTICAL                   984
#define FRONTIER_MON_SCIZOR_EGGTACTICAL                    985
#define FRONTIER_MON_UMBREON_EGGTACTICAL                   986
#define FRONTIER_MON_DELIBIRD_MASOCHIST                    987
#define FRONTIER_MON_DUNSPARCE_MASOCHIST                   988
#define FRONTIER_MON_LUVDISC_MASOCHIST                     989
#define FRONTIER_MON_HIPPOWDON_FEAR                        990
#define FRONTIER_MON_TOGEDEMARU_FEAR                       991
#define FRONTIER_MON_MAGNEMITE_FEAR                        992
#define FRONTIER_MON_BLANK1_BLANK3                         993
#define FRONTIER_MON_BLANK2_BLANK3                         994
#define FRONTIER_MON_BLANK3_BLANK3                         995
#define FRONTIER_MON_BLANK1_BLANK4                         996
#define FRONTIER_MON_BLANK2_BLANK4                         997
#define FRONTIER_MON_BLANK3_BLANK4                         998

#define NUM_FRONTIER_MONS                                  999

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
