#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MON_LEAFEON_3                             0
#define FRONTIER_MON_AZUMARILL_4                           1
#define FRONTIER_MON_ILLUMISE_3                            2
#define FRONTIER_MON_VOLBEAT_3                             3
#define FRONTIER_MON_DRAPION_3                             4
#define FRONTIER_MON_GALLADE_3                             5
#define FRONTIER_MON_GYARADOS_3                            6
#define FRONTIER_MON_SLOWKING_3                            7
#define FRONTIER_MON_METAPOD                               8
#define FRONTIER_MON_KAKUNA                                9
#define FRONTIER_MON_TOGEDEMARU_3                          10
#define FRONTIER_MON_SILCOON                               11
#define FRONTIER_MON_CASCOON                               12
#define FRONTIER_MON_WHIMSICOTT_3                          13
#define FRONTIER_MON_QUAGSIRE_3                            14
#define FRONTIER_MON_HITMONTOP_3                           15
#define FRONTIER_MON_HAXORUS_3                             16
#define FRONTIER_MON_AMBIPOM_4                             17
#define FRONTIER_MON_GOGOAT_3                              18
#define FRONTIER_MON_LUDICOLO_3                            19
#define FRONTIER_MON_MIGHTYENA_3                           20
#define FRONTIER_MON_SHEDINJA                              21
#define FRONTIER_MON_SCRAFTY_3                             22
#define FRONTIER_MON_PORYGON2_3                            23
#define FRONTIER_MON_LINOONE_3                             24
#define FRONTIER_MON_CROBAT_3                              25
#define FRONTIER_MON_SMEARGLE_1                            26
#define FRONTIER_MON_HERACROSS_3                           27
#define FRONTIER_MON_AZUMARILL_3                           28
#define FRONTIER_MON_SCEPTILE_4                            29
#define FRONTIER_MON_MAGMORTAR_3                           30
#define FRONTIER_MON_MAMOSWINE_3                           31
#define FRONTIER_MON_SMEARGLE_2                            32
#define FRONTIER_MON_GLISCOR_3                             33
#define FRONTIER_MON_RATICATE_3                            34
#define FRONTIER_MON_WOBBUFFET_3                           35
#define FRONTIER_MON_DELCATTY_3                            36
#define FRONTIER_MON_NOIVERN_3                             37
#define FRONTIER_MON_ARCHEOPS_3                            38
#define FRONTIER_MON_YANMEGA_2                             39
#define FRONTIER_MON_SCYTHER_3                             40
#define FRONTIER_MON_SCIZOR_3                              41
#define FRONTIER_MON_GOLISOPOD_3                           42
#define FRONTIER_MON_SKARMORY_3                            43
#define FRONTIER_MON_SWELLOW_3                             44
#define FRONTIER_MON_PIDGEOT_3                             45
#define FRONTIER_MON_NIDOKING_3                            46
#define FRONTIER_MON_NIDOQUEEN_3                           47
#define FRONTIER_MON_SYLVEON_3                             48
#define FRONTIER_MON_LUXRAY_3                              49
#define FRONTIER_MON_AUDINO_3                              50
#define FRONTIER_MON_SLAKING_3                             51
#define FRONTIER_MON_GALVANTULA_3                          52
#define FRONTIER_MON_ARBOK_3                               53
#define FRONTIER_MON_DITTO                                 54
#define FRONTIER_MON_WHISCASH_3                            55
#define FRONTIER_MON_PERSIAN_3                             56
#define FRONTIER_MON_FORRETRESS_3                          57
#define FRONTIER_MON_SHUCKLE_3                             58
#define FRONTIER_MON_VANILLUXE_3                           59
#define FRONTIER_MON_MANTINE_3                             60
#define FRONTIER_MON_DURANT_3                              61
#define FRONTIER_MON_MIMIKYU_3                             62
#define FRONTIER_MON_DUSKNOIR_3                            63
#define FRONTIER_MON_VIKAVOLT_3                            64
#define FRONTIER_MON_NINETALES_3                           65
#define FRONTIER_MON_ROTOM_FROST_3                         66
#define FRONTIER_MON_SANDSLASH_3                           67
#define FRONTIER_MON_POLIWRATH_3                           68
#define FRONTIER_MON_MASQUERAIN_3                          69
#define FRONTIER_MON_RHYPERIOR_3                           70
#define FRONTIER_MON_WAILORD_4                             71
#define FRONTIER_MON_PORYGON_Z_3                           72
#define FRONTIER_MON_OCTILLERY_3                           73
#define FRONTIER_MON_GARCHOMP_5                            74
#define FRONTIER_MON_CLAYDOL_3                             75
#define FRONTIER_MON_AURORUS_3                             76
#define FRONTIER_MON_SALAMENCE_5                           77
#define FRONTIER_MON_ZANGOOSE_3                            78
#define FRONTIER_MON_SEVIPER_3                             79
#define FRONTIER_MON_VENOMOTH_3                            80
#define FRONTIER_MON_PRIMEAPE_3                            81
#define FRONTIER_MON_EMBOAR_3                              82
#define FRONTIER_MON_CLOYSTER_3                            83
#define FRONTIER_MON_JYNX_3                                84
#define FRONTIER_MON_CAMERUPT_3                            85
#define FRONTIER_MON_SHARPEDO_3                            86
#define FRONTIER_MON_CRAWDAUNT_3                           87
#define FRONTIER_MON_CHARIZARD_3                           88
#define FRONTIER_MON_DELPHOX_3                             89
#define FRONTIER_MON_ALAKAZAM_3                            90
#define FRONTIER_MON_DODRIO_3                              91
#define FRONTIER_MON_SCOLIPEDE_3                           92
#define FRONTIER_MON_HAWLUCHA_3                            93
#define FRONTIER_MON_SCEPTILE_3                            94
#define FRONTIER_MON_TALONFLAME_3                          95
#define FRONTIER_MON_WAILORD_3                             96
#define FRONTIER_MON_BLASTOISE_3                           97
#define FRONTIER_MON_FERALIGATR_3                          98
#define FRONTIER_MON_SLOWBRO_3                             99
#define FRONTIER_MON_TORTERRA_3                            100
#define FRONTIER_MON_MEGANIUM_3                            101
#define FRONTIER_MON_VILEPLUME_3                           102
#define FRONTIER_MON_TENTACRUEL_3                          103
#define FRONTIER_MON_MAROWAK_3                             104
#define FRONTIER_MON_SEAKING_3                             105
#define FRONTIER_MON_TROPIUS_3                             106
#define FRONTIER_MON_CLEFABLE_3                            107
#define FRONTIER_MON_MAGNEZONE_3                           108
#define FRONTIER_MON_DEWGONG_3                             109
#define FRONTIER_MON_TOXICROAK_3                           110
#define FRONTIER_MON_KINGLER_3                             111
#define FRONTIER_MON_EXEGGUTOR_3                           112
#define FRONTIER_MON_TOUCANNON_3                           113
#define FRONTIER_MON_CINCCINO_3                            114
#define FRONTIER_MON_ROTOM_FAN_3                           115
#define FRONTIER_MON_EELEKTROSS_3                          116
#define FRONTIER_MON_PELIPPER_3                            117
#define FRONTIER_MON_DELIBIRD                              118
#define FRONTIER_MON_ROTOM_HEAT_3                          119
#define FRONTIER_MON_HIPPOWDON_3                           120
#define FRONTIER_MON_GRUMPIG_3                             121
#define FRONTIER_MON_TYRANTRUM_3                           122
#define FRONTIER_MON_LUVDISC                               123
#define FRONTIER_MON_TOXAPEX_3                             124
#define FRONTIER_MON_CACTURNE_3                            125
#define FRONTIER_MON_UNOWN                                 126
#define FRONTIER_MON_DRAGALGE_3                            127
#define FRONTIER_MON_PRIMARINA_4                           128
#define FRONTIER_MON_LILLIGANT_3                           129
#define FRONTIER_MON_ROTOM_MOW_3                           130
#define FRONTIER_MON_CLAWITZER_3                           131
#define FRONTIER_MON_FLYGON_3                              132
#define FRONTIER_MON_MUDSDALE_3                            133
#define FRONTIER_MON_PRIMARINA_3                           134
#define FRONTIER_MON_STARAPTOR_3                           135
#define FRONTIER_MON_SALAZZLE_3                            136
#define FRONTIER_MON_FARFETCHD                             137
#define FRONTIER_MON_OMASTAR_3                             138
#define FRONTIER_MON_KABUTOPS_3                            139
#define FRONTIER_MON_CRADILY_3                             140
#define FRONTIER_MON_ARMALDO_3                             141
#define FRONTIER_MON_AMBIPOM_3                             142
#define FRONTIER_MON_ELECTIVIRE_3                          143
#define FRONTIER_MON_EXPLOUD_3                             144
#define FRONTIER_MON_SPINDA                                145
#define FRONTIER_MON_ZOROARK_3                             146
#define FRONTIER_MON_ZOROARK_4                             147
#define FRONTIER_MON_AMPHAROS_3                            148
#define FRONTIER_MON_FLAREON_3                             149
#define FRONTIER_MON_PROBOPASS                             150
#define FRONTIER_MON_CORSOLA                               151
#define FRONTIER_MON_MAWILE                                152
#define FRONTIER_MON_BEEDRILL_1                            153
#define FRONTIER_MON_BEEDRILL_2                            154
#define FRONTIER_MON_EMPOLEON_3                            155
#define FRONTIER_MON_STEELIX_3                             156
#define FRONTIER_MON_BEAUTIFLY                             157
#define FRONTIER_MON_DUSTOX                                158
#define FRONTIER_MON_LEDIAN                                159
#define FRONTIER_MON_ARIADOS                               160
#define FRONTIER_MON_YANMEGA_1                             161

#define FRONTIER_MON_DELCATTY_1                            162
#define FRONTIER_MON_SABLEYE_1                             163
#define FRONTIER_MON_LICKILICKY_1                          164
#define FRONTIER_MON_FERROTHORN_3                          165
#define FRONTIER_MON_GOLEM_3                               166
#define FRONTIER_MON_CHERRIM_1                             167
#define FRONTIER_MON_AUDINO_1                              168
#define FRONTIER_MON_DARMANITAN_ZEN_1                      169
#define FRONTIER_MON_ROTOM_WASH_3                          170
#define FRONTIER_MON_WHIMSICOTT_1                          171
#define FRONTIER_MON_VOLBEAT_1                             172
#define FRONTIER_MON_ILLUMISE_1                            173
#define FRONTIER_MON_MARACTUS_1                            174
#define FRONTIER_MON_INCINEROAR_3                          175
#define FRONTIER_MON_SAMUROTT_3                            176
#define FRONTIER_MON_PARASECT_1                            177
#define FRONTIER_MON_HITMONLEE_3                           178
#define FRONTIER_MON_AEGISLASH_3                           179
#define FRONTIER_MON_GOGOAT_1                              180
#define FRONTIER_MON_TYPHLOSION_3                          181
#define FRONTIER_MON_GRENINJA_5                            182
#define FRONTIER_MON_RAICHU_3                              183
#define FRONTIER_MON_NOCTOWL_3                             184
#define FRONTIER_MON_WOBBUFFET_1                           185
#define FRONTIER_MON_PLUSLE_1                              186
#define FRONTIER_MON_MINUN_1                               187
#define FRONTIER_MON_LURANTIS_1                            188
#define FRONTIER_MON_INFERNAPE_3                           189
#define FRONTIER_MON_SWAMPERT_3                            190
#define FRONTIER_MON_DARMANITAN_3                          191
#define FRONTIER_MON_AZUMARILL_1                           192
#define FRONTIER_MON_SUDOWOODO_1                           193
#define FRONTIER_MON_MAGCARGO_1                            194
#define FRONTIER_MON_PANGORO_3                             195
#define FRONTIER_MON_WALREIN_3                             196
#define FRONTIER_MON_RATICATE_1                            197
#define FRONTIER_MON_MASQUERAIN_1                          198
#define FRONTIER_MON_FURRET_1                              199
#define FRONTIER_MON_DUNSPARCE_1                           200
#define FRONTIER_MON_GOODRA_1                              201
#define FRONTIER_MON_MIGHTYENA_1                           202
#define FRONTIER_MON_LINOONE_1                             203
#define FRONTIER_MON_CASTFORM_1                            204
#define FRONTIER_MON_KOMMO_O_5                             205
#define FRONTIER_MON_METAGROSS_5                           206
#define FRONTIER_MON_WIGGLYTUFF_1                          207
#define FRONTIER_MON_SUNFLORA_1                            208
#define FRONTIER_MON_BUTTERFREE_1                          209
#define FRONTIER_MON_CONKELDURR_5                          210
#define FRONTIER_MON_QWILFISH_1                            211
#define FRONTIER_MON_JELLICENT_3                           212
#define FRONTIER_MON_PELIPPER_1                            213
#define FRONTIER_MON_SWELLOW_1                             214
#define FRONTIER_MON_LYCANROC_MIDNIGHT_3                   215
#define FRONTIER_MON_LILLIGANT_1                           216
#define FRONTIER_MON_ARBOK_1                               217
#define FRONTIER_MON_PERSIAN_1                             218
#define FRONTIER_MON_KINGDRA_3                             219
#define FRONTIER_MON_KECLEON_1                             220
#define FRONTIER_MON_SCRAFTY_1                             221
#define FRONTIER_MON_LUNATONE_1                            222
#define FRONTIER_MON_SOLROCK_1                             223
#define FRONTIER_MON_NOCTOWL_1                             224
#define FRONTIER_MON_SANDSLASH_1                           225
#define FRONTIER_MON_VENOMOTH_1                            226
#define FRONTIER_MON_BLISSEY_1                             227
#define FRONTIER_MON_SEAKING_1                             228
#define FRONTIER_MON_JUMPLUFF_1                            229
#define FRONTIER_MON_BASTIODON_1                           230
#define FRONTIER_MON_LIEPARD_1                             231
#define FRONTIER_MON_PRIMEAPE_1                            232
#define FRONTIER_MON_HITMONLEE_1                           233
#define FRONTIER_MON_HITMONCHAN_1                          234
#define FRONTIER_MON_GIRAFARIG_1                           235
#define FRONTIER_MON_HITMONTOP_1                           236
#define FRONTIER_MON_BANETTE_1                             237
#define FRONTIER_MON_NINJASK_1                             238
#define FRONTIER_MON_SEVIPER_1                             239
#define FRONTIER_MON_ZANGOOSE_1                            240
#define FRONTIER_MON_CAMERUPT_1                            241
#define FRONTIER_MON_SHARPEDO_1                            242
#define FRONTIER_MON_TROPIUS_1                             243
#define FRONTIER_MON_MAGNEZONE_1                           244
#define FRONTIER_MON_MANTINE_1                             245
#define FRONTIER_MON_STANTLER_1                            246
#define FRONTIER_MON_ABSOL_1                               247
#define FRONTIER_MON_SWALOT_1                              248
#define FRONTIER_MON_CRAWDAUNT_1                           249
#define FRONTIER_MON_PIDGEOT_1                             250
#define FRONTIER_MON_GRUMPIG_1                             251
#define FRONTIER_MON_TORKOAL_1                             252
#define FRONTIER_MON_KINGLER_1                             253
#define FRONTIER_MON_CACTURNE_1                            254
#define FRONTIER_MON_BELLOSSOM_1                           255
#define FRONTIER_MON_OCTILLERY_1                           256
#define FRONTIER_MON_HUNTAIL_1                             257
#define FRONTIER_MON_GOREBYSS_1                            258
#define FRONTIER_MON_RELICANTH_1                           259
#define FRONTIER_MON_OMASTAR_1                             260
#define FRONTIER_MON_KABUTOPS_1                            261
#define FRONTIER_MON_POLIWRATH_1                           262
#define FRONTIER_MON_SCYTHER_1                             263
#define FRONTIER_MON_PINSIR_1                              264
#define FRONTIER_MON_POLITOED_1                            265
#define FRONTIER_MON_CLOYSTER_1                            266
#define FRONTIER_MON_ABOMASNOW_1                           267
#define FRONTIER_MON_AVALUGG_1                             268
#define FRONTIER_MON_BEARTIC_1                             269
#define FRONTIER_MON_CARBINK_1                             270
#define FRONTIER_MON_CARRACOSTA_1                          271
#define FRONTIER_MON_CRUSTLE_1                             272
#define FRONTIER_MON_CRYOGONAL_1                           273
#define FRONTIER_MON_CRABOMINABLE_1                        274
#define FRONTIER_MON_LUMINEON_1                            275
#define FRONTIER_MON_SAWSBUCK_1                            276
#define FRONTIER_MON_BASCULIN_1                            277
#define FRONTIER_MON_CARNIVINE_1                           278
#define FRONTIER_MON_STUNFISK_1                            279
#define FRONTIER_MON_PHIONE_1                              280

#define FRONTIER_MON_DELCATTY_2                            281
#define FRONTIER_MON_SABLEYE_2                             282
#define FRONTIER_MON_LICKILICKY_2                          283
#define FRONTIER_MON_FERROTHORN_4                          284
#define FRONTIER_MON_GOLEM_4                               285
#define FRONTIER_MON_CHERRIM_2                             286
#define FRONTIER_MON_AUDINO_2                              287
#define FRONTIER_MON_DARMANITAN_ZEN_2                      288
#define FRONTIER_MON_ROTOM_WASH_4                          289
#define FRONTIER_MON_WHIMSICOTT_2                          290
#define FRONTIER_MON_VOLBEAT_2                             291
#define FRONTIER_MON_ILLUMISE_2                            292
#define FRONTIER_MON_MARACTUS_2                            293
#define FRONTIER_MON_INCINEROAR_4                          294
#define FRONTIER_MON_SAMUROTT_4                            295
#define FRONTIER_MON_PARASECT_2                            296
#define FRONTIER_MON_HITMONLEE_4                           297
#define FRONTIER_MON_AEGISLASH_4                           298
#define FRONTIER_MON_GOGOAT_2                              299
#define FRONTIER_MON_TYPHLOSION_4                          300
#define FRONTIER_MON_GRENINJA_6                            301
#define FRONTIER_MON_RAICHU_4                              302
#define FRONTIER_MON_NOCTOWL_4                             303
#define FRONTIER_MON_WOBBUFFET_2                           304
#define FRONTIER_MON_PLUSLE_2                              305
#define FRONTIER_MON_MINUN_2                               306
#define FRONTIER_MON_LURANTIS_2                            307
#define FRONTIER_MON_INFERNAPE_4                           308
#define FRONTIER_MON_EXCADRILL_3                           309
#define FRONTIER_MON_DARMANITAN_4                          310
#define FRONTIER_MON_AZUMARILL_2                           311
#define FRONTIER_MON_SUDOWOODO_2                           312
#define FRONTIER_MON_MAGCARGO_2                            313
#define FRONTIER_MON_PUPITAR                               314
#define FRONTIER_MON_SEISMITOAD_3                          315
#define FRONTIER_MON_RATICATE_2                            316
#define FRONTIER_MON_MASQUERAIN_2                          317
#define FRONTIER_MON_FURRET_2                              318
#define FRONTIER_MON_DUNSPARCE_2                           319
#define FRONTIER_MON_GOODRA_2                              320
#define FRONTIER_MON_MIGHTYENA_2                           321
#define FRONTIER_MON_LINOONE_2                             322
#define FRONTIER_MON_CASTFORM_2                            323
#define FRONTIER_MON_KOMMO_O_6                             324
#define FRONTIER_MON_METAGROSS_6                           325
#define FRONTIER_MON_WIGGLYTUFF_2                          326
#define FRONTIER_MON_SUNFLORA_2                            327
#define FRONTIER_MON_BUTTERFREE_2                          328
#define FRONTIER_MON_CONKELDURR_6                          329
#define FRONTIER_MON_QWILFISH_2                            330
#define FRONTIER_MON_JELLICENT_4                           331
#define FRONTIER_MON_PELIPPER_2                            332
#define FRONTIER_MON_SWELLOW_2                             333
#define FRONTIER_MON_LYCANROC_MIDNIGHT_4                   334
#define FRONTIER_MON_LILLIGANT_2                           335
#define FRONTIER_MON_ARBOK_2                               336
#define FRONTIER_MON_PERSIAN_2                             337
#define FRONTIER_MON_ARAQUANID_3                           338
#define FRONTIER_MON_KECLEON_2                             339
#define FRONTIER_MON_SCRAFTY_2                             340
#define FRONTIER_MON_LUNATONE_2                            341
#define FRONTIER_MON_SOLROCK_2                             342
#define FRONTIER_MON_NOCTOWL_2                             343
#define FRONTIER_MON_SANDSLASH_2                           344
#define FRONTIER_MON_VENOMOTH_2                            345
#define FRONTIER_MON_BLISSEY_2                             346
#define FRONTIER_MON_SEAKING_2                             347
#define FRONTIER_MON_JUMPLUFF_2                            348
#define FRONTIER_MON_BASTIODON_2                           349
#define FRONTIER_MON_LIEPARD_2                             350
#define FRONTIER_MON_PRIMEAPE_2                            351
#define FRONTIER_MON_HITMONLEE_2                           352
#define FRONTIER_MON_HITMONCHAN_2                          353
#define FRONTIER_MON_GIRAFARIG_2                           354
#define FRONTIER_MON_HITMONTOP_2                           355
#define FRONTIER_MON_BANETTE_2                             356
#define FRONTIER_MON_NINJASK_2                             357
#define FRONTIER_MON_SEVIPER_2                             358
#define FRONTIER_MON_ZANGOOSE_2                            359
#define FRONTIER_MON_CAMERUPT_2                            360
#define FRONTIER_MON_SHARPEDO_2                            361
#define FRONTIER_MON_TROPIUS_2                             362
#define FRONTIER_MON_MAGNEZONE_2                           363
#define FRONTIER_MON_MANTINE_2                             364
#define FRONTIER_MON_STANTLER_2                            365
#define FRONTIER_MON_ABSOL_2                               366
#define FRONTIER_MON_SWALOT_2                              367
#define FRONTIER_MON_CRAWDAUNT_2                           368
#define FRONTIER_MON_PIDGEOT_2                             369
#define FRONTIER_MON_GRUMPIG_2                             370
#define FRONTIER_MON_TORKOAL_2                             371
#define FRONTIER_MON_KINGLER_2                             372
#define FRONTIER_MON_CACTURNE_2                            373
#define FRONTIER_MON_BELLOSSOM_2                           374
#define FRONTIER_MON_OCTILLERY_2                           375
#define FRONTIER_MON_HUNTAIL_2                             376
#define FRONTIER_MON_GOREBYSS_2                            377
#define FRONTIER_MON_RELICANTH_2                           378
#define FRONTIER_MON_OMASTAR_2                             379
#define FRONTIER_MON_KABUTOPS_2                            380
#define FRONTIER_MON_POLIWRATH_2                           381
#define FRONTIER_MON_SCYTHER_2                             382
#define FRONTIER_MON_PINSIR_2                              383
#define FRONTIER_MON_POLITOED_2                            384
#define FRONTIER_MON_CLOYSTER_2                            385
#define FRONTIER_MON_ABOMASNOW_2                           386
#define FRONTIER_MON_AVALUGG_2                             387
#define FRONTIER_MON_BEARTIC_2                             388
#define FRONTIER_MON_CARBINK_2                             389
#define FRONTIER_MON_CARRACOSTA_2                          390
#define FRONTIER_MON_CRUSTLE_2                             391
#define FRONTIER_MON_CRYOGONAL_2                           392
#define FRONTIER_MON_CRABOMINABLE_2                        393
#define FRONTIER_MON_LUMINEON_2                            394
#define FRONTIER_MON_SAWSBUCK_2                            395
#define FRONTIER_MON_BASCULIN_2                            396
#define FRONTIER_MON_CARNIVINE_2                           397
#define FRONTIER_MON_STUNFISK_2                            398
#define FRONTIER_MON_PHIONE_2                              399

#define FRONTIER_MON_BARBARACLE_1                          400
#define FRONTIER_MON_COFAGRIGUS_1                          401
#define FRONTIER_MON_PASSIMIAN_1                           402
#define FRONTIER_MON_ORANGURU_1                            403
#define FRONTIER_MON_DUGTRIO_1                             404
#define FRONTIER_MON_HAWLUCHA_1                            405
#define FRONTIER_MON_MISMAGIUS_1                           406
#define FRONTIER_MON_TALONFLAME_1                          407
#define FRONTIER_MON_GRANBULL_1                            408
#define FRONTIER_MON_FROSLASS_1                            409
#define FRONTIER_MON_DUSKNOIR_1                            410
#define FRONTIER_MON_TOUCANNON_1                           411
#define FRONTIER_MON_MR_MIME_1                             412
#define FRONTIER_MON_ROTOM_FAN_1                           413
#define FRONTIER_MON_BRELOOM_1                             414
#define FRONTIER_MON_VIKAVOLT_1                            415
#define FRONTIER_MON_WHISCASH_1                            416
#define FRONTIER_MON_HONCHKROW_1                           417
#define FRONTIER_MON_SKARMORY_1                            418
#define FRONTIER_MON_RAMPARDOS_1                           419
#define FRONTIER_MON_QUAGSIRE_1                            420
#define FRONTIER_MON_AURORUS_1                             421
#define FRONTIER_MON_HARIYAMA_1                            422
#define FRONTIER_MON_EMOLGA_1                              423
#define FRONTIER_MON_DEWGONG_1                             424
#define FRONTIER_MON_ZEBSTRIKA_1                           425
#define FRONTIER_MON_VILEPLUME_1                           426
#define FRONTIER_MON_ROSERADE_1                            427
#define FRONTIER_MON_ELECTRODE_1                           428
#define FRONTIER_MON_ZOROARK_1                             429
#define FRONTIER_MON_SHIFTRY_1                             430
#define FRONTIER_MON_GLACEON_1                             431
#define FRONTIER_MON_LUDICOLO_1                            432
#define FRONTIER_MON_SPIRITOMB_1                           433
#define FRONTIER_MON_GOLEM_1                               434
#define FRONTIER_MON_LYCANROC_1                            435
#define FRONTIER_MON_ALAKAZAM_1                            436
#define FRONTIER_MON_DRAPION_1                             437
#define FRONTIER_MON_KANGASKHAN_1                          438
#define FRONTIER_MON_EELEKTROSS_1                          439
#define FRONTIER_MON_TAUROS_1                              440
#define FRONTIER_MON_REUNICLUS_1                           441
#define FRONTIER_MON_SLOWKING_1                            442
#define FRONTIER_MON_PORYGON_Z_1                           443
#define FRONTIER_MON_ALTARIA_1                             444
#define FRONTIER_MON_HIPPOWDON_1                           445
#define FRONTIER_MON_NIDOKING_1                            446
#define FRONTIER_MON_GOLURK_1                              447
#define FRONTIER_MON_CRADILY_1                             448
#define FRONTIER_MON_GOLISOPOD_1                           449
#define FRONTIER_MON_GOLDUCK_1                             450
#define FRONTIER_MON_AMBIPOM_1                             451
#define FRONTIER_MON_MUK_1                                 452
#define FRONTIER_MON_CHANDELURE_1                          453
#define FRONTIER_MON_AMPHAROS_1                            454
#define FRONTIER_MON_DURANT_1                              455
#define FRONTIER_MON_HERACROSS_1                           456
#define FRONTIER_MON_LUCARIO_1                             457
#define FRONTIER_MON_HOUNDOOM_1                            458
#define FRONTIER_MON_MUDSDALE_1                            459
#define FRONTIER_MON_CLAYDOL_1                             460
#define FRONTIER_MON_PYUKUMUKU_1                           461
#define FRONTIER_MON_NINETALES_1                           462
#define FRONTIER_MON_CONKELDURR_1                          463
#define FRONTIER_MON_SHUCKLE_1                             464
#define FRONTIER_MON_EXCADRILL_1                           465
#define FRONTIER_MON_TENTACRUEL_1                          466
#define FRONTIER_MON_ARCHEOPS_1                            467
#define FRONTIER_MON_PORYGON2_1                            468
#define FRONTIER_MON_SERPERIOR_1                           469
#define FRONTIER_MON_EXEGGUTOR_1                           470
#define FRONTIER_MON_BLAZIKEN_1                            471
#define FRONTIER_MON_FLYGON_1                              472
#define FRONTIER_MON_TORTERRA_1                            473
#define FRONTIER_MON_VAPOREON_1                            474
#define FRONTIER_MON_LUXRAY_1                              475
#define FRONTIER_MON_FLAREON_1                             476
#define FRONTIER_MON_CHESNAUGHT_1                          477
#define FRONTIER_MON_URSARING_1                            478
#define FRONTIER_MON_BISHARP_1                             479
#define FRONTIER_MON_BLASTOISE_1                           480
#define FRONTIER_MON_SAMUROTT_1                            481
#define FRONTIER_MON_AGGRON_1                              482
#define FRONTIER_MON_DELPHOX_1                             483
#define FRONTIER_MON_WALREIN_1                             484
#define FRONTIER_MON_DECIDUEYE_1                           485
#define FRONTIER_MON_CHARIZARD_1                           486
#define FRONTIER_MON_EMBOAR_1                              487
#define FRONTIER_MON_LAPRAS_1                              488
#define FRONTIER_MON_SALAZZLE_1                            489
#define FRONTIER_MON_SWAMPERT_1                            490
#define FRONTIER_MON_DRAGALGE_1                            491
#define FRONTIER_MON_SNORLAX_1                             492
#define FRONTIER_MON_ARAQUANID_1                           493
#define FRONTIER_MON_CHANSEY_1                             494
#define FRONTIER_MON_ROTOM_WASH_1                          495
#define FRONTIER_MON_ARCANINE_1                            496
#define FRONTIER_MON_GARCHOMP_1                            497
#define FRONTIER_MON_METAGROSS_1                           498
#define FRONTIER_MON_REGIGIGAS_1                           499

#define FRONTIER_MON_BRAVIARY_1                            500
#define FRONTIER_MON_DIGGERSBY_1                           501
#define FRONTIER_MON_DRIFBLIM_1                            502
#define FRONTIER_MON_GOURGEIST_1                           503
#define FRONTIER_MON_GLISCOR_1                             504
#define FRONTIER_MON_MEDICHAM_1                            505
#define FRONTIER_MON_WEAVILE_1                             506
#define FRONTIER_MON_FEAROW_1                              507
#define FRONTIER_MON_SCOLIPEDE_1                           508
#define FRONTIER_MON_JYNX_1                                509
#define FRONTIER_MON_AEGISLASH_1                           510
#define FRONTIER_MON_DODRIO_1                              511
#define FRONTIER_MON_MIMIKYU_1                             512
#define FRONTIER_MON_LANTURN_1                             513
#define FRONTIER_MON_PANGORO_1                             514
#define FRONTIER_MON_FORRETRESS_1                          515
#define FRONTIER_MON_MAMOSWINE_1                           516
#define FRONTIER_MON_XATU_1                                517
#define FRONTIER_MON_STARAPTOR_1                           518
#define FRONTIER_MON_MAROWAK_1                             519
#define FRONTIER_MON_GASTRODON_1                           520
#define FRONTIER_MON_CLEFABLE_1                            521
#define FRONTIER_MON_MIENSHAO_1                            522
#define FRONTIER_MON_RAICHU_1                              523
#define FRONTIER_MON_ROTOM_FROST_1                         524
#define FRONTIER_MON_MANECTRIC_1                           525
#define FRONTIER_MON_TANGROWTH_1                           526
#define FRONTIER_MON_VICTREEBEL_1                          527
#define FRONTIER_MON_ROTOM_MOW_1                           528
#define FRONTIER_MON_EXPLOUD_1                             529
#define FRONTIER_MON_TREVENANT_1                           530
#define FRONTIER_MON_GLALIE_1                              531
#define FRONTIER_MON_LEAFEON_1                             532
#define FRONTIER_MON_HYPNO_1                               533
#define FRONTIER_MON_GIGALITH_1                            534
#define FRONTIER_MON_RHYPERIOR_1                           535
#define FRONTIER_MON_GALLADE_1                             536
#define FRONTIER_MON_WEEZING_1                             537
#define FRONTIER_MON_BEWEAR_1                              538
#define FRONTIER_MON_ELECTIVIRE_1                          539
#define FRONTIER_MON_LOPUNNY_1                             540
#define FRONTIER_MON_SLOWBRO_1                             541
#define FRONTIER_MON_BEHEEYEM_1                            542
#define FRONTIER_MON_MILTANK_1                             543
#define FRONTIER_MON_NOIVERN_1                             544
#define FRONTIER_MON_NIDOQUEEN_1                           545
#define FRONTIER_MON_KROOKODILE_1                          546
#define FRONTIER_MON_MAGMORTAR_1                           547
#define FRONTIER_MON_FERROTHORN_1                          548
#define FRONTIER_MON_ARMALDO_1                             549
#define FRONTIER_MON_CLAWITZER_1                           550
#define FRONTIER_MON_RAPIDASH_1                            551
#define FRONTIER_MON_TOXICROAK_1                           552
#define FRONTIER_MON_GENGAR_1                              553
#define FRONTIER_MON_TOGEDEMARU_1                          554
#define FRONTIER_MON_SCIZOR_1                              555
#define FRONTIER_MON_GALVANTULA_1                          556
#define FRONTIER_MON_ESPEON_1                              557
#define FRONTIER_MON_LYCANROC_MIDNIGHT_1                   558
#define FRONTIER_MON_DONPHAN_1                             559
#define FRONTIER_MON_PALOSSAND_1                           560
#define FRONTIER_MON_WAILORD_1                             561
#define FRONTIER_MON_TURTONATOR_1                          562
#define FRONTIER_MON_MACHAMP_1                             563
#define FRONTIER_MON_LYCANROC_DUSK_1                       564
#define FRONTIER_MON_STEELIX_1                             565
#define FRONTIER_MON_JELLICENT_1                           566
#define FRONTIER_MON_AERODACTYL_1                          567
#define FRONTIER_MON_CINCCINO_1                            568
#define FRONTIER_MON_GARDEVOIR_1                           569
#define FRONTIER_MON_TSAREENA_1                            570
#define FRONTIER_MON_STARMIE_1                             571
#define FRONTIER_MON_HAXORUS_1                             572
#define FRONTIER_MON_VENUSAUR_1                            573
#define FRONTIER_MON_SEISMITOAD_1                          574
#define FRONTIER_MON_JOLTEON_1                             575
#define FRONTIER_MON_DARMANITAN_1                          576
#define FRONTIER_MON_MEGANIUM_1                            577
#define FRONTIER_MON_SYLVEON_1                             578
#define FRONTIER_MON_UMBREON_1                             579
#define FRONTIER_MON_EMPOLEON_1                            580
#define FRONTIER_MON_FERALIGATR_1                          581
#define FRONTIER_MON_TYRANTRUM_1                           582
#define FRONTIER_MON_INCINEROAR_1                          583
#define FRONTIER_MON_VANILLUXE_1                           584
#define FRONTIER_MON_SCEPTILE_1                            585
#define FRONTIER_MON_INFERNAPE_1                           586
#define FRONTIER_MON_TYPHLOSION_1                          587
#define FRONTIER_MON_GRENINJA_1                            588
#define FRONTIER_MON_CROBAT_1                              589
#define FRONTIER_MON_PRIMARINA_1                           590
#define FRONTIER_MON_GYARADOS_1                            591
#define FRONTIER_MON_TOGEKISS_1                            592
#define FRONTIER_MON_KINGDRA_1                             593
#define FRONTIER_MON_TOXAPEX_1                             594
#define FRONTIER_MON_MILOTIC_1                             595
#define FRONTIER_MON_ROTOM_HEAT_1                          596
#define FRONTIER_MON_SALAMENCE_1                           597
#define FRONTIER_MON_KOMMO_O_1                             598
#define FRONTIER_MON_SLAKING_1                             599

#define FRONTIER_MON_BARBARACLE_2                          600
#define FRONTIER_MON_COFAGRIGUS_2                          601
#define FRONTIER_MON_PASSIMIAN_2                           602
#define FRONTIER_MON_ORANGURU_2                            603
#define FRONTIER_MON_DUGTRIO_2                             604
#define FRONTIER_MON_HAWLUCHA_2                            605
#define FRONTIER_MON_MISMAGIUS_2                           606
#define FRONTIER_MON_TALONFLAME_2                          607
#define FRONTIER_MON_GRANBULL_2                            608
#define FRONTIER_MON_FROSLASS_2                            609
#define FRONTIER_MON_DUSKNOIR_2                            610
#define FRONTIER_MON_TOUCANNON_2                           611
#define FRONTIER_MON_MR_MIME_2                             612
#define FRONTIER_MON_ROTOM_FAN_2                           613
#define FRONTIER_MON_BRELOOM_2                             614
#define FRONTIER_MON_VIKAVOLT_2                            615
#define FRONTIER_MON_WHISCASH_2                            616
#define FRONTIER_MON_HONCHKROW_2                           617
#define FRONTIER_MON_SKARMORY_2                            618
#define FRONTIER_MON_RAMPARDOS_2                           619
#define FRONTIER_MON_QUAGSIRE_2                            620
#define FRONTIER_MON_AURORUS_2                             621
#define FRONTIER_MON_HARIYAMA_2                            622
#define FRONTIER_MON_EMOLGA_2                              623
#define FRONTIER_MON_DEWGONG_2                             624
#define FRONTIER_MON_ZEBSTRIKA_2                           625
#define FRONTIER_MON_VILEPLUME_2                           626
#define FRONTIER_MON_ROSERADE_2                            627
#define FRONTIER_MON_ELECTRODE_3                           628
#define FRONTIER_MON_ZOROARK_2                             629
#define FRONTIER_MON_SHIFTRY_2                             630
#define FRONTIER_MON_GLACEON_2                             631
#define FRONTIER_MON_LUDICOLO_2                            632
#define FRONTIER_MON_SPIRITOMB_2                           633
#define FRONTIER_MON_GOLEM_2                               634
#define FRONTIER_MON_LYCANROC_2                            635
#define FRONTIER_MON_ALAKAZAM_2                            636
#define FRONTIER_MON_DRAPION_2                             637
#define FRONTIER_MON_KANGASKHAN_2                          638
#define FRONTIER_MON_EELEKTROSS_2                          639
#define FRONTIER_MON_TAUROS_2                              640
#define FRONTIER_MON_REUNICLUS_2                           641
#define FRONTIER_MON_SLOWKING_2                            642
#define FRONTIER_MON_PORYGON_Z_2                           643
#define FRONTIER_MON_ALTARIA_2                             644
#define FRONTIER_MON_HIPPOWDON_2                           645
#define FRONTIER_MON_NIDOKING_2                            646
#define FRONTIER_MON_GOLURK_2                              647
#define FRONTIER_MON_CRADILY_2                             648
#define FRONTIER_MON_GOLISOPOD_2                           649
#define FRONTIER_MON_GOLDUCK_2                             650
#define FRONTIER_MON_AMBIPOM_2                             651
#define FRONTIER_MON_MUK_2                                 652
#define FRONTIER_MON_CHANDELURE_2                          653
#define FRONTIER_MON_AMPHAROS_2                            654
#define FRONTIER_MON_DURANT_2                              655
#define FRONTIER_MON_HERACROSS_2                           656
#define FRONTIER_MON_LUCARIO_2                             657
#define FRONTIER_MON_HOUNDOOM_2                            658
#define FRONTIER_MON_MUDSDALE_2                            659
#define FRONTIER_MON_CLAYDOL_2                             660
#define FRONTIER_MON_PYUKUMUKU_2                           661
#define FRONTIER_MON_NINETALES_2                           662
#define FRONTIER_MON_CONKELDURR_2                          663
#define FRONTIER_MON_SHUCKLE_2                             664
#define FRONTIER_MON_EXCADRILL_2                           665
#define FRONTIER_MON_TENTACRUEL_2                          666
#define FRONTIER_MON_ARCHEOPS_2                            667
#define FRONTIER_MON_PORYGON2_2                            668
#define FRONTIER_MON_SERPERIOR_2                           669
#define FRONTIER_MON_EXEGGUTOR_2                           670
#define FRONTIER_MON_BLAZIKEN_2                            671
#define FRONTIER_MON_FLYGON_2                              672
#define FRONTIER_MON_TORTERRA_2                            673
#define FRONTIER_MON_VAPOREON_2                            674
#define FRONTIER_MON_LUXRAY_2                              675
#define FRONTIER_MON_FLAREON_2                             676
#define FRONTIER_MON_CHESNAUGHT_2                          677
#define FRONTIER_MON_URSARING_2                            678
#define FRONTIER_MON_BISHARP_2                             679
#define FRONTIER_MON_BLASTOISE_2                           680
#define FRONTIER_MON_SAMUROTT_2                            681
#define FRONTIER_MON_AGGRON_2                              682
#define FRONTIER_MON_DELPHOX_2                             683
#define FRONTIER_MON_WALREIN_2                             684
#define FRONTIER_MON_DECIDUEYE_2                           685
#define FRONTIER_MON_CHARIZARD_2                           686
#define FRONTIER_MON_EMBOAR_2                              687
#define FRONTIER_MON_LAPRAS_2                              688
#define FRONTIER_MON_SALAZZLE_2                            689
#define FRONTIER_MON_SWAMPERT_2                            690
#define FRONTIER_MON_DRAGALGE_2                            691
#define FRONTIER_MON_SNORLAX_2                             692
#define FRONTIER_MON_ARAQUANID_2                           693
#define FRONTIER_MON_CHANSEY_2                             694
#define FRONTIER_MON_ROTOM_WASH_2                          695
#define FRONTIER_MON_ARCANINE_2                            696
#define FRONTIER_MON_GARCHOMP_2                            697
#define FRONTIER_MON_METAGROSS_2                           698
#define FRONTIER_MON_REGIGIGAS_2                           699

#define FRONTIER_MON_BRAVIARY_2                            700
#define FRONTIER_MON_DIGGERSBY_2                           701
#define FRONTIER_MON_DRIFBLIM_2                            702
#define FRONTIER_MON_GOURGEIST_2                           703
#define FRONTIER_MON_GLISCOR_2                             704
#define FRONTIER_MON_MEDICHAM_2                            705
#define FRONTIER_MON_WEAVILE_2                             706
#define FRONTIER_MON_FEAROW_2                              707
#define FRONTIER_MON_SCOLIPEDE_2                           708
#define FRONTIER_MON_JYNX_2                                709
#define FRONTIER_MON_AEGISLASH_2                           710
#define FRONTIER_MON_DODRIO_2                              711
#define FRONTIER_MON_MIMIKYU_2                             712
#define FRONTIER_MON_LANTURN_2                             713
#define FRONTIER_MON_PANGORO_2                             714
#define FRONTIER_MON_FORRETRESS_2                          715
#define FRONTIER_MON_MAMOSWINE_2                           716
#define FRONTIER_MON_XATU_2                                717
#define FRONTIER_MON_STARAPTOR_2                           718
#define FRONTIER_MON_MAROWAK_2                             719
#define FRONTIER_MON_GASTRODON_2                           720
#define FRONTIER_MON_CLEFABLE_2                            721
#define FRONTIER_MON_MIENSHAO_2                            722
#define FRONTIER_MON_RAICHU_2                              723
#define FRONTIER_MON_ROTOM_FROST_2                         724
#define FRONTIER_MON_MANECTRIC_2                           725
#define FRONTIER_MON_TANGROWTH_2                           726
#define FRONTIER_MON_VICTREEBEL_2                          727
#define FRONTIER_MON_ROTOM_MOW_2                           728
#define FRONTIER_MON_EXPLOUD_2                             729
#define FRONTIER_MON_TREVENANT_2                           730
#define FRONTIER_MON_GLALIE_2                              731
#define FRONTIER_MON_LEAFEON_2                             732
#define FRONTIER_MON_HYPNO_2                               733
#define FRONTIER_MON_GIGALITH_2                            734
#define FRONTIER_MON_RHYPERIOR_2                           735
#define FRONTIER_MON_GALLADE_2                             736
#define FRONTIER_MON_WEEZING_2                             737
#define FRONTIER_MON_BEWEAR_2                              738
#define FRONTIER_MON_ELECTIVIRE_2                          739
#define FRONTIER_MON_LOPUNNY_2                             740
#define FRONTIER_MON_SLOWBRO_2                             741
#define FRONTIER_MON_BEHEEYEM_2                            742
#define FRONTIER_MON_MILTANK_2                             743
#define FRONTIER_MON_NOIVERN_2                             744
#define FRONTIER_MON_NIDOQUEEN_2                           745
#define FRONTIER_MON_KROOKODILE_2                          746
#define FRONTIER_MON_MAGMORTAR_2                           747
#define FRONTIER_MON_FERROTHORN_2                          748
#define FRONTIER_MON_ARMALDO_2                             749
#define FRONTIER_MON_CLAWITZER_2                           750
#define FRONTIER_MON_RAPIDASH_2                            751
#define FRONTIER_MON_TOXICROAK_2                           752
#define FRONTIER_MON_GENGAR_2                              753
#define FRONTIER_MON_TOGEDEMARU_2                          754
#define FRONTIER_MON_SCIZOR_2                              755
#define FRONTIER_MON_GALVANTULA_2                          756
#define FRONTIER_MON_ESPEON_2                              757
#define FRONTIER_MON_LYCANROC_MIDNIGHT_2                   758
#define FRONTIER_MON_DONPHAN_2                             759
#define FRONTIER_MON_PALOSSAND_2                           760
#define FRONTIER_MON_WAILORD_2                             761
#define FRONTIER_MON_TURTONATOR_2                          762
#define FRONTIER_MON_MACHAMP_2                             763
#define FRONTIER_MON_LYCANROC_DUSK_2                       764
#define FRONTIER_MON_STEELIX_2                             765
#define FRONTIER_MON_JELLICENT_2                           766
#define FRONTIER_MON_AERODACTYL_2                          767
#define FRONTIER_MON_CINCCINO_2                            768
#define FRONTIER_MON_GARDEVOIR_2                           769
#define FRONTIER_MON_TSAREENA_2                            770
#define FRONTIER_MON_STARMIE_2                             771
#define FRONTIER_MON_HAXORUS_2                             772
#define FRONTIER_MON_VENUSAUR_2                            773
#define FRONTIER_MON_SEISMITOAD_2                          774
#define FRONTIER_MON_JOLTEON_2                             775
#define FRONTIER_MON_DARMANITAN_2                          776
#define FRONTIER_MON_MEGANIUM_2                            777
#define FRONTIER_MON_SYLVEON_2                             778
#define FRONTIER_MON_UMBREON_2                             779
#define FRONTIER_MON_EMPOLEON_2                            780
#define FRONTIER_MON_FERALIGATR_2                          781
#define FRONTIER_MON_TYRANTRUM_2                           782
#define FRONTIER_MON_INCINEROAR_2                          783
#define FRONTIER_MON_VANILLUXE_2                           784
#define FRONTIER_MON_SCEPTILE_2                            785
#define FRONTIER_MON_INFERNAPE_2                           786
#define FRONTIER_MON_TYPHLOSION_2                          787
#define FRONTIER_MON_GRENINJA_2                            788
#define FRONTIER_MON_CROBAT_2                              789
#define FRONTIER_MON_PRIMARINA_2                           790
#define FRONTIER_MON_GYARADOS_2                            791
#define FRONTIER_MON_TOGEKISS_2                            792
#define FRONTIER_MON_KINGDRA_2                             793
#define FRONTIER_MON_TOXAPEX_2                             794
#define FRONTIER_MON_MILOTIC_2                             795
#define FRONTIER_MON_ROTOM_HEAT_2                          796
#define FRONTIER_MON_SALAMENCE_2                           797
#define FRONTIER_MON_KOMMO_O_2                             798
#define FRONTIER_MON_SLAKING_2                             799

#define FRONTIER_MON_COBALION_1                            800
#define FRONTIER_MON_TERRAKION_1                           801
#define FRONTIER_MON_VIRIZION_1                            802
#define FRONTIER_MON_RAIKOU_1                              803
#define FRONTIER_MON_ENTEI_1                               804
#define FRONTIER_MON_SUICUNE_1                             805
#define FRONTIER_MON_HEATRAN_1                             806
#define FRONTIER_MON_REGIROCK_1                            807
#define FRONTIER_MON_REGICE_1                              808
#define FRONTIER_MON_REGISTEEL_1                           809
#define FRONTIER_MON_LATIAS_1                              810
#define FRONTIER_MON_LATIOS_1                              811
#define FRONTIER_MON_COBALION_2                            812
#define FRONTIER_MON_TERRAKION_2                           813
#define FRONTIER_MON_VIRIZION_2                            814
#define FRONTIER_MON_RAIKOU_2                              815
#define FRONTIER_MON_ENTEI_2                               816
#define FRONTIER_MON_SUICUNE_2                             817
#define FRONTIER_MON_HEATRAN_2                             818
#define FRONTIER_MON_REGIROCK_2                            819
#define FRONTIER_MON_REGICE_2                              820
#define FRONTIER_MON_REGISTEEL_2                           821
#define FRONTIER_MON_LATIAS_2                              822
#define FRONTIER_MON_LATIOS_2                              823
#define FRONTIER_MON_COBALION_3                            824
#define FRONTIER_MON_TERRAKION_3                           825
#define FRONTIER_MON_VIRIZION_3                            826
#define FRONTIER_MON_RAIKOU_3                              827
#define FRONTIER_MON_ENTEI_3                               828
#define FRONTIER_MON_SUICUNE_3                             829
#define FRONTIER_MON_HEATRAN_3                             830
#define FRONTIER_MON_REGIROCK_3                            831
#define FRONTIER_MON_REGICE_3                              832
#define FRONTIER_MON_REGISTEEL_3                           833
#define FRONTIER_MON_LATIAS_3                              834
#define FRONTIER_MON_LATIOS_3                              835
#define FRONTIER_MON_COBALION_4                            836
#define FRONTIER_MON_TERRAKION_4                           837
#define FRONTIER_MON_VIRIZION_4                            838
#define FRONTIER_MON_RAIKOU_4                              839
#define FRONTIER_MON_ENTEI_4                               840
#define FRONTIER_MON_SUICUNE_4                             841
#define FRONTIER_MON_HEATRAN_4                             842
#define FRONTIER_MON_REGIROCK_4                            843
#define FRONTIER_MON_REGICE_4                              844
#define FRONTIER_MON_REGISTEEL_4                           845
#define FRONTIER_MON_LATIAS_4                              846
#define FRONTIER_MON_LATIOS_4                              847
#define FRONTIER_MON_GENGAR_3                              848
#define FRONTIER_MON_CHANDELURE_3                          849
#define FRONTIER_MON_GENGAR_4                              850
#define FRONTIER_MON_CHANDELURE_4                          851
#define FRONTIER_MON_ESPEON_3                              852
#define FRONTIER_MON_LUCARIO_3                             853
#define FRONTIER_MON_ESPEON_4                              854
#define FRONTIER_MON_LUCARIO_4                             855
#define FRONTIER_MON_MACHAMP_3                             856
#define FRONTIER_MON_CONKELDURR_3                          857
#define FRONTIER_MON_MACHAMP_4                             858
#define FRONTIER_MON_CONKELDURR_4                          859
#define FRONTIER_MON_GARDEVOIR_3                           860
#define FRONTIER_MON_SERPERIOR_3                           861
#define FRONTIER_MON_GARDEVOIR_4                           862
#define FRONTIER_MON_SERPERIOR_4                           863
#define FRONTIER_MON_STARMIE_3                             864
#define FRONTIER_MON_BLAZIKEN_3                            865
#define FRONTIER_MON_STARMIE_4                             866
#define FRONTIER_MON_BLAZIKEN_4                            867
#define FRONTIER_MON_LAPRAS_3                              868
#define FRONTIER_MON_GRENINJA_3                            869
#define FRONTIER_MON_LAPRAS_4                              870
#define FRONTIER_MON_GRENINJA_4                            871
#define FRONTIER_MON_SNORLAX_3                             872
#define FRONTIER_MON_TOGEKISS_3                            873
#define FRONTIER_MON_SNORLAX_4                             874
#define FRONTIER_MON_TOGEKISS_4                            875
#define FRONTIER_MON_SALAMENCE_3                           876
#define FRONTIER_MON_GARCHOMP_3                            877
#define FRONTIER_MON_SALAMENCE_4                           878
#define FRONTIER_MON_GARCHOMP_4                            879
#define FRONTIER_MON_METAGROSS_3                           880
#define FRONTIER_MON_KOMMO_O_3                             881
#define FRONTIER_MON_METAGROSS_4                           882
#define FRONTIER_MON_KOMMO_O_4                             883
#define FRONTIER_MON_REGIROCK_5                            884
#define FRONTIER_MON_REGIROCK_6                            885
#define FRONTIER_MON_REGICE_5                              886
#define FRONTIER_MON_REGICE_6                              887
#define FRONTIER_MON_REGISTEEL_5                           888
#define FRONTIER_MON_REGISTEEL_6                           889
#define FRONTIER_MON_LATIAS_5                              890
#define FRONTIER_MON_LATIAS_6                              891
#define FRONTIER_MON_LATIAS_7                              892
#define FRONTIER_MON_LATIAS_8                              893
#define FRONTIER_MON_LATIOS_5                              894
#define FRONTIER_MON_LATIOS_6                              895
#define FRONTIER_MON_LATIOS_7                              896
#define FRONTIER_MON_LATIOS_8                              897

// Mons above this point can only appear > level 50
#define FRONTIER_MONS_HIGH_TIER                            897

#define FRONTIER_MON_DRAGONITE_1                           898
#define FRONTIER_MON_DRAGONITE_2                           899
#define FRONTIER_MON_DRAGONITE_3                           900
#define FRONTIER_MON_DRAGONITE_4                           901
#define FRONTIER_MON_GOODRA_3                              902
#define FRONTIER_MON_GOODRA_4                              903
#define FRONTIER_MON_GOODRA_5                              904
#define FRONTIER_MON_GOODRA_6                              905
#define FRONTIER_MON_VOLCARONA_1                           906
#define FRONTIER_MON_VOLCARONA_2                           907
#define FRONTIER_MON_VOLCARONA_3                           908
#define FRONTIER_MON_VOLCARONA_4                           909
#define FRONTIER_MON_HYDREIGON_1                           910
#define FRONTIER_MON_HYDREIGON_2                           911
#define FRONTIER_MON_HYDREIGON_3                           912
#define FRONTIER_MON_HYDREIGON_4                           913
#define FRONTIER_MON_TYRANITAR_1                           914
#define FRONTIER_MON_TYRANITAR_2                           915
#define FRONTIER_MON_TYRANITAR_3                           916
#define FRONTIER_MON_TYRANITAR_4                           917
#define FRONTIER_MON_COBALION_5                            918
#define FRONTIER_MON_TERRAKION_5                           919
#define FRONTIER_MON_VIRIZION_5                            920
#define FRONTIER_MON_KELDEO_1                              921
#define FRONTIER_MON_KELDEO_2                              922
#define FRONTIER_MON_KELDEO_3                              923
#define FRONTIER_MON_RAIKOU_5                              924
#define FRONTIER_MON_RAIKOU_6                              925
#define FRONTIER_MON_ENTEI_5                               926
#define FRONTIER_MON_ENTEI_6                               927
#define FRONTIER_MON_SUICUNE_5                             928
#define FRONTIER_MON_SUICUNE_6                             929
#define FRONTIER_MON_HEATRAN_5                             930
#define FRONTIER_MON_HEATRAN_6                             931


//Custom Frontier Mons

//Trubbish
#define FRONTIER_MON_TRUBBISH                              932
//Megas
#define FRONTIER_MON_MEGA_VENUSAUR_1                       933
#define FRONTIER_MON_MEGA_VENUSAUR_2                       934
#define FRONTIER_MON_MEGA_CHARIZARD_X_1                    935
#define FRONTIER_MON_MEGA_CHARIZARD_X_2                    936
#define FRONTIER_MON_MEGA_CHARIZARD_Y_1                    937
#define FRONTIER_MON_MEGA_CHARIZARD_Y_2                    938
#define FRONTIER_MON_MEGA_BLASTOISE_1                      939
#define FRONTIER_MON_MEGA_BLASTOISE_2                      940
#define FRONTIER_MON_MEGA_BEEDRILL_1                       941
#define FRONTIER_MON_MEGA_BEEDRILL_2                       942
#define FRONTIER_MON_MEGA_PIDGEOT_1                        943
#define FRONTIER_MON_MEGA_PIDGEOT_2                        944
#define FRONTIER_MON_MEGA_ALAKAZAM_1                       945
#define FRONTIER_MON_MEGA_ALAKAZAM_2                       946
#define FRONTIER_MON_MEGA_SLOWBRO_1                        947
#define FRONTIER_MON_MEGA_SLOWBRO_2                        948
#define FRONTIER_MON_MEGA_GENGAR_1                         949
#define FRONTIER_MON_MEGA_GENGAR_2                         950
#define FRONTIER_MON_MEGA_KANGASKHAN_1                     951
#define FRONTIER_MON_MEGA_KANGASKHAN_2                     952
#define FRONTIER_MON_MEGA_PINSIR_1                         953
#define FRONTIER_MON_MEGA_PINSIR_2                         954
#define FRONTIER_MON_MEGA_GYARADOS_1                       955
#define FRONTIER_MON_MEGA_GYARADOS_2                       956
#define FRONTIER_MON_MEGA_AERODACTYL_1                     957
#define FRONTIER_MON_MEGA_AERODACTYL_2                     958
#define FRONTIER_MON_MEGA_MEWTWO_X_1                       959
#define FRONTIER_MON_MEGA_MEWTWO_X_2                       960
#define FRONTIER_MON_MEGA_MEWTWO_Y_1                       961
#define FRONTIER_MON_MEGA_MEWTWO_Y_2                       962
#define FRONTIER_MON_MEGA_AMPHAROS_1                       963
#define FRONTIER_MON_MEGA_AMPHAROS_2                       964
#define FRONTIER_MON_MEGA_STEELIX_1                        965
#define FRONTIER_MON_MEGA_STEELIX_2                        966
#define FRONTIER_MON_MEGA_SCIZOR_1                         967
#define FRONTIER_MON_MEGA_SCIZOR_2                         968
#define FRONTIER_MON_MEGA_HERACROSS_1                      969
#define FRONTIER_MON_MEGA_HERACROSS_2                      970
#define FRONTIER_MON_MEGA_HOUNDOOM_1                       971
#define FRONTIER_MON_MEGA_HOUNDOOM_2                       972
#define FRONTIER_MON_MEGA_TYRANITAR_1                      973
#define FRONTIER_MON_MEGA_TYRANITAR_2                      974
#define FRONTIER_MON_MEGA_SCEPTILE_1                       975
#define FRONTIER_MON_MEGA_SCEPTILE_2                       976
#define FRONTIER_MON_MEGA_BLAZIKEN_1                       977
#define FRONTIER_MON_MEGA_BLAZIKEN_2                       978
#define FRONTIER_MON_MEGA_SWAMPERT_1                       979
#define FRONTIER_MON_MEGA_SWAMPERT_2                       980
#define FRONTIER_MON_MEGA_GARDEVOIR_1                      981
#define FRONTIER_MON_MEGA_GARDEVOIR_2                      982
#define FRONTIER_MON_MEGA_SABLEYE_1                        983
#define FRONTIER_MON_MEGA_SABLEYE_2                        984
#define FRONTIER_MON_MEGA_MAWILE_1                         985
#define FRONTIER_MON_MEGA_MAWILE_2                         986
#define FRONTIER_MON_MEGA_AGGRON_1                         987
#define FRONTIER_MON_MEGA_AGGRON_2                         988
#define FRONTIER_MON_MEGA_MEDICHAM_1                       989
#define FRONTIER_MON_MEGA_MEDICHAM_2                       990
#define FRONTIER_MON_MEGA_MANECTRIC_1                      991
#define FRONTIER_MON_MEGA_MANECTRIC_2                      992
#define FRONTIER_MON_MEGA_SHARPEDO_1                       993
#define FRONTIER_MON_MEGA_SHARPEDO_2                       994
#define FRONTIER_MON_MEGA_CAMERUPT_1                       995
#define FRONTIER_MON_MEGA_CAMERUPT_2                       996
#define FRONTIER_MON_MEGA_ALTARIA_1                        997
#define FRONTIER_MON_MEGA_ALTARIA_2                        998
#define FRONTIER_MON_MEGA_BANETTE_1                        999
#define FRONTIER_MON_MEGA_BANETTE_2                        1000
#define FRONTIER_MON_MEGA_ABSOL_1                          1001
#define FRONTIER_MON_MEGA_ABSOL_2                          1002
#define FRONTIER_MON_MEGA_GLALIE_1                         1003
#define FRONTIER_MON_MEGA_GLALIE_2                         1004
#define FRONTIER_MON_MEGA_SALAMENCE_1                      1005
#define FRONTIER_MON_MEGA_SALAMENCE_2                      1006
#define FRONTIER_MON_MEGA_METAGROSS_1                      1007
#define FRONTIER_MON_MEGA_METAGROSS_2                      1008
#define FRONTIER_MON_MEGA_LATIAS_1                         1009
#define FRONTIER_MON_MEGA_LATIAS_2                         1010
#define FRONTIER_MON_MEGA_LATIOS_1                         1011
#define FRONTIER_MON_MEGA_LATIOS_2                         1012
#define FRONTIER_MON_PRIMAL_GROUDON_1                      1013
#define FRONTIER_MON_PRIMAL_GROUDON_2                      1014
#define FRONTIER_MON_PRIMAL_KYOGRE_1                       1015
#define FRONTIER_MON_PRIMAL_KYOGRE_2                       1016
#define FRONTIER_MON_MEGA_RAYQUAZA_1                       1017
#define FRONTIER_MON_MEGA_RAYQUAZA_2                       1018
#define FRONTIER_MON_MEGA_LOPUNNY_1                        1019
#define FRONTIER_MON_MEGA_LOPUNNY_2                        1020
#define FRONTIER_MON_MEGA_GARCHOMP_1                       1021
#define FRONTIER_MON_MEGA_GARCHOMP_2                       1022
#define FRONTIER_MON_MEGA_LUCARIO_1                        1023
#define FRONTIER_MON_MEGA_LUCARIO_2                        1024
#define FRONTIER_MON_MEGA_ABOMASNOW_1                      1025
#define FRONTIER_MON_MEGA_ABOMASNOW_2                      1026
#define FRONTIER_MON_MEGA_GALLADE_1                        1027
#define FRONTIER_MON_MEGA_GALLADE_2                        1028
#define FRONTIER_MON_MEGA_AUDINO_1                         1029
#define FRONTIER_MON_MEGA_AUDINO_2                         1030
#define FRONTIER_MON_MEGA_DIANCIE_1                        1031
#define FRONTIER_MON_MEGA_DIANCIE_2                        1032
//Frontier starter teams
//Classic
#define FRONTIER_MON_ARIADOS_HYPER_OFFENSE                 1033
#define FRONTIER_MON_TOXICROAK_HYPER_OFFENSE               1034
#define FRONTIER_MON_ZANGOOSE_HYPER_OFFENSE                1035
#define FRONTIER_MON_AURORUS_OFFENSE                       1036
#define FRONTIER_MON_BEARTIC_OFFENSE                       1037
#define FRONTIER_MON_MEGA_GALLADE_OFFENSE                  1038
#define FRONTIER_MON_TYPHLOSION_BALANCE                    1039
#define FRONTIER_MON_FERALIGATR_BALANCE                    1040
#define FRONTIER_MON_VENUSAUR_BALANCE                      1041
#define FRONTIER_MON_SWAMPERT_BULKY_OFFENSE                1042
#define FRONTIER_MON_RHYDON_BULKY_OFFENSE                  1043
#define FRONTIER_MON_MEGANIUM_BULKY_OFFENSE                1044
#define FRONTIER_MON_REGICE_STALL                          1045
#define FRONTIER_MON_SLOWBRO_STALL                         1046
#define FRONTIER_MON_GLISCOR_STALL                         1047
#define FRONTIER_MON_BLANK1_BLANK1                         1048
#define FRONTIER_MON_BLANK2_BLANK1                         1049
#define FRONTIER_MON_BLANK3_BLANK1                         1050
#define FRONTIER_MON_BLANK1_BLANK2                         1051
#define FRONTIER_MON_BLANK2_BLANK2                         1052
#define FRONTIER_MON_BLANK3_BLANK2                         1053
//Field Effects
#define FRONTIER_MON_WALREIN_HAIL                          1054
#define FRONTIER_MON_DEWGONG_HAIL                          1055
#define FRONTIER_MON_RAIKOU_HAIL                           1056
#define FRONTIER_MON_LAPRAS_RAIN                           1057
#define FRONTIER_MON_SEISMITOAD_RAIN                       1058
#define FRONTIER_MON_ROTOM_FAN_RAIN                        1059
#define FRONTIER_MON_MAGCARGO_SUN                          1060
#define FRONTIER_MON_VICTREEBEL_SUN                        1061
#define FRONTIER_MON_MEGA_HOUNDOOM_SUN                     1062
#define FRONTIER_MON_GIGALITH_SANDSTORM                    1063
#define FRONTIER_MON_EXCADRILL_SANDSTORM                   1064
#define FRONTIER_MON_STOUTLAND_SANDSTORM                   1065
#define FRONTIER_MON_ROTOM_MOW_GRASSY_TERRAIN              1066
#define FRONTIER_MON_GOGOAT_GRASSY_TERRAIN                 1067
#define FRONTIER_MON_SEVIPER_GRASSY_TERRAIN                1068
#define FRONTIER_MON_BEHEEYEM_PSYCHIC_TERRAIN              1069
#define FRONTIER_MON_DELPHOX_PSYCHIC_TERRAIN               1070
#define FRONTIER_MON_MEGA_SHARPEDO_PSYCHIC_TERRAIN         1071
#define FRONTIER_MON_OCTILLERY_TRICK_ROOM                  1072
#define FRONTIER_MON_DARMANITAN_ZEN_TRICK_ROOM             1073
#define FRONTIER_MON_RAMPARDOS_TRICK_ROOM                  1074
//Special
#define FRONTIER_MON_JOLTEON_BATON_PASS                    1075
#define FRONTIER_MON_VAPOREON_BATON_PASS                   1076
#define FRONTIER_MON_ESPEON_BATON_PASS                     1077
#define FRONTIER_MON_TOXICROAK_GIMMICK                     1078
#define FRONTIER_MON_TOXAPEX_GIMMICK                       1079
#define FRONTIER_MON_SKARMORY_GIMMICK                      1080
#define FRONTIER_MON_NINJASK_EGGTACTICAL                   1081
#define FRONTIER_MON_SCIZOR_EGGTACTICAL                    1082
#define FRONTIER_MON_UMBREON_EGGTACTICAL                   1083
#define FRONTIER_MON_DELIBIRD_MASOCHIST                    1084
#define FRONTIER_MON_DUNSPARCE_MASOCHIST                   1085
#define FRONTIER_MON_LUVDISC_MASOCHIST                     1086
#define FRONTIER_MON_HIPPOWDON_FEAR                        1087
#define FRONTIER_MON_TOGEDEMARU_FEAR                       1088
#define FRONTIER_MON_MAGNEMITE_FEAR                        1089
#define FRONTIER_MON_BLANK1_BLANK3                         1090
#define FRONTIER_MON_BLANK2_BLANK3                         1091
#define FRONTIER_MON_BLANK3_BLANK3                         1092
#define FRONTIER_MON_BLANK1_BLANK4                         1093
#define FRONTIER_MON_BLANK2_BLANK4                         1094
#define FRONTIER_MON_BLANK3_BLANK4                         1095

#define NUM_FRONTIER_MONS                                  1096

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
