#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MON_LEAFEON_3                             0
#define FRONTIER_MON_AZUMARILL_4                           1
#define FRONTIER_MON_ILLUMISE_3                            2
#define FRONTIER_MON_VOLBEAT_3                             3
#define FRONTIER_MON_DRAPION_3                             4
#define FRONTIER_MON_GALLADE_3                             5
#define FRONTIER_MON_GYARADOS_3                            6
#define FRONTIER_MON_MILOTIC_3                             7
#define FRONTIER_MON_METAPOD                               8
#define FRONTIER_MON_KAKUNA                                9
#define FRONTIER_MON_TOGEDEMARU_3                          10
#define FRONTIER_MON_SILCOON                               11
#define FRONTIER_MON_CASCOON                               12
#define FRONTIER_MON_WHIMSICOTT_3                          13
#define FRONTIER_MON_QUAGSIRE_3                            14
#define FRONTIER_MON_HITMONTOP_3                           15
#define FRONTIER_MON_HAXORUS_3                             16
#define FRONTIER_MON_AMBIPOM_4                             17
#define FRONTIER_MON_GOGOAT_3                              18
#define FRONTIER_MON_LUDICOLO_3                            19
#define FRONTIER_MON_MIGHTYENA_3                           20
#define FRONTIER_MON_SHEDINJA                              21
#define FRONTIER_MON_SCRAFTY_3                             22
#define FRONTIER_MON_PORYGON2_3                            23
#define FRONTIER_MON_LINOONE_3                             24
#define FRONTIER_MON_CROBAT_3                              25
#define FRONTIER_MON_SMEARGLE_1                            26
#define FRONTIER_MON_HERACROSS_3                           27
#define FRONTIER_MON_AZUMARILL_3                           28
#define FRONTIER_MON_SCEPTILE_4                            29
#define FRONTIER_MON_MAGMORTAR_3                           30
#define FRONTIER_MON_MAMOSWINE_3                           31
#define FRONTIER_MON_SMEARGLE_2                            32
#define FRONTIER_MON_GLISCOR_3                             33
#define FRONTIER_MON_RATICATE_3                            34
#define FRONTIER_MON_WOBBUFFET_3                           35
#define FRONTIER_MON_DELCATTY_3                            36
#define FRONTIER_MON_NOIVERN_3                             37
#define FRONTIER_MON_ARCHEOPS_3                            38
#define FRONTIER_MON_YANMEGA_2                             39
#define FRONTIER_MON_SCYTHER_3                             40
#define FRONTIER_MON_SCIZOR_3                              41
#define FRONTIER_MON_GOLISOPOD_3                           42
#define FRONTIER_MON_SKARMORY_3                            43
#define FRONTIER_MON_SWELLOW_3                             44
#define FRONTIER_MON_PIDGEOT_3                             45
#define FRONTIER_MON_NIDOKING_3                            46
#define FRONTIER_MON_NIDOQUEEN_3                           47
#define FRONTIER_MON_SYLVEON_3                             48
#define FRONTIER_MON_LUXRAY_3                              49
#define FRONTIER_MON_AUDINO_3                              50
#define FRONTIER_MON_SLAKING_3                             51
#define FRONTIER_MON_GALVANTULA_3                          52
#define FRONTIER_MON_ARBOK_3                               53
#define FRONTIER_MON_DITTO                                 54
#define FRONTIER_MON_WHISCASH_3                            55
#define FRONTIER_MON_PERSIAN_3                             56
#define FRONTIER_MON_FORRETRESS_3                          57
#define FRONTIER_MON_SHUCKLE_3                             58
#define FRONTIER_MON_VANILLUXE_3                           59
#define FRONTIER_MON_MANTINE_3                             60
#define FRONTIER_MON_DURANT_3                              61
#define FRONTIER_MON_MIMIKYU_3                             62
#define FRONTIER_MON_DUSKNOIR_3                            63
#define FRONTIER_MON_VIKAVOLT_3                            64
#define FRONTIER_MON_NINETALES_3                           65
#define FRONTIER_MON_ROTOM_FROST_3                         66
#define FRONTIER_MON_SANDSLASH_3                           67
#define FRONTIER_MON_POLIWRATH_3                           68
#define FRONTIER_MON_MASQUERAIN_3                          69
#define FRONTIER_MON_RHYPERIOR_3                           70
#define FRONTIER_MON_WAILORD_4                             71
#define FRONTIER_MON_PORYGON_Z_3                           72
#define FRONTIER_MON_OCTILLERY_3                           73
#define FRONTIER_MON_GARCHOMP_5                            74
#define FRONTIER_MON_CLAYDOL_3                             75
#define FRONTIER_MON_AURORUS_3                             76
#define FRONTIER_MON_SALAMENCE_5                           77
#define FRONTIER_MON_ZANGOOSE_3                            78
#define FRONTIER_MON_SEVIPER_3                             79
#define FRONTIER_MON_VENOMOTH_3                            80
#define FRONTIER_MON_PRIMEAPE_3                            81
#define FRONTIER_MON_EMBOAR_3                              82
#define FRONTIER_MON_CLOYSTER_3                            83
#define FRONTIER_MON_JYNX_3                                84
#define FRONTIER_MON_CAMERUPT_3                            85
#define FRONTIER_MON_SHARPEDO_3                            86
#define FRONTIER_MON_CRAWDAUNT_3                           87
#define FRONTIER_MON_CHARIZARD_3                           88
#define FRONTIER_MON_DELPHOX_3                             89
#define FRONTIER_MON_ALAKAZAM_3                            90
#define FRONTIER_MON_DODRIO_3                              91
#define FRONTIER_MON_SCOLIPEDE_3                           92
#define FRONTIER_MON_HAWLUCHA_3                            93
#define FRONTIER_MON_SCEPTILE_3                            94
#define FRONTIER_MON_TALONFLAME_3                          95
#define FRONTIER_MON_WAILORD_3                             96
#define FRONTIER_MON_BLASTOISE_3                           97
#define FRONTIER_MON_FERALIGATR_3                          98
#define FRONTIER_MON_SLOWBRO_3                             99
#define FRONTIER_MON_TORTERRA_3                            100
#define FRONTIER_MON_MEGANIUM_3                            101
#define FRONTIER_MON_VILEPLUME_3                           102
#define FRONTIER_MON_TENTACRUEL_3                          103
#define FRONTIER_MON_MAROWAK_3                             104
#define FRONTIER_MON_SEAKING_3                             105
#define FRONTIER_MON_TROPIUS_3                             106
#define FRONTIER_MON_CLEFABLE_3                            107
#define FRONTIER_MON_MAGNEZONE_3                           108
#define FRONTIER_MON_DEWGONG_3                             109
#define FRONTIER_MON_TOXICROAK_3                           110
#define FRONTIER_MON_KINGLER_3                             111
#define FRONTIER_MON_EXEGGUTOR_3                           112
#define FRONTIER_MON_TOUCANNON_3                           113
#define FRONTIER_MON_CINCCINO_3                            114
#define FRONTIER_MON_ROTOM_FAN_3                           115
#define FRONTIER_MON_EELEKTROSS_3                          116
#define FRONTIER_MON_PELIPPER_3                            117
#define FRONTIER_MON_DELIBIRD                              118
#define FRONTIER_MON_ROTOM_HEAT_3                          119
#define FRONTIER_MON_HIPPOWDON_3                           120
#define FRONTIER_MON_GRUMPIG_3                             121
#define FRONTIER_MON_TYRANTRUM_3                           122
#define FRONTIER_MON_LUVDISC                               123
#define FRONTIER_MON_TOXAPEX_3                             124
#define FRONTIER_MON_CACTURNE_3                            125
#define FRONTIER_MON_UNOWN                                 126
#define FRONTIER_MON_DRAGALGE_3                            127
#define FRONTIER_MON_PRIMARINA_4                           128
#define FRONTIER_MON_LILLIGANT_3                           129
#define FRONTIER_MON_ROTOM_MOW_3                           130
#define FRONTIER_MON_CLAWITZER_3                           131
#define FRONTIER_MON_FLYGON_3                              132
#define FRONTIER_MON_MUDSDALE_3                            133
#define FRONTIER_MON_PRIMARINA_3                           134
#define FRONTIER_MON_STARAPTOR_3                           135
#define FRONTIER_MON_SALAZZLE_3                            136
#define FRONTIER_MON_FARFETCHD                             137
#define FRONTIER_MON_OMASTAR_3                             138
#define FRONTIER_MON_KABUTOPS_3                            139
#define FRONTIER_MON_CRADILY_3                             140
#define FRONTIER_MON_ARMALDO_3                             141
#define FRONTIER_MON_AMBIPOM_3                             142
#define FRONTIER_MON_ELECTIVIRE_3                          143
#define FRONTIER_MON_EXPLOUD_3                             144
#define FRONTIER_MON_SPINDA                                145
#define FRONTIER_MON_ZOROARK_3                             146
#define FRONTIER_MON_ZOROARK_4                             147
#define FRONTIER_MON_AMPHAROS_3                            148
#define FRONTIER_MON_FLAREON_3                             149
#define FRONTIER_MON_PROBOPASS                             150
#define FRONTIER_MON_CORSOLA                               151
#define FRONTIER_MON_MAWILE                                152
#define FRONTIER_MON_BEEDRILL_1                            153
#define FRONTIER_MON_BEEDRILL_2                            154
#define FRONTIER_MON_EMPOLEON_3                            155
#define FRONTIER_MON_STEELIX_3                             156
#define FRONTIER_MON_BEAUTIFLY                             157
#define FRONTIER_MON_DUSTOX                                158
#define FRONTIER_MON_LEDIAN                                159
#define FRONTIER_MON_ARIADOS                               160
#define FRONTIER_MON_YANMEGA_1                             161

#define FRONTIER_MON_DELCATTY_1                            162
#define FRONTIER_MON_SABLEYE_1                             163
#define FRONTIER_MON_LICKILICKY_1                          164
#define FRONTIER_MON_FERROTHORN_3                          165
#define FRONTIER_MON_GOLEM_3                               166
#define FRONTIER_MON_CHERRIM_1                             167
#define FRONTIER_MON_AUDINO_1                              168
#define FRONTIER_MON_DARMANITAN_ZEN_1                      169
#define FRONTIER_MON_ROTOM_WASH_3                          170
#define FRONTIER_MON_WHIMSICOTT_1                          171
#define FRONTIER_MON_VOLBEAT_1                             172
#define FRONTIER_MON_ILLUMISE_1                            173
#define FRONTIER_MON_MARACTUS_1                            174
#define FRONTIER_MON_INCINEROAR_3                          175
#define FRONTIER_MON_SAMUROTT_3                            176
#define FRONTIER_MON_PARASECT_1                            177
#define FRONTIER_MON_HITMONLEE_3                           178
#define FRONTIER_MON_AEGISLASH_3                           179
#define FRONTIER_MON_GOGOAT_1                              180
#define FRONTIER_MON_TYPHLOSION_3                          181
#define FRONTIER_MON_GRENINJA_5                            182
#define FRONTIER_MON_RAICHU_3                              183
#define FRONTIER_MON_NOCTOWL_3                             184
#define FRONTIER_MON_WOBBUFFET_1                           185
#define FRONTIER_MON_PLUSLE_1                              186
#define FRONTIER_MON_MINUN_1                               187
#define FRONTIER_MON_LURANTIS_1                            188
#define FRONTIER_MON_INFERNAPE_3                           189
#define FRONTIER_MON_SWAMPERT_3                            190
#define FRONTIER_MON_DARMANITAN_3                          191
#define FRONTIER_MON_AZUMARILL_1                           192
#define FRONTIER_MON_SUDOWOODO_1                           193
#define FRONTIER_MON_MAGCARGO_1                            194
#define FRONTIER_MON_PANGORO_3                             195
#define FRONTIER_MON_WALREIN_3                             196
#define FRONTIER_MON_RATICATE_1                            197
#define FRONTIER_MON_MASQUERAIN_1                          198
#define FRONTIER_MON_FURRET_1                              199
#define FRONTIER_MON_DUNSPARCE_1                           200
#define FRONTIER_MON_GOODRA_1                              201
#define FRONTIER_MON_MIGHTYENA_1                           202
#define FRONTIER_MON_LINOONE_1                             203
#define FRONTIER_MON_CASTFORM_1                            204
#define FRONTIER_MON_KOMMO_O_5                             205
#define FRONTIER_MON_METAGROSS_5                           206
#define FRONTIER_MON_WIGGLYTUFF_1                          207
#define FRONTIER_MON_SUNFLORA_1                            208
#define FRONTIER_MON_BUTTERFREE_1                          209
#define FRONTIER_MON_CONKELDURR_5                          210
#define FRONTIER_MON_QWILFISH_1                            211
#define FRONTIER_MON_JELLICENT_3                           212
#define FRONTIER_MON_PELIPPER_1                            213
#define FRONTIER_MON_SWELLOW_1                             214
#define FRONTIER_MON_LYCANROC_MIDNIGHT_3                   215
#define FRONTIER_MON_LILLIGANT_1                           216
#define FRONTIER_MON_ARBOK_1                               217
#define FRONTIER_MON_PERSIAN_1                             218
#define FRONTIER_MON_KINGDRA_3                             219
#define FRONTIER_MON_KECLEON_1                             220
#define FRONTIER_MON_SCRAFTY_1                             221
#define FRONTIER_MON_LUNATONE_1                            222
#define FRONTIER_MON_SOLROCK_1                             223
#define FRONTIER_MON_NOCTOWL_1                             224
#define FRONTIER_MON_SANDSLASH_1                           225
#define FRONTIER_MON_VENOMOTH_1                            226
#define FRONTIER_MON_BLISSEY_1                             227
#define FRONTIER_MON_SEAKING_1                             228
#define FRONTIER_MON_JUMPLUFF_1                            229
#define FRONTIER_MON_BASTIODON_1                           230
#define FRONTIER_MON_LIEPARD_1                             231
#define FRONTIER_MON_PRIMEAPE_1                            232
#define FRONTIER_MON_HITMONLEE_1                           233
#define FRONTIER_MON_HITMONCHAN_1                          234
#define FRONTIER_MON_GIRAFARIG_1                           235
#define FRONTIER_MON_HITMONTOP_1                           236
#define FRONTIER_MON_BANETTE_1                             237
#define FRONTIER_MON_NINJASK_1                             238
#define FRONTIER_MON_SEVIPER_1                             239
#define FRONTIER_MON_ZANGOOSE_1                            240
#define FRONTIER_MON_CAMERUPT_1                            241
#define FRONTIER_MON_SHARPEDO_1                            242
#define FRONTIER_MON_TROPIUS_1                             243
#define FRONTIER_MON_MAGNEZONE_1                           244
#define FRONTIER_MON_MANTINE_1                             245
#define FRONTIER_MON_STANTLER_1                            246
#define FRONTIER_MON_ABSOL_1                               247
#define FRONTIER_MON_SWALOT_1                              248
#define FRONTIER_MON_CRAWDAUNT_1                           249
#define FRONTIER_MON_PIDGEOT_1                             250
#define FRONTIER_MON_GRUMPIG_1                             251
#define FRONTIER_MON_TORKOAL_1                             252
#define FRONTIER_MON_KINGLER_1                             253
#define FRONTIER_MON_CACTURNE_1                            254
#define FRONTIER_MON_BELLOSSOM_1                           255
#define FRONTIER_MON_OCTILLERY_1                           256
#define FRONTIER_MON_HUNTAIL_1                             257
#define FRONTIER_MON_GOREBYSS_1                            258
#define FRONTIER_MON_RELICANTH_1                           259
#define FRONTIER_MON_OMASTAR_1                             260
#define FRONTIER_MON_KABUTOPS_1                            261
#define FRONTIER_MON_POLIWRATH_1                           262
#define FRONTIER_MON_SCYTHER_1                             263
#define FRONTIER_MON_PINSIR_1                              264
#define FRONTIER_MON_POLITOED_1                            265
#define FRONTIER_MON_CLOYSTER_1                            266

#define FRONTIER_MON_DELCATTY_2                            267
#define FRONTIER_MON_SABLEYE_2                             268
#define FRONTIER_MON_LICKILICKY_2                          269
#define FRONTIER_MON_FERROTHORN_4                          270
#define FRONTIER_MON_GOLEM_4                               271
#define FRONTIER_MON_CHERRIM_2                             272
#define FRONTIER_MON_AUDINO_2                              273
#define FRONTIER_MON_DARMANITAN_ZEN_2                      274
#define FRONTIER_MON_ROTOM_WASH_4                          275
#define FRONTIER_MON_WHIMSICOTT_2                          276
#define FRONTIER_MON_VOLBEAT_2                             277
#define FRONTIER_MON_ILLUMISE_2                            278
#define FRONTIER_MON_MARACTUS_2                            279
#define FRONTIER_MON_INCINEROAR_4                          280
#define FRONTIER_MON_SAMUROTT_4                            281
#define FRONTIER_MON_PARASECT_2                            282
#define FRONTIER_MON_HITMONLEE_4                           283
#define FRONTIER_MON_AEGISLASH_4                           284
#define FRONTIER_MON_GOGOAT_2                              285
#define FRONTIER_MON_TYPHLOSION_4                          286
#define FRONTIER_MON_GRENINJA_6                            287
#define FRONTIER_MON_RAICHU_4                              288
#define FRONTIER_MON_NOCTOWL_4                             289
#define FRONTIER_MON_WOBBUFFET_2                           290
#define FRONTIER_MON_PLUSLE_2                              291
#define FRONTIER_MON_MINUN_2                               292
#define FRONTIER_MON_LURANTIS_2                            293
#define FRONTIER_MON_INFERNAPE_4                           294
#define FRONTIER_MON_EXCADRILL_3                           295
#define FRONTIER_MON_DARMANITAN_4                          296
#define FRONTIER_MON_AZUMARILL_2                           297
#define FRONTIER_MON_SUDOWOODO_2                           298
#define FRONTIER_MON_MAGCARGO_2                            299
#define FRONTIER_MON_PUPITAR                               300
#define FRONTIER_MON_SEISMITOAD_3                          301
#define FRONTIER_MON_RATICATE_2                            302
#define FRONTIER_MON_MASQUERAIN_2                          303
#define FRONTIER_MON_FURRET_2                              304
#define FRONTIER_MON_DUNSPARCE_2                           305
#define FRONTIER_MON_GOODRA_2                              306
#define FRONTIER_MON_MIGHTYENA_2                           307
#define FRONTIER_MON_LINOONE_2                             308
#define FRONTIER_MON_CASTFORM_2                            309
#define FRONTIER_MON_KOMMO_O_6                             310
#define FRONTIER_MON_METAGROSS_6                           311
#define FRONTIER_MON_WIGGLYTUFF_2                          312
#define FRONTIER_MON_SUNFLORA_2                            313
#define FRONTIER_MON_BUTTERFREE_2                          314
#define FRONTIER_MON_CONKELDURR_6                          315
#define FRONTIER_MON_QWILFISH_2                            316
#define FRONTIER_MON_JELLICENT_4                           317
#define FRONTIER_MON_PELIPPER_2                            318
#define FRONTIER_MON_SWELLOW_2                             319
#define FRONTIER_MON_LYCANROC_MIDNIGHT_4                   320
#define FRONTIER_MON_LILLIGANT_2                           321
#define FRONTIER_MON_ARBOK_2                               322
#define FRONTIER_MON_PERSIAN_2                             323
#define FRONTIER_MON_ARAQUANID_3                           324
#define FRONTIER_MON_KECLEON_2                             325
#define FRONTIER_MON_SCRAFTY_2                             326
#define FRONTIER_MON_LUNATONE_2                            327
#define FRONTIER_MON_SOLROCK_2                             328
#define FRONTIER_MON_NOCTOWL_2                             329
#define FRONTIER_MON_SANDSLASH_2                           330
#define FRONTIER_MON_VENOMOTH_2                            331
#define FRONTIER_MON_BLISSEY_2                             332
#define FRONTIER_MON_SEAKING_2                             333
#define FRONTIER_MON_JUMPLUFF_2                            334
#define FRONTIER_MON_BASTIODON_2                           335
#define FRONTIER_MON_LIEPARD_2                             336
#define FRONTIER_MON_PRIMEAPE_2                            337
#define FRONTIER_MON_HITMONLEE_2                           338
#define FRONTIER_MON_HITMONCHAN_2                          339
#define FRONTIER_MON_GIRAFARIG_2                           340
#define FRONTIER_MON_HITMONTOP_2                           341
#define FRONTIER_MON_BANETTE_2                             342
#define FRONTIER_MON_NINJASK_2                             343
#define FRONTIER_MON_SEVIPER_2                             344
#define FRONTIER_MON_ZANGOOSE_2                            345
#define FRONTIER_MON_CAMERUPT_2                            346
#define FRONTIER_MON_SHARPEDO_2                            347
#define FRONTIER_MON_TROPIUS_2                             348
#define FRONTIER_MON_MAGNEZONE_2                           349
#define FRONTIER_MON_MANTINE_2                             350
#define FRONTIER_MON_STANTLER_2                            351
#define FRONTIER_MON_ABSOL_2                               352
#define FRONTIER_MON_SWALOT_2                              353
#define FRONTIER_MON_CRAWDAUNT_2                           354
#define FRONTIER_MON_PIDGEOT_2                             355
#define FRONTIER_MON_GRUMPIG_2                             356
#define FRONTIER_MON_TORKOAL_2                             357
#define FRONTIER_MON_KINGLER_2                             358
#define FRONTIER_MON_CACTURNE_2                            359
#define FRONTIER_MON_BELLOSSOM_2                           360
#define FRONTIER_MON_OCTILLERY_2                           361
#define FRONTIER_MON_HUNTAIL_2                             362
#define FRONTIER_MON_GOREBYSS_2                            363
#define FRONTIER_MON_RELICANTH_2                           364
#define FRONTIER_MON_OMASTAR_2                             365
#define FRONTIER_MON_KABUTOPS_2                            366
#define FRONTIER_MON_POLIWRATH_2                           367
#define FRONTIER_MON_SCYTHER_2                             368
#define FRONTIER_MON_PINSIR_2                              369
#define FRONTIER_MON_POLITOED_2                            370
#define FRONTIER_MON_CLOYSTER_2                            371

#define FRONTIER_MON_DUGTRIO_1                             372
#define FRONTIER_MON_HAWLUCHA_1                            373
#define FRONTIER_MON_MISMAGIUS_1                           374
#define FRONTIER_MON_TALONFLAME_1                          375
#define FRONTIER_MON_GRANBULL_1                            376
#define FRONTIER_MON_FROSLASS_1                            377
#define FRONTIER_MON_DUSKNOIR_1                            378
#define FRONTIER_MON_TOUCANNON_1                           379
#define FRONTIER_MON_MR_MIME_1                             380
#define FRONTIER_MON_ROTOM_FAN_1                           381
#define FRONTIER_MON_BRELOOM_1                             382
#define FRONTIER_MON_VIKAVOLT_1                            383
#define FRONTIER_MON_WHISCASH_1                            384
#define FRONTIER_MON_HONCHKROW_1                           385
#define FRONTIER_MON_SKARMORY_1                            386
#define FRONTIER_MON_RAMPARDOS_1                           387
#define FRONTIER_MON_QUAGSIRE_1                            388
#define FRONTIER_MON_AURORUS_1                             389
#define FRONTIER_MON_HARIYAMA_1                            390
#define FRONTIER_MON_EMOLGA_1                              391
#define FRONTIER_MON_DEWGONG_1                             392
#define FRONTIER_MON_ZEBSTRIKA_1                           393
#define FRONTIER_MON_VILEPLUME_1                           394
#define FRONTIER_MON_ROSERADE_1                            395
#define FRONTIER_MON_ELECTRODE_1                           396
#define FRONTIER_MON_ZOROARK_1                             397
#define FRONTIER_MON_SHIFTRY_1                             398
#define FRONTIER_MON_GLACEON_1                             399
#define FRONTIER_MON_LUDICOLO_1                            400
#define FRONTIER_MON_SPIRITOMB_1                           401
#define FRONTIER_MON_GOLEM_1                               402
#define FRONTIER_MON_LYCANROC_1                            403
#define FRONTIER_MON_ALAKAZAM_1                            404
#define FRONTIER_MON_DRAPION_1                             405
#define FRONTIER_MON_KANGASKHAN_1                          406
#define FRONTIER_MON_EELEKTROSS_1                          407
#define FRONTIER_MON_TAUROS_1                              408
#define FRONTIER_MON_REUNICLUS_1                           409
#define FRONTIER_MON_SLOWKING_1                            410
#define FRONTIER_MON_PORYGON_Z_1                           411
#define FRONTIER_MON_ALTARIA_1                             412
#define FRONTIER_MON_HIPPOWDON_1                           413
#define FRONTIER_MON_NIDOKING_1                            414
#define FRONTIER_MON_GOLURK_1                              415
#define FRONTIER_MON_CRADILY_1                             416
#define FRONTIER_MON_GOLISOPOD_1                           417
#define FRONTIER_MON_GOLDUCK_1                             418
#define FRONTIER_MON_AMBIPOM_1                             419
#define FRONTIER_MON_MUK_1                                 420
#define FRONTIER_MON_CHANDELURE_1                          421
#define FRONTIER_MON_AMPHAROS_1                            422
#define FRONTIER_MON_DURANT_1                              423
#define FRONTIER_MON_HERACROSS_1                           424
#define FRONTIER_MON_LUCARIO_1                             425
#define FRONTIER_MON_HOUNDOOM_1                            426
#define FRONTIER_MON_MUDSDALE_1                            427
#define FRONTIER_MON_CLAYDOL_1                             428
#define FRONTIER_MON_PYUKUMUKU_1                           429
#define FRONTIER_MON_NINETALES_1                           430
#define FRONTIER_MON_CONKELDURR_1                          431
#define FRONTIER_MON_SHUCKLE_1                             432
#define FRONTIER_MON_EXCADRILL_1                           433
#define FRONTIER_MON_TENTACRUEL_1                          434
#define FRONTIER_MON_ARCHEOPS_1                            435
#define FRONTIER_MON_PORYGON2_1                            436
#define FRONTIER_MON_SERPERIOR_1                           437
#define FRONTIER_MON_EXEGGUTOR_1                           438
#define FRONTIER_MON_BLAZIKEN_1                            439
#define FRONTIER_MON_FLYGON_1                              440
#define FRONTIER_MON_TORTERRA_1                            441
#define FRONTIER_MON_VAPOREON_1                            442
#define FRONTIER_MON_LUXRAY_1                              443
#define FRONTIER_MON_FLAREON_1                             444
#define FRONTIER_MON_CHESNAUGHT_1                          445
#define FRONTIER_MON_ESPEON_1                              446
#define FRONTIER_MON_BISHARP_1                             447
#define FRONTIER_MON_BLASTOISE_1                           448
#define FRONTIER_MON_SAMUROTT_1                            449
#define FRONTIER_MON_AGGRON_1                              450
#define FRONTIER_MON_DELPHOX_1                             451
#define FRONTIER_MON_WALREIN_1                             452
#define FRONTIER_MON_DECIDUEYE_1                           453
#define FRONTIER_MON_CHARIZARD_1                           454
#define FRONTIER_MON_EMBOAR_1                              455
#define FRONTIER_MON_LAPRAS_1                              456
#define FRONTIER_MON_SALAZZLE_1                            457
#define FRONTIER_MON_SWAMPERT_1                            458
#define FRONTIER_MON_DRAGALGE_1                            459
#define FRONTIER_MON_SNORLAX_1                             460
#define FRONTIER_MON_ARAQUANID_1                           461
#define FRONTIER_MON_CHANSEY_1                             462
#define FRONTIER_MON_ROTOM_WASH_1                          463
#define FRONTIER_MON_ARCANINE_1                            464
#define FRONTIER_MON_GARCHOMP_1                            465
#define FRONTIER_MON_METAGROSS_1                           466
#define FRONTIER_MON_REGIGIGAS_1                           467

#define FRONTIER_MON_GLISCOR_1                             468
#define FRONTIER_MON_MEDICHAM_1                            469
#define FRONTIER_MON_WEAVILE_1                             470
#define FRONTIER_MON_FEAROW_1                              471
#define FRONTIER_MON_SCOLIPEDE_1                           472
#define FRONTIER_MON_JYNX_1                                473
#define FRONTIER_MON_AEGISLASH_1                           474
#define FRONTIER_MON_DODRIO_1                              475
#define FRONTIER_MON_MIMIKYU_1                             476
#define FRONTIER_MON_LANTURN_1                             477
#define FRONTIER_MON_PANGORO_1                             478
#define FRONTIER_MON_FORRETRESS_1                          479
#define FRONTIER_MON_MAMOSWINE_1                           480
#define FRONTIER_MON_XATU_1                                481
#define FRONTIER_MON_STARAPTOR_1                           482
#define FRONTIER_MON_MAROWAK_1                             483
#define FRONTIER_MON_GASTRODON_1                           484
#define FRONTIER_MON_CLEFABLE_1                            485
#define FRONTIER_MON_MIENSHAO_1                            486
#define FRONTIER_MON_RAICHU_1                              487
#define FRONTIER_MON_ROTOM_FROST_1                         488
#define FRONTIER_MON_MANECTRIC_1                           489
#define FRONTIER_MON_TANGROWTH_1                           490
#define FRONTIER_MON_VICTREEBEL_1                          491
#define FRONTIER_MON_ROTOM_MOW_1                           492
#define FRONTIER_MON_EXPLOUD_1                             493
#define FRONTIER_MON_TREVENANT_1                           494
#define FRONTIER_MON_GLALIE_1                              495
#define FRONTIER_MON_LEAFEON_1                             496
#define FRONTIER_MON_HYPNO_1                               497
#define FRONTIER_MON_GIGALITH_1                            498
#define FRONTIER_MON_RHYPERIOR_1                           499
#define FRONTIER_MON_GALLADE_1                             500
#define FRONTIER_MON_WEEZING_1                             501
#define FRONTIER_MON_BEWEAR_1                              502
#define FRONTIER_MON_ELECTIVIRE_1                          503
#define FRONTIER_MON_LOPUNNY_1                             504
#define FRONTIER_MON_SLOWBRO_1                             505
#define FRONTIER_MON_BEHEEYEM_1                            506
#define FRONTIER_MON_MILTANK_1                             507
#define FRONTIER_MON_NOIVERN_1                             508
#define FRONTIER_MON_NIDOQUEEN_1                           509
#define FRONTIER_MON_KROOKODILE_1                          510
#define FRONTIER_MON_MAGMORTAR_1                           511
#define FRONTIER_MON_FERROTHORN_1                          512
#define FRONTIER_MON_ARMALDO_1                             513
#define FRONTIER_MON_CLAWITZER_1                           514
#define FRONTIER_MON_RAPIDASH_1                            515
#define FRONTIER_MON_TOXICROAK_1                           516
#define FRONTIER_MON_GENGAR_1                              517
#define FRONTIER_MON_TOGEDEMARU_1                          518
#define FRONTIER_MON_SCIZOR_1                              519
#define FRONTIER_MON_GALVANTULA_1                          520
#define FRONTIER_MON_URSARING_1                            521
#define FRONTIER_MON_LYCANROC_MIDNIGHT_1                   522
#define FRONTIER_MON_DONPHAN_1                             523
#define FRONTIER_MON_PALOSSAND_1                           524
#define FRONTIER_MON_WAILORD_1                             525
#define FRONTIER_MON_TURTONATOR_1                          526
#define FRONTIER_MON_MACHAMP_1                             527
#define FRONTIER_MON_LYCANROC_DUSK_1                       528
#define FRONTIER_MON_STEELIX_1                             529
#define FRONTIER_MON_JELLICENT_1                           530
#define FRONTIER_MON_AERODACTYL_1                          531
#define FRONTIER_MON_CINCCINO_1                            532
#define FRONTIER_MON_GARDEVOIR_1                           533
#define FRONTIER_MON_TSAREENA_1                            534
#define FRONTIER_MON_STARMIE_1                             535
#define FRONTIER_MON_HAXORUS_1                             536
#define FRONTIER_MON_VENUSAUR_1                            537
#define FRONTIER_MON_SEISMITOAD_1                          538
#define FRONTIER_MON_JOLTEON_1                             539
#define FRONTIER_MON_DARMANITAN_1                          540
#define FRONTIER_MON_MEGANIUM_1                            541
#define FRONTIER_MON_SYLVEON_1                             542
#define FRONTIER_MON_UMBREON_1                             543
#define FRONTIER_MON_EMPOLEON_1                            544
#define FRONTIER_MON_FERALIGATR_1                          545
#define FRONTIER_MON_TYRANTRUM_1                           546
#define FRONTIER_MON_INCINEROAR_1                          547
#define FRONTIER_MON_VANILLUXE_1                           548
#define FRONTIER_MON_SCEPTILE_1                            549
#define FRONTIER_MON_INFERNAPE_1                           550
#define FRONTIER_MON_TYPHLOSION_1                          551
#define FRONTIER_MON_GRENINJA_1                            552
#define FRONTIER_MON_CROBAT_1                              553
#define FRONTIER_MON_PRIMARINA_1                           554
#define FRONTIER_MON_GYARADOS_1                            555
#define FRONTIER_MON_TOGEKISS_1                            556
#define FRONTIER_MON_KINGDRA_1                             557
#define FRONTIER_MON_TOXAPEX_1                             558
#define FRONTIER_MON_MILOTIC_1                             559
#define FRONTIER_MON_ROTOM_HEAT_1                          560
#define FRONTIER_MON_SALAMENCE_1                           561
#define FRONTIER_MON_KOMMO_O_1                             562
#define FRONTIER_MON_SLAKING_1                             563

#define FRONTIER_MON_DUGTRIO_2                             564
#define FRONTIER_MON_HAWLUCHA_2                            565
#define FRONTIER_MON_MISMAGIUS_2                           566
#define FRONTIER_MON_TALONFLAME_2                          567
#define FRONTIER_MON_GRANBULL_2                            568
#define FRONTIER_MON_FROSLASS_2                            569
#define FRONTIER_MON_DUSKNOIR_2                            570
#define FRONTIER_MON_TOUCANNON_2                           571
#define FRONTIER_MON_MR_MIME_2                             572
#define FRONTIER_MON_ROTOM_FAN_2                           573
#define FRONTIER_MON_BRELOOM_2                             574
#define FRONTIER_MON_VIKAVOLT_2                            575
#define FRONTIER_MON_WHISCASH_2                            576
#define FRONTIER_MON_HONCHKROW_2                           577
#define FRONTIER_MON_SKARMORY_2                            578
#define FRONTIER_MON_RAMPARDOS_2                           579
#define FRONTIER_MON_QUAGSIRE_2                            580
#define FRONTIER_MON_AURORUS_2                             581
#define FRONTIER_MON_HARIYAMA_2                            582
#define FRONTIER_MON_EMOLGA_2                              583
#define FRONTIER_MON_DEWGONG_2                             584
#define FRONTIER_MON_ZEBSTRIKA_2                           585
#define FRONTIER_MON_VILEPLUME_2                           586
#define FRONTIER_MON_ROSERADE_2                            587
#define FRONTIER_MON_ELECTRODE_3                           588
#define FRONTIER_MON_ZOROARK_2                             589
#define FRONTIER_MON_SHIFTRY_2                             590
#define FRONTIER_MON_GLACEON_2                             591
#define FRONTIER_MON_LUDICOLO_2                            592
#define FRONTIER_MON_SPIRITOMB_2                           593
#define FRONTIER_MON_GOLEM_2                               594
#define FRONTIER_MON_LYCANROC_2                            595
#define FRONTIER_MON_ALAKAZAM_2                            596
#define FRONTIER_MON_DRAPION_2                             597
#define FRONTIER_MON_KANGASKHAN_2                          598
#define FRONTIER_MON_EELEKTROSS_2                          599
#define FRONTIER_MON_TAUROS_2                              600
#define FRONTIER_MON_REUNICLUS_2                           601
#define FRONTIER_MON_SLOWKING_2                            602
#define FRONTIER_MON_PORYGON_Z_2                           603
#define FRONTIER_MON_ALTARIA_2                             604
#define FRONTIER_MON_HIPPOWDON_2                           605
#define FRONTIER_MON_NIDOKING_2                            606
#define FRONTIER_MON_GOLURK_2                              607
#define FRONTIER_MON_CRADILY_2                             608
#define FRONTIER_MON_GOLISOPOD_2                           609
#define FRONTIER_MON_GOLDUCK_2                             610
#define FRONTIER_MON_AMBIPOM_2                             611
#define FRONTIER_MON_MUK_2                                 612
#define FRONTIER_MON_CHANDELURE_2                          613
#define FRONTIER_MON_AMPHAROS_2                            614
#define FRONTIER_MON_DURANT_2                              615
#define FRONTIER_MON_HERACROSS_2                           616
#define FRONTIER_MON_LUCARIO_2                             617
#define FRONTIER_MON_HOUNDOOM_2                            618
#define FRONTIER_MON_MUDSDALE_2                            619
#define FRONTIER_MON_CLAYDOL_2                             620
#define FRONTIER_MON_PYUKUMUKU_2                           621
#define FRONTIER_MON_NINETALES_2                           622
#define FRONTIER_MON_CONKELDURR_2                          623
#define FRONTIER_MON_SHUCKLE_2                             624
#define FRONTIER_MON_EXCADRILL_2                           625
#define FRONTIER_MON_TENTACRUEL_2                          626
#define FRONTIER_MON_ARCHEOPS_2                            627
#define FRONTIER_MON_PORYGON2_2                            628
#define FRONTIER_MON_SERPERIOR_2                           629
#define FRONTIER_MON_EXEGGUTOR_2                           630
#define FRONTIER_MON_BLAZIKEN_2                            631
#define FRONTIER_MON_FLYGON_2                              632
#define FRONTIER_MON_TORTERRA_2                            633
#define FRONTIER_MON_VAPOREON_2                            634
#define FRONTIER_MON_LUXRAY_2                              635
#define FRONTIER_MON_FLAREON_2                             636
#define FRONTIER_MON_CHESNAUGHT_2                          637
#define FRONTIER_MON_ESPEON_2                              638
#define FRONTIER_MON_BISHARP_2                             639
#define FRONTIER_MON_BLASTOISE_2                           640
#define FRONTIER_MON_SAMUROTT_2                            641
#define FRONTIER_MON_AGGRON_2                              642
#define FRONTIER_MON_DELPHOX_2                             643
#define FRONTIER_MON_WALREIN_2                             644
#define FRONTIER_MON_DECIDUEYE_2                           645
#define FRONTIER_MON_CHARIZARD_2                           646
#define FRONTIER_MON_EMBOAR_2                              647
#define FRONTIER_MON_LAPRAS_2                              648
#define FRONTIER_MON_SALAZZLE_2                            649
#define FRONTIER_MON_SWAMPERT_2                            650
#define FRONTIER_MON_DRAGALGE_2                            651
#define FRONTIER_MON_SNORLAX_2                             652
#define FRONTIER_MON_ARAQUANID_2                           653
#define FRONTIER_MON_CHANSEY_2                             654
#define FRONTIER_MON_ROTOM_WASH_2                          655
#define FRONTIER_MON_ARCANINE_2                            656
#define FRONTIER_MON_GARCHOMP_2                            657
#define FRONTIER_MON_METAGROSS_2                           658
#define FRONTIER_MON_REGIGIGAS_2                           659

#define FRONTIER_MON_GLISCOR_2                             660
#define FRONTIER_MON_MEDICHAM_2                            661
#define FRONTIER_MON_WEAVILE_2                             662
#define FRONTIER_MON_FEAROW_2                              663
#define FRONTIER_MON_SCOLIPEDE_2                           664
#define FRONTIER_MON_JYNX_2                                665
#define FRONTIER_MON_AEGISLASH_2                           666
#define FRONTIER_MON_DODRIO_2                              667
#define FRONTIER_MON_MIMIKYU_2                             668
#define FRONTIER_MON_LANTURN_2                             669
#define FRONTIER_MON_PANGORO_2                             670
#define FRONTIER_MON_FORRETRESS_2                          671
#define FRONTIER_MON_MAMOSWINE_2                           672
#define FRONTIER_MON_XATU_2                                673
#define FRONTIER_MON_STARAPTOR_2                           674
#define FRONTIER_MON_MAROWAK_2                             675
#define FRONTIER_MON_GASTRODON_2                           676
#define FRONTIER_MON_CLEFABLE_2                            677
#define FRONTIER_MON_MIENSHAO_2                            678
#define FRONTIER_MON_RAICHU_2                              679
#define FRONTIER_MON_ROTOM_FROST_2                         680
#define FRONTIER_MON_MANECTRIC_2                           681
#define FRONTIER_MON_TANGROWTH_2                           682
#define FRONTIER_MON_VICTREEBEL_2                          683
#define FRONTIER_MON_ROTOM_MOW_2                           684
#define FRONTIER_MON_EXPLOUD_2                             685
#define FRONTIER_MON_TREVENANT_2                           686
#define FRONTIER_MON_GLALIE_2                              687
#define FRONTIER_MON_LEAFEON_2                             688
#define FRONTIER_MON_HYPNO_2                               689
#define FRONTIER_MON_GIGALITH_2                            690
#define FRONTIER_MON_RHYPERIOR_2                           691
#define FRONTIER_MON_GALLADE_2                             692
#define FRONTIER_MON_WEEZING_2                             693
#define FRONTIER_MON_BEWEAR_2                              694
#define FRONTIER_MON_ELECTIVIRE_2                          695
#define FRONTIER_MON_LOPUNNY_2                             696
#define FRONTIER_MON_SLOWBRO_2                             697
#define FRONTIER_MON_BEHEEYEM_2                            698
#define FRONTIER_MON_MILTANK_2                             699
#define FRONTIER_MON_NOIVERN_2                             700
#define FRONTIER_MON_NIDOQUEEN_2                           701
#define FRONTIER_MON_KROOKODILE_2                          702
#define FRONTIER_MON_MAGMORTAR_2                           703
#define FRONTIER_MON_FERROTHORN_2                          704
#define FRONTIER_MON_ARMALDO_2                             705
#define FRONTIER_MON_CLAWITZER_2                           706
#define FRONTIER_MON_RAPIDASH_2                            707
#define FRONTIER_MON_TOXICROAK_2                           708
#define FRONTIER_MON_GENGAR_2                              709
#define FRONTIER_MON_TOGEDEMARU_2                          710
#define FRONTIER_MON_SCIZOR_2                              711
#define FRONTIER_MON_GALVANTULA_2                          712
#define FRONTIER_MON_URSARING_2                            713
#define FRONTIER_MON_LYCANROC_MIDNIGHT_2                   714
#define FRONTIER_MON_DONPHAN_2                             715
#define FRONTIER_MON_PALOSSAND_2                           716
#define FRONTIER_MON_WAILORD_2                             717
#define FRONTIER_MON_TURTONATOR_2                          718
#define FRONTIER_MON_MACHAMP_2                             719
#define FRONTIER_MON_LYCANROC_DUSK_2                       720
#define FRONTIER_MON_STEELIX_2                             721
#define FRONTIER_MON_JELLICENT_2                           722
#define FRONTIER_MON_AERODACTYL_2                          723
#define FRONTIER_MON_CINCCINO_2                            724
#define FRONTIER_MON_GARDEVOIR_2                           725
#define FRONTIER_MON_TSAREENA_2                            726
#define FRONTIER_MON_STARMIE_2                             727
#define FRONTIER_MON_HAXORUS_2                             728
#define FRONTIER_MON_VENUSAUR_2                            729
#define FRONTIER_MON_SEISMITOAD_2                          730
#define FRONTIER_MON_JOLTEON_2                             731
#define FRONTIER_MON_DARMANITAN_2                          732
#define FRONTIER_MON_MEGANIUM_2                            733
#define FRONTIER_MON_SYLVEON_2                             734
#define FRONTIER_MON_UMBREON_2                             735
#define FRONTIER_MON_EMPOLEON_2                            736
#define FRONTIER_MON_FERALIGATR_2                          737
#define FRONTIER_MON_TYRANTRUM_2                           738
#define FRONTIER_MON_INCINEROAR_2                          739
#define FRONTIER_MON_VANILLUXE_2                           740
#define FRONTIER_MON_SCEPTILE_2                            741
#define FRONTIER_MON_INFERNAPE_2                           742
#define FRONTIER_MON_TYPHLOSION_2                          743
#define FRONTIER_MON_GRENINJA_2                            744
#define FRONTIER_MON_CROBAT_2                              745
#define FRONTIER_MON_PRIMARINA_2                           746
#define FRONTIER_MON_GYARADOS_2                            747
#define FRONTIER_MON_TOGEKISS_2                            748
#define FRONTIER_MON_KINGDRA_2                             749
#define FRONTIER_MON_TOXAPEX_2                             750
#define FRONTIER_MON_MILOTIC_2                             751
#define FRONTIER_MON_ROTOM_HEAT_2                          752
#define FRONTIER_MON_SALAMENCE_2                           753
#define FRONTIER_MON_KOMMO_O_2                             754
#define FRONTIER_MON_SLAKING_2                             755

#define FRONTIER_MON_COBALION_1                            756
#define FRONTIER_MON_TERRAKION_1                           757
#define FRONTIER_MON_VIRIZION_1                            758
#define FRONTIER_MON_RAIKOU_1                              759
#define FRONTIER_MON_ENTEI_1                               760
#define FRONTIER_MON_SUICUNE_1                             761
#define FRONTIER_MON_REGIROCK_1                            762
#define FRONTIER_MON_REGICE_1                              763
#define FRONTIER_MON_REGISTEEL_1                           764
#define FRONTIER_MON_LATIAS_1                              765
#define FRONTIER_MON_LATIOS_1                              766
#define FRONTIER_MON_COBALION_2                            767
#define FRONTIER_MON_TERRAKION_2                           768
#define FRONTIER_MON_VIRIZION_2                            769
#define FRONTIER_MON_RAIKOU_2                              770
#define FRONTIER_MON_ENTEI_2                               771
#define FRONTIER_MON_SUICUNE_2                             772
#define FRONTIER_MON_REGIROCK_2                            773
#define FRONTIER_MON_REGICE_2                              774
#define FRONTIER_MON_REGISTEEL_2                           775
#define FRONTIER_MON_LATIAS_2                              776
#define FRONTIER_MON_LATIOS_2                              777
#define FRONTIER_MON_COBALION_3                            778
#define FRONTIER_MON_TERRAKION_3                           779
#define FRONTIER_MON_VIRIZION_3                            780
#define FRONTIER_MON_RAIKOU_3                              781
#define FRONTIER_MON_ENTEI_3                               782
#define FRONTIER_MON_SUICUNE_3                             783
#define FRONTIER_MON_REGIROCK_3                            784
#define FRONTIER_MON_REGICE_3                              785
#define FRONTIER_MON_REGISTEEL_3                           786
#define FRONTIER_MON_LATIAS_3                              787
#define FRONTIER_MON_LATIOS_3                              788
#define FRONTIER_MON_COBALION_4                            789
#define FRONTIER_MON_TERRAKION_4                           790
#define FRONTIER_MON_VIRIZION_4                            791
#define FRONTIER_MON_RAIKOU_4                              792
#define FRONTIER_MON_ENTEI_4                               793
#define FRONTIER_MON_SUICUNE_4                             794
#define FRONTIER_MON_REGIROCK_4                            795
#define FRONTIER_MON_REGICE_4                              796
#define FRONTIER_MON_REGISTEEL_4                           797
#define FRONTIER_MON_LATIAS_4                              798
#define FRONTIER_MON_LATIOS_4                              799
#define FRONTIER_MON_GENGAR_3                              800
#define FRONTIER_MON_CHANDELURE_3                          801
#define FRONTIER_MON_GENGAR_4                              802
#define FRONTIER_MON_CHANDELURE_4                          803
#define FRONTIER_MON_URSARING_3                            804
#define FRONTIER_MON_LUCARIO_3                             805
#define FRONTIER_MON_URSARING_4                            806
#define FRONTIER_MON_LUCARIO_4                             807
#define FRONTIER_MON_MACHAMP_3                             808
#define FRONTIER_MON_CONKELDURR_3                          809
#define FRONTIER_MON_MACHAMP_4                             810
#define FRONTIER_MON_CONKELDURR_4                          811
#define FRONTIER_MON_GARDEVOIR_3                           812
#define FRONTIER_MON_SERPERIOR_3                           813
#define FRONTIER_MON_GARDEVOIR_4                           814
#define FRONTIER_MON_SERPERIOR_4                           815
#define FRONTIER_MON_STARMIE_3                             816
#define FRONTIER_MON_BLAZIKEN_3                            817
#define FRONTIER_MON_STARMIE_4                             818
#define FRONTIER_MON_BLAZIKEN_4                            819
#define FRONTIER_MON_LAPRAS_3                              820
#define FRONTIER_MON_GRENINJA_3                            821
#define FRONTIER_MON_LAPRAS_4                              822
#define FRONTIER_MON_GRENINJA_4                            823
#define FRONTIER_MON_SNORLAX_3                             824
#define FRONTIER_MON_TOGEKISS_3                            825
#define FRONTIER_MON_SNORLAX_4                             826
#define FRONTIER_MON_TOGEKISS_4                            827
#define FRONTIER_MON_SALAMENCE_3                           828
#define FRONTIER_MON_GARCHOMP_3                            829
#define FRONTIER_MON_SALAMENCE_4                           830
#define FRONTIER_MON_GARCHOMP_4                            831
#define FRONTIER_MON_METAGROSS_3                           832
#define FRONTIER_MON_KOMMO_O_3                             833
#define FRONTIER_MON_METAGROSS_4                           834
#define FRONTIER_MON_KOMMO_O_4                             835
#define FRONTIER_MON_REGIROCK_5                            836
#define FRONTIER_MON_REGIROCK_6                            837
#define FRONTIER_MON_REGICE_5                              838
#define FRONTIER_MON_REGICE_6                              839
#define FRONTIER_MON_REGISTEEL_5                           840
#define FRONTIER_MON_REGISTEEL_6                           841
#define FRONTIER_MON_LATIAS_5                              842
#define FRONTIER_MON_LATIAS_6                              843
#define FRONTIER_MON_LATIAS_7                              844
#define FRONTIER_MON_LATIAS_8                              845
#define FRONTIER_MON_LATIOS_5                              846
#define FRONTIER_MON_LATIOS_6                              847
#define FRONTIER_MON_LATIOS_7                              848
#define FRONTIER_MON_LATIOS_8                              849

// Mons above this point can only appear > level 50
#define FRONTIER_MONS_HIGH_TIER                            849

#define FRONTIER_MON_DRAGONITE_1                           850
#define FRONTIER_MON_DRAGONITE_2                           851
#define FRONTIER_MON_DRAGONITE_3                           852
#define FRONTIER_MON_DRAGONITE_4                           853
// does it really make sense for Goodra to be in the high tier list?
#define FRONTIER_MON_GOODRA_3                              854
#define FRONTIER_MON_GOODRA_4                              855
#define FRONTIER_MON_GOODRA_5                              856
#define FRONTIER_MON_GOODRA_6                              857
#define FRONTIER_MON_VOLCARONA_1                           858
#define FRONTIER_MON_VOLCARONA_2                           859
#define FRONTIER_MON_VOLCARONA_3                           860
#define FRONTIER_MON_VOLCARONA_4                           861
#define FRONTIER_MON_HYDREIGON_1                           862
#define FRONTIER_MON_HYDREIGON_2                           863
#define FRONTIER_MON_HYDREIGON_3                           864
#define FRONTIER_MON_HYDREIGON_4                           865
#define FRONTIER_MON_TYRANITAR_1                           866
#define FRONTIER_MON_TYRANITAR_2                           867
#define FRONTIER_MON_TYRANITAR_3                           868
#define FRONTIER_MON_TYRANITAR_4                           869
#define FRONTIER_MON_COBALION_5                            870
#define FRONTIER_MON_TERRAKION_5                           871
#define FRONTIER_MON_VIRIZION_5                            872
#define FRONTIER_MON_KELDEO_1                              873
#define FRONTIER_MON_KELDEO_2                              874
#define FRONTIER_MON_KELDEO_3                              875
#define FRONTIER_MON_RAIKOU_5                              876
#define FRONTIER_MON_RAIKOU_6                              877
#define FRONTIER_MON_ENTEI_5                               878
#define FRONTIER_MON_ENTEI_6                               879
#define FRONTIER_MON_SUICUNE_5                             880
#define FRONTIER_MON_SUICUNE_6                             881


//Custom Frontier Mons

//Trubbish
#define FRONTIER_MON_TRUBBISH                              882
//Megas
#define FRONTIER_MON_MEGA_VENUSAUR_1                       883
#define FRONTIER_MON_MEGA_VENUSAUR_2                       884
#define FRONTIER_MON_MEGA_CHARIZARD_X_1                    885
#define FRONTIER_MON_MEGA_CHARIZARD_X_2                    886
#define FRONTIER_MON_MEGA_CHARIZARD_Y_1                    887
#define FRONTIER_MON_MEGA_CHARIZARD_Y_2                    888
#define FRONTIER_MON_MEGA_BLASTOISE_1                      889
#define FRONTIER_MON_MEGA_BLASTOISE_2                      890
#define FRONTIER_MON_MEGA_BEEDRILL_1                       891
#define FRONTIER_MON_MEGA_BEEDRILL_2                       892
#define FRONTIER_MON_MEGA_PIDGEOT_1                        893
#define FRONTIER_MON_MEGA_PIDGEOT_2                        894
#define FRONTIER_MON_MEGA_ALAKAZAM_1                       895
#define FRONTIER_MON_MEGA_ALAKAZAM_2                       896
#define FRONTIER_MON_MEGA_SLOWBRO_1                        897
#define FRONTIER_MON_MEGA_SLOWBRO_2                        898
#define FRONTIER_MON_MEGA_GENGAR_1                         899
#define FRONTIER_MON_MEGA_GENGAR_2                         900
#define FRONTIER_MON_MEGA_KANGASKHAN_1                     901
#define FRONTIER_MON_MEGA_KANGASKHAN_2                     902
#define FRONTIER_MON_MEGA_PINSIR_1                         903
#define FRONTIER_MON_MEGA_PINSIR_2                         904
#define FRONTIER_MON_MEGA_GYARADOS_1                       905
#define FRONTIER_MON_MEGA_GYARADOS_2                       906
#define FRONTIER_MON_MEGA_AERODACTYL_1                     907
#define FRONTIER_MON_MEGA_AERODACTYL_2                     908
#define FRONTIER_MON_MEGA_MEWTWO_X_1                       909
#define FRONTIER_MON_MEGA_MEWTWO_X_2                       910
#define FRONTIER_MON_MEGA_MEWTWO_Y_1                       911
#define FRONTIER_MON_MEGA_MEWTWO_Y_2                       912
#define FRONTIER_MON_MEGA_AMPHAROS_1                       913
#define FRONTIER_MON_MEGA_AMPHAROS_2                       914
#define FRONTIER_MON_MEGA_STEELIX_1                        915
#define FRONTIER_MON_MEGA_STEELIX_2                        916
#define FRONTIER_MON_MEGA_SCIZOR_1                         917
#define FRONTIER_MON_MEGA_SCIZOR_2                         918
#define FRONTIER_MON_MEGA_HERACROSS_1                      919
#define FRONTIER_MON_MEGA_HERACROSS_2                      920
#define FRONTIER_MON_MEGA_HOUNDOOM_1                       921
#define FRONTIER_MON_MEGA_HOUNDOOM_2                       922
#define FRONTIER_MON_MEGA_TYRANITAR_1                      923
#define FRONTIER_MON_MEGA_TYRANITAR_2                      924
#define FRONTIER_MON_MEGA_SCEPTILE_1                       925
#define FRONTIER_MON_MEGA_SCEPTILE_2                       926
#define FRONTIER_MON_MEGA_BLAZIKEN_1                       927
#define FRONTIER_MON_MEGA_BLAZIKEN_2                       928
#define FRONTIER_MON_MEGA_SWAMPERT_1                       929
#define FRONTIER_MON_MEGA_SWAMPERT_2                       930
#define FRONTIER_MON_MEGA_GARDEVOIR_1                      931
#define FRONTIER_MON_MEGA_GARDEVOIR_2                      932
#define FRONTIER_MON_MEGA_SABLEYE_1                        933
#define FRONTIER_MON_MEGA_SABLEYE_2                        934
#define FRONTIER_MON_MEGA_MAWILE_1                         935
#define FRONTIER_MON_MEGA_MAWILE_2                         936
#define FRONTIER_MON_MEGA_AGGRON_1                         937
#define FRONTIER_MON_MEGA_AGGRON_2                         938
#define FRONTIER_MON_MEGA_MEDICHAM_1                       939
#define FRONTIER_MON_MEGA_MEDICHAM_2                       940
#define FRONTIER_MON_MEGA_MANECTRIC_1                      941
#define FRONTIER_MON_MEGA_MANECTRIC_2                      942
#define FRONTIER_MON_MEGA_SHARPEDO_1                       943
#define FRONTIER_MON_MEGA_SHARPEDO_2                       944
#define FRONTIER_MON_MEGA_CAMERUPT_1                       945
#define FRONTIER_MON_MEGA_CAMERUPT_2                       946
#define FRONTIER_MON_MEGA_ALTARIA_1                        947
#define FRONTIER_MON_MEGA_ALTARIA_2                        948
#define FRONTIER_MON_MEGA_BANETTE_1                        949
#define FRONTIER_MON_MEGA_BANETTE_2                        950
#define FRONTIER_MON_MEGA_ABSOL_1                          951
#define FRONTIER_MON_MEGA_ABSOL_2                          952
#define FRONTIER_MON_MEGA_GLALIE_1                         953
#define FRONTIER_MON_MEGA_GLALIE_2                         954
#define FRONTIER_MON_MEGA_SALAMENCE_1                      955
#define FRONTIER_MON_MEGA_SALAMENCE_2                      956
#define FRONTIER_MON_MEGA_METAGROSS_1                      957
#define FRONTIER_MON_MEGA_METAGROSS_2                      958
#define FRONTIER_MON_MEGA_LATIAS_1                         959
#define FRONTIER_MON_MEGA_LATIAS_2                         960
#define FRONTIER_MON_MEGA_LATIOS_1                         961
#define FRONTIER_MON_MEGA_LATIOS_2                         962
#define FRONTIER_MON_PRIMAL_GROUDON_1                      963
#define FRONTIER_MON_PRIMAL_GROUDON_2                      964
#define FRONTIER_MON_PRIMAL_KYOGRE_1                       965
#define FRONTIER_MON_PRIMAL_KYOGRE_2                       966
#define FRONTIER_MON_MEGA_RAYQUAZA_1                       967
#define FRONTIER_MON_MEGA_RAYQUAZA_2                       968
#define FRONTIER_MON_MEGA_LOPUNNY_1                        969
#define FRONTIER_MON_MEGA_LOPUNNY_2                        970
#define FRONTIER_MON_MEGA_GARCHOMP_1                       971
#define FRONTIER_MON_MEGA_GARCHOMP_2                       972
#define FRONTIER_MON_MEGA_LUCARIO_1                        973
#define FRONTIER_MON_MEGA_LUCARIO_2                        974
#define FRONTIER_MON_MEGA_ABOMASNOW_1                      975
#define FRONTIER_MON_MEGA_ABOMASNOW_2                      976
#define FRONTIER_MON_MEGA_GALLADE_1                        977
#define FRONTIER_MON_MEGA_GALLADE_2                        978
#define FRONTIER_MON_MEGA_AUDINO_1                         979
#define FRONTIER_MON_MEGA_AUDINO_2                         980
#define FRONTIER_MON_MEGA_DIANCIE_1                        981
#define FRONTIER_MON_MEGA_DIANCIE_2                        982
//Frontier starter teams
//Classic
#define FRONTIER_MON_ARIADOS_HYPER_OFFENSE                 983
#define FRONTIER_MON_TOXICROAK_HYPER_OFFENSE               984
#define FRONTIER_MON_ZANGOOSE_HYPER_OFFENSE                985
#define FRONTIER_MON_AURORUS_OFFENSE                       986
#define FRONTIER_MON_BEARTIC_OFFENSE                       987
#define FRONTIER_MON_MEGA_GALLADE_OFFENSE                  988
#define FRONTIER_MON_TYPHLOSION_BALANCE                    989
#define FRONTIER_MON_FERALIGATR_BALANCE                    990
#define FRONTIER_MON_VENUSAUR_BALANCE                      991
#define FRONTIER_MON_SWAMPERT_BULKY_OFFENSE                992
#define FRONTIER_MON_RHYDON_BULKY_OFFENSE                  993
#define FRONTIER_MON_MEGANIUM_BULKY_OFFENSE                994
#define FRONTIER_MON_REGICE_STALL                          995
#define FRONTIER_MON_SLOWBRO_STALL                         996
#define FRONTIER_MON_GLISCOR_STALL                         997
#define FRONTIER_MON_BLANK1_BLANK1                         998
#define FRONTIER_MON_BLANK2_BLANK1                         999
#define FRONTIER_MON_BLANK3_BLANK1                         1000
#define FRONTIER_MON_BLANK1_BLANK2                         1001
#define FRONTIER_MON_BLANK2_BLANK2                         1002
#define FRONTIER_MON_BLANK3_BLANK2                         1003
//Field Effects
#define FRONTIER_MON_WALREIN_HAIL                          1004
#define FRONTIER_MON_DEWGONG_HAIL                          1005
#define FRONTIER_MON_RAIKOU_HAIL                           1006
#define FRONTIER_MON_LAPRAS_RAIN                           1007
#define FRONTIER_MON_SEISMITOAD_RAIN                       1008
#define FRONTIER_MON_ROTOM_FAN_RAIN                        1009
#define FRONTIER_MON_MAGCARGO_SUN                          1010
#define FRONTIER_MON_VICTREEBEL_SUN                        1011
#define FRONTIER_MON_MEGA_HOUNDOOM_SUN                     1012
#define FRONTIER_MON_GIGALITH_SANDSTORM                    1013
#define FRONTIER_MON_EXCADRILL_SANDSTORM                   1014
#define FRONTIER_MON_STOUTLAND_SANDSTORM                   1015
#define FRONTIER_MON_ROTOM_MOW_GRASSY_TERRAIN              1016
#define FRONTIER_MON_GOGOAT_GRASSY_TERRAIN                 1017
#define FRONTIER_MON_SEVIPER_GRASSY_TERRAIN                1018
#define FRONTIER_MON_BEHEEYEM_PSYCHIC_TERRAIN              1019
#define FRONTIER_MON_DELPHOX_PSYCHIC_TERRAIN               1020
#define FRONTIER_MON_MEGA_SHARPEDO_PSYCHIC_TERRAIN         1021
#define FRONTIER_MON_OCTILLERY_TRICK_ROOM                  1022
#define FRONTIER_MON_DARMANITAN_ZEN_TRICK_ROOM             1023
#define FRONTIER_MON_RAMPARDOS_TRICK_ROOM                  1024
//Special
#define FRONTIER_MON_JOLTEON_BATON_PASS                    1025
#define FRONTIER_MON_VAPOREON_BATON_PASS                   1026
#define FRONTIER_MON_ESPEON_BATON_PASS                     1027
#define FRONTIER_MON_TOXICROAK_GIMMICK                     1028
#define FRONTIER_MON_TOXAPEX_GIMMICK                       1029
#define FRONTIER_MON_SKARMORY_GIMMICK                      1030
#define FRONTIER_MON_NINJASK_EGGTACTICAL                   1031
#define FRONTIER_MON_SCIZOR_EGGTACTICAL                    1032
#define FRONTIER_MON_UMBREON_EGGTACTICAL                   1033
#define FRONTIER_MON_DELIBIRD_MASOCHIST                    1034
#define FRONTIER_MON_DUNSPARCE_MASOCHIST                   1035
#define FRONTIER_MON_LUVDISC_MASOCHIST                     1036
#define FRONTIER_MON_HIPPOWDON_FEAR                        1037
#define FRONTIER_MON_TOGEDEMARU_FEAR                       1038
#define FRONTIER_MON_MAGNEMITE_FEAR                        1039
#define FRONTIER_MON_BLANK1_BLANK3                         1040
#define FRONTIER_MON_BLANK2_BLANK3                         1041
#define FRONTIER_MON_BLANK3_BLANK3                         1042
#define FRONTIER_MON_BLANK1_BLANK4                         1043
#define FRONTIER_MON_BLANK2_BLANK4                         1044
#define FRONTIER_MON_BLANK3_BLANK4                         1045

#define NUM_FRONTIER_MONS                                  1046

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
