#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                             0
#define TRAINER_SAWYER_1                         1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1             2
#define TRAINER_GRUNT_2                          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3             4
#define TRAINER_GRUNT_4                          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1          6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2          7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3          8
#define TRAINER_GABRIELLE_1                      9
#define TRAINER_GRUNT_PETALBURG_WOODS            10
#define TRAINER_MARCEL                           11
#define TRAINER_ALBERTO                          12
#define TRAINER_ED                               13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4          14
#define TRAINER_DECLAN                           15
#define TRAINER_GRUNT_RUSTURF_TUNNEL             16
#define TRAINER_GRUNT_WEATHER_INST_1             17
#define TRAINER_GRUNT_WEATHER_INST_2             18
#define TRAINER_GRUNT_WEATHER_INST_3             19
#define TRAINER_GRUNT_14                         20
#define TRAINER_GRUNT_15                         21
#define TRAINER_GRUNT_16                         22
#define TRAINER_GRUNT_MT_PYRE_1                  23
#define TRAINER_GRUNT_MT_PYRE_2                  24
#define TRAINER_GRUNT_MT_PYRE_3                  25
#define TRAINER_GRUNT_WEATHER_INST_4             26
#define TRAINER_GRUNT_21                         27
#define TRAINER_GRUNT_22                         28
#define TRAINER_FREDRICK                         29
#define TRAINER_MATT                             30
#define TRAINER_ZANDER                           31
#define TRAINER_SHELLY_1                         32
#define TRAINER_SHELLY_2                         33
#define TRAINER_ARCHIE                           34
#define TRAINER_LEAH                             35
#define TRAINER_DAISY                            36
#define TRAINER_ROSE_1                           37
#define TRAINER_FELIX                            38
#define TRAINER_VIOLET                           39
#define TRAINER_MORRIS                           40
#define TRAINER_BRINEY                           41
#define TRAINER_STEVEN_POSTGAME                  42
#define TRAINER_DUSTY_1                          43
#define TRAINER_CHIP                             44
#define TRAINER_FOSTER                           45
#define TRAINER_GABBY_AND_TY_1                   46
#define TRAINER_GABBY_AND_TY_2                   47
#define TRAINER_GABBY_AND_TY_3                   48
#define TRAINER_GABBY_AND_TY_4                   49
#define TRAINER_GABBY_AND_TY_5                   50
#define TRAINER_GABBY_AND_TY_6                   51
#define TRAINER_LOLA_1                           52
#define TRAINER_AUSTINA                          53
#define TRAINER_GWEN                             54
#define TRAINER_RICKY_1                          55
#define TRAINER_SIMON                            56
#define TRAINER_CHARLIE                          57
#define TRAINER_RANDALL                          58
#define TRAINER_PARKER                           59
#define TRAINER_GEORGE                           60
#define TRAINER_BERKE                            61
#define TRAINER_BRAXTON                          62
#define TRAINER_VINCENT                          63
#define TRAINER_LEROY                            64
#define TRAINER_WILTON_1                         65
#define TRAINER_EDGAR                            66
#define TRAINER_ALBERT                           67
#define TRAINER_SAMUEL                           68
#define TRAINER_VITO                             69
#define TRAINER_OWEN                             70
#define TRAINER_STEVEN_POSTGAME9                 71
#define TRAINER_WARREN                           72
#define TRAINER_MARY                             73
#define TRAINER_ALEXIA                           74
#define TRAINER_JODY                             75
#define TRAINER_WENDY                            76
#define TRAINER_KEIRA                            77
#define TRAINER_BROOKE_1                         78
#define TRAINER_JENNIFER                         79
#define TRAINER_HOPE                             80
#define TRAINER_SHANNON                          81
#define TRAINER_MICHELLE                         82
#define TRAINER_CAROLINE                         83
#define TRAINER_JULIE                            84
#define TRAINER_STEVEN_POSTGAME8                 85
#define TRAINER_BROOKE_3                         86
#define TRAINER_BROOKE_4                         87
#define TRAINER_BROOKE_5                         88
#define TRAINER_PATRICIA                         89
#define TRAINER_KINDRA                           90
#define TRAINER_TAMMY                            91
#define TRAINER_VALERIE_1                        92
#define TRAINER_TASHA                            93
#define TRAINER_CINDY_1                          94
#define TRAINER_DAPHNE                           95
#define TRAINER_GRUNT_SPACE_CENTER_2             96
#define TRAINER_CINDY_2                          97
#define TRAINER_BRIANNA                          98
#define TRAINER_NAOMI                            99
#define TRAINER_CINDY_5                          100
#define TRAINER_CINDY_6                          101
#define TRAINER_MELISSA                          102
#define TRAINER_SHEILA                           103
#define TRAINER_SHIRLEY                          104
#define TRAINER_JESSICA_1                        105
#define TRAINER_CONNIE                           106
#define TRAINER_BRIDGET                          107
#define TRAINER_OLIVIA                           108
#define TRAINER_TIFFANY                          109
#define TRAINER_WINSTON_1                        110
#define TRAINER_MOLLIE                           111
#define TRAINER_GARRET                           112
#define TRAINER_STEVE_1                          113
#define TRAINER_THALIA_1                         114
#define TRAINER_MARK                             115
#define TRAINER_GRUNT_MT_CHIMNEY_1               116
#define TRAINER_LUIS                             117
#define TRAINER_DOMINIK                          118
#define TRAINER_DOUGLAS                          119
#define TRAINER_DARRIN                           120
#define TRAINER_TONY_1                           121
#define TRAINER_JEROME                           122
#define TRAINER_MATTHEW                          123
#define TRAINER_DAVID                            124
#define TRAINER_SPENCER                          125
#define TRAINER_ROLAND                           126
#define TRAINER_NOLEN                            127
#define TRAINER_STAN                             128
#define TRAINER_BARRY                            129
#define TRAINER_DEAN                             130
#define TRAINER_RODNEY                           131
#define TRAINER_RICHARD                          132
#define TRAINER_HERMAN                           133
#define TRAINER_SANTIAGO                         134
#define TRAINER_GILBERT                          135
#define TRAINER_FRANKLIN                         136
#define TRAINER_KEVIN                            137
#define TRAINER_JACK                             138
#define TRAINER_DUDLEY                           139
#define TRAINER_CHAD                             140
#define TRAINER_TAKAO                            141
#define TRAINER_HITOSHI                          142
#define TRAINER_KIYO                             143
#define TRAINER_KOICHI                           144
#define TRAINER_NOB_1                            145
#define TRAINER_YUJI                             146
#define TRAINER_DAISUKE                          147
#define TRAINER_ATSUSHI                          148
#define TRAINER_KIRK                             149
#define TRAINER_GRUNT_25                         150
#define TRAINER_GRUNT_26                         151
#define TRAINER_SHAWN                            152
#define TRAINER_FERNANDO_1                       153
#define TRAINER_DALTON_1                         154
#define TRAINER_DALTON_3                         155
#define TRAINER_DALTON_4                         156
#define TRAINER_DALTON_5                         157
#define TRAINER_COLE                             158
#define TRAINER_JEFF                             159
#define TRAINER_AXLE                             160
#define TRAINER_JACE                             161
#define TRAINER_KEEGAN                           162
#define TRAINER_BERNIE_1                         163
#define TRAINER_DREW                             164
#define TRAINER_BEAU                             165
#define TRAINER_LARRY                            166
#define TRAINER_SHANE                            167
#define TRAINER_JUSTIN                           168
#define TRAINER_ETHAN_1                          169
#define TRAINER_AUTUMN                           170
#define TRAINER_TRAVIS                           171
#define TRAINER_BRENT                            172
#define TRAINER_DONALD                           173
#define TRAINER_TAYLOR                           174
#define TRAINER_JEFFREY_1                        175
#define TRAINER_DEREK                            176
#define TRAINER_JEFFREY_3                        177
#define TRAINER_JEFFREY_4                        178
#define TRAINER_JEFFREY_5                        179
#define TRAINER_EDWARD                           180
#define TRAINER_PRESTON                          181
#define TRAINER_VIRGIL                           182
#define TRAINER_BLAKE                            183
#define TRAINER_WILLIAM                          184
#define TRAINER_JOSHUA                           185
#define TRAINER_CAMERON_1                        186
#define TRAINER_JACLYN                           187
#define TRAINER_HANNAH                           188
#define TRAINER_SAMANTHA                         189
#define TRAINER_MAURA                            190
#define TRAINER_KAYLA                            191
#define TRAINER_ALEXIS                           192
#define TRAINER_JACKI_1                          193
#define TRAINER_WALTER_1                         194
#define TRAINER_MICAH                            195
#define TRAINER_THOMAS                           196
#define TRAINER_SIDNEY                           197
#define TRAINER_PHOEBE                           198
#define TRAINER_GLACIA                           199
#define TRAINER_DRAKE                            200
#define TRAINER_ROXANNE_1                        201
#define TRAINER_BRAWLY_1                         202
#define TRAINER_WATTSON_1                        203
#define TRAINER_FLANNERY_1                       204
#define TRAINER_NORMAN_1                         205
#define TRAINER_WINONA_1                         206
#define TRAINER_TATE_AND_LIZA_1                  207
#define TRAINER_JUAN_1                           208
#define TRAINER_JERRY_1                          209
#define TRAINER_TED                              210
#define TRAINER_PAUL                             211
#define TRAINER_KAREN_1                          212
#define TRAINER_GEORGIA                          213
#define TRAINER_KATE_AND_JOY                     214
#define TRAINER_ANNA_AND_MEG_1                   215
#define TRAINER_VICTOR                           216
#define TRAINER_MIGUEL_1                         217
#define TRAINER_COLTON                           218
#define TRAINER_VICTORIA                         219
#define TRAINER_VANESSA                          220
#define TRAINER_BETHANY                          221
#define TRAINER_ISABEL_1                         222
#define TRAINER_TIMOTHY_1                        223
#define TRAINER_VICKY                            224
#define TRAINER_SHELBY_1                         225
#define TRAINER_CALVIN_1                         226
#define TRAINER_BILLY                            227
#define TRAINER_JOSH                             228
#define TRAINER_TOMMY                            229
#define TRAINER_JOEY                             230
#define TRAINER_BEN                              231
#define TRAINER_QUINCY                           232
#define TRAINER_KATELYNN                         233
#define TRAINER_JAYLEN                           234
#define TRAINER_DILLON                           235
#define TRAINER_EDDIE                            236
#define TRAINER_ALLEN                            237
#define TRAINER_TIMMY                            238
#define TRAINER_WALLACE                          239
#define TRAINER_ANDREW                           240
#define TRAINER_IVAN                             241
#define TRAINER_CLAUDE                           242
#define TRAINER_ELLIOT_1                         243
#define TRAINER_NED                              244
#define TRAINER_DALE                             245
#define TRAINER_NOLAN                            246
#define TRAINER_BARNY                            247
#define TRAINER_WADE                             248
#define TRAINER_CARTER                           249
#define TRAINER_ELLIOT_3                         250
#define TRAINER_ELLIOT_4                         251
#define TRAINER_ELLIOT_5                         252
#define TRAINER_RONALD                           253
#define TRAINER_JACOB                            254
#define TRAINER_ANTHONY                          255
#define TRAINER_BENJAMIN_1                       256
#define TRAINER_ABIGAIL_1                        257
#define TRAINER_JASMINE                          258
#define TRAINER_DYLAN_1                          259
#define TRAINER_MARIA_1                          260
#define TRAINER_CAMDEN                           261
#define TRAINER_DEMETRIUS                        262
#define TRAINER_ISAIAH_1                         263
#define TRAINER_PABLO_1                          264
#define TRAINER_CHASE                            265
#define TRAINER_ISOBEL                           266
#define TRAINER_DONNY                            267
#define TRAINER_TALIA                            268
#define TRAINER_KATELYN_1                        269
#define TRAINER_ALLISON                          270
#define TRAINER_NICOLAS_1                        271
#define TRAINER_AARON                            272
#define TRAINER_PERRY                            273
#define TRAINER_HUGH                             274
#define TRAINER_PHIL                             275
#define TRAINER_JARED                            276
#define TRAINER_HUMBERTO                         277
#define TRAINER_PRESLEY                          278
#define TRAINER_EDWARDO                          279
#define TRAINER_COLIN                            280
#define TRAINER_ROBERT_1                         281
#define TRAINER_BENNY                            282
#define TRAINER_CHESTER                          283
#define TRAINER_ALEX                             284
#define TRAINER_BECK                             285
#define TRAINER_YASU                             286
#define TRAINER_TAKASHI                          287
#define TRAINER_DIANNE                           288
#define TRAINER_JANI                             289
#define TRAINER_LAO_1                            290
#define TRAINER_LUNG                             291
#define TRAINER_JOCELYN                          292
#define TRAINER_LAURA                            293
#define TRAINER_CYNDY_1                          294
#define TRAINER_CORA                             295
#define TRAINER_PAULA                            296
#define TRAINER_MADELINE_1                       297
#define TRAINER_CLARISSA                         298
#define TRAINER_ANGELICA                         299
#define TRAINER_BEVERLY                          300
#define TRAINER_IMANI                            301
#define TRAINER_KYLA                             302
#define TRAINER_DENISE                           303
#define TRAINER_BETH                             304
#define TRAINER_TARA                             305
#define TRAINER_MISSY                            306
#define TRAINER_ALICE                            307
#define TRAINER_JENNY_1                          308
#define TRAINER_GRACE                            309
#define TRAINER_TANYA                            310
#define TRAINER_SHARON                           311
#define TRAINER_NIKKI                            312
#define TRAINER_BRENDA                           313
#define TRAINER_KATIE                            314
#define TRAINER_SUSIE                            315
#define TRAINER_KARA                             316
#define TRAINER_DANA                             317
#define TRAINER_SIENNA                           318
#define TRAINER_DEBRA                            319
#define TRAINER_LINDA                            320
#define TRAINER_KAYLEE                           321
#define TRAINER_LAUREL                           322
#define TRAINER_CARLEE                           323
#define TRAINER_HEIDI                            324
#define TRAINER_BECKY                            325
#define TRAINER_CAROL                            326
#define TRAINER_NANCY                            327
#define TRAINER_MARTHA                           328
#define TRAINER_DIANA_1                          329
#define TRAINER_CEDRIC                           330
#define TRAINER_IRENE                            331
#define TRAINER_AMY_AND_LIV_1                    332
#define TRAINER_GINA_AND_MIA_1                   333
#define TRAINER_MIU_AND_YUKI                     334
#define TRAINER_AMY_AND_LIV_3                    335
#define TRAINER_GINA_AND_MIA_2                   336
#define TRAINER_HUEY                             337
#define TRAINER_EDMOND                           338
#define TRAINER_ERNEST_1                         339
#define TRAINER_DWAYNE                           340
#define TRAINER_PHILLIP                          341
#define TRAINER_LEONARD                          342
#define TRAINER_DUNCAN                           343
#define TRAINER_ELI                              344
#define TRAINER_ANNIKA                           345
#define TRAINER_JAZMYN                           346
#define TRAINER_JONAS                            347
#define TRAINER_KAYLEY                           348
#define TRAINER_AURON                            349
#define TRAINER_KELVIN                           350
#define TRAINER_MARLEY                           351
#define TRAINER_REYNA                            352
#define TRAINER_HUDSON                           353
#define TRAINER_CONOR                            354
#define TRAINER_EDWIN_1                          355
#define TRAINER_HECTOR                           356
#define TRAINER_COURTNEY_MOSSDEEP                357
#define TRAINER_WALLY_VR_1                       358
#define TRAINER_BRENDAN_1                        359
#define TRAINER_BRENDAN_3                        360
#define TRAINER_HAROLD                           361
#define TRAINER_TIM                              362
#define TRAINER_JIM                              363
#define TRAINER_BRENDAN_4                        364
#define TRAINER_JOYCE                            365
#define TRAINER_DELTON                           366
#define TRAINER_MARCUS                           367
#define TRAINER_DAWN_1                           368
#define TRAINER_NICK                             369
#define TRAINER_DAWN_4                           370
#define TRAINER_LEMMY                            371
#define TRAINER_DAWN_3                           372
#define TRAINER_TERRENCE                         373
#define TRAINER_MASAHIRO                         374
#define TRAINER_MIA_AND_JAKE                     375
#define TRAINER_REL_COURTNEY_2                   376
#define TRAINER_ISAAC_1                          377
#define TRAINER_DAVIS                            378
#define TRAINER_MITCHELL                         379
#define TRAINER_STEVEN_POSTGAME01                380
#define TRAINER_STEVEN_POSTGAME02                381
#define TRAINER_STEVEN_POSTGAME03                382
#define TRAINER_STEVEN_POSTGAME04                383
#define TRAINER_LYDIA_1                          384
#define TRAINER_HALLE                            385
#define TRAINER_GARRISON                         386
#define TRAINER_CHALLENGER_DANNY                 387
#define TRAINER_BAD_TENANT                       388
#define TRAINER_STEVEN_POSTGAME00                389
#define TRAINER_JACKSON_1                        390
#define TRAINER_LORENZO                          391
#define TRAINER_SEBASTIAN                        392
#define TRAINER_STEVEN_POSTGAME11                393
#define TRAINER_JACKSON_3                        394
#define TRAINER_JACKSON_4                        395
#define TRAINER_JACKSON_5                        396
#define TRAINER_CATHERINE_1                      397
#define TRAINER_JENNA                            398
#define TRAINER_SOPHIA                           399
#define TRAINER_STEVEN_POSTGAME07                400
#define TRAINER_STEVEN_POSTGAME08                401
#define TRAINER_STEVEN_POSTGAME09                402
#define TRAINER_STEVEN_POSTGAME10                403
#define TRAINER_JULIO                            404
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5          405
#define TRAINER_GRUNT_RUSTURF_MAGMA              406
#define TRAINER_GRUNT_MT_PYRE_4                  407
#define TRAINER_GRUNT_JAGGED_PASS                408
#define TRAINER_MARC                             409
#define TRAINER_BRENDEN                          410
#define TRAINER_LILITH                           411
#define TRAINER_CRISTIAN                         412
#define TRAINER_SYLVIA                           413
#define TRAINER_LEONARDO                         414
#define TRAINER_ATHENA                           415
#define TRAINER_HARRISON                         416
#define TRAINER_GRUNT_MT_CHIMNEY_2               417
#define TRAINER_CLARENCE                         418
#define TRAINER_TERRY                            419
#define TRAINER_NATE                             420
#define TRAINER_KATHLEEN                         421
#define TRAINER_CLIFFORD                         422
#define TRAINER_NICHOLAS                         423
#define TRAINER_GRUNT_SPACE_CENTER_3             424
#define TRAINER_GRUNT_SPACE_CENTER_4             425
#define TRAINER_GRUNT_SPACE_CENTER_5             426
#define TRAINER_GRUNT_SPACE_CENTER_6             427
#define TRAINER_GRUNT_SPACE_CENTER_7             428
#define TRAINER_MACEY                            429
#define TRAINER_STORY_MAXIE                      430
#define TRAINER_BRENDAN_2                        431
#define TRAINER_PAXTON                           432
#define TRAINER_ISABELLA                         433
#define TRAINER_GRUNT_WEATHER_INST_5             434
#define TRAINER_COURTNEY_MT_CHIMNEY              435
#define TRAINER_JONATHAN                         436
#define TRAINER_DEVON_2                          437
#define TRAINER_STORY_MEWTWO                     438
#define TRAINER_MAXIE_MAGMA_HIDEOUT              439
#define TRAINER_MAXIE_MT_CHIMNEY                 440
#define TRAINER_TIANA                            441
#define TRAINER_HALEY_1                          442
#define TRAINER_JANICE                           443
#define TRAINER_VIVI                             444
#define TRAINER_STEVEN_POSTGAME12                445
#define TRAINER_HALEY_3                          446
#define TRAINER_HALEY_4                          447
#define TRAINER_HALEY_5                          448
#define TRAINER_SALLY                            449
#define TRAINER_ROBIN                            450
#define TRAINER_ANDREA                           451
#define TRAINER_CRISSY                           452
#define TRAINER_RICK                             453
#define TRAINER_LYLE                             454
#define TRAINER_JOSE                             455
#define TRAINER_DOUG                             456
#define TRAINER_GREG                             457
#define TRAINER_KENT                             458
#define TRAINER_JAMES_1                          459
#define TRAINER_JAMES_2                          460
#define TRAINER_JAMES_3                          461
#define TRAINER_JAMES_4                          462
#define TRAINER_STEVEN_POSTGAME13                463
#define TRAINER_BRICE                            464
#define TRAINER_TRENT_1                          465
#define TRAINER_LENNY                            466
#define TRAINER_LUCAS_1                          467
#define TRAINER_ALAN                             468
#define TRAINER_CLARK                            469
#define TRAINER_ERIC                             470
#define TRAINER_LUCAS_2                          471
#define TRAINER_MIKE_1                           472
#define TRAINER_MIKE_2                           473
#define TRAINER_STEVEN_POSTGAME14                474
#define TRAINER_STEVEN_POSTGAME15                475
#define TRAINER_LORWYN                           476
#define TRAINER_MR_STONE                         477
#define TRAINER_DEZ_AND_LUKE                     478
#define TRAINER_LEA_AND_JED                      479
#define TRAINER_KIRA_AND_DAN_1                   480
#define TRAINER_DEVON_ENFORCER_5                 481
#define TRAINER_DEVON_ENFORCER_4                 482
#define TRAINER_DEVON_ENFORCER_3                 483
#define TRAINER_DEVON_ENFORCER_2                 484
#define TRAINER_JOHANNA                          485
#define TRAINER_GERALD                           486
#define TRAINER_VIVIAN                           487
#define TRAINER_DANIELLE                         488
#define TRAINER_HIDEO                            489
#define TRAINER_KEIGO                            490
#define TRAINER_RILEY                            491
#define TRAINER_FLINT                            492
#define TRAINER_ASHLEY                           493
#define TRAINER_WALLY_MAUVILLE                   494
#define TRAINER_WALLY_VR_2                       495
#define TRAINER_WALLY_VR_3                       496
#define TRAINER_WALLY_VR_4                       497
#define TRAINER_WALLY_VR_5                       498
#define TRAINER_BRENDAN_5                        499
#define TRAINER_REL_COURTNEY_1                   500
#define TRAINER_DEVON_ENFORCER_1                 501
#define TRAINER_DAWN_5                           502
#define TRAINER_STEVEN_STORY1                    503
#define TRAINER_ESKIMO_1                         504
#define TRAINER_JONAH                            505
#define TRAINER_HENRY                            506
#define TRAINER_ROGER                            507
#define TRAINER_ALEXA                            508
#define TRAINER_RUBEN                            509
#define TRAINER_KOJI_1                           510
#define TRAINER_WAYNE                            511
#define TRAINER_AIDAN                            512
#define TRAINER_REED                             513
#define TRAINER_TISHA                            514
#define TRAINER_TORI_AND_TIA                     515
#define TRAINER_KIM_AND_IRIS                     516
#define TRAINER_TYRA_AND_IVY                     517
#define TRAINER_MEL_AND_PAUL                     518
#define TRAINER_JOHN_AND_JAY_1                   519
#define TRAINER_JOHN_AND_JAY_2                   520
#define TRAINER_JOHN_AND_JAY_3                   521
#define TRAINER_JOHN_AND_JAY_4                   522
#define TRAINER_RELI_AND_IAN                     523
#define TRAINER_LILA_AND_ROY_1                   524
#define TRAINER_STEVEN_POSTGAME0                 525
#define TRAINER_STEVEN_POSTGAME1                 526
#define TRAINER_STEVEN_POSTGAME2                 527
#define TRAINER_STEVEN_POSTGAME3                 528
#define TRAINER_LISA_AND_RAY                     529
#define TRAINER_CHRIS                            530
#define TRAINER_DAWSON                           531
#define TRAINER_SARAH                            532
#define TRAINER_DARIAN                           533
#define TRAINER_HAILEY                           534
#define TRAINER_CHANDLER                         535
#define TRAINER_KALEB                            536
#define TRAINER_JOSEPH                           537
#define TRAINER_ALYSSA                           538
#define TRAINER_MARCOS                           539
#define TRAINER_RHETT                            540
#define TRAINER_TYRON                            541
#define TRAINER_CELINA                           542
#define TRAINER_BIANCA                           543
#define TRAINER_HAYDEN                           544
#define TRAINER_SOPHIE                           545
#define TRAINER_COBY                             546
#define TRAINER_LAWRENCE                         547
#define TRAINER_WYATT                            548
#define TRAINER_ANGELINA                         549
#define TRAINER_KAI                              550
#define TRAINER_CHARLOTTE                        551
#define TRAINER_DEANDRE                          552
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1            553
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2            554
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3            555
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4            556
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5            557
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6            558
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7            559
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8            560
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9            561
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10           562
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11           563
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12           564
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13           565
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14           566
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15           567
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16           568
#define TRAINER_COURTNEY_3                       569
#define TRAINER_DARCY                            570
#define TRAINER_MAXIE_3                          571
#define TRAINER_PETE                             572
#define TRAINER_ISABELLE                         573
#define TRAINER_ANDRES_1                         574
#define TRAINER_JOSUE                            575
#define TRAINER_CAMRON                           576
#define TRAINER_CORY_1                           577
#define TRAINER_CAROLINA                         578
#define TRAINER_ELIJAH                           579
#define TRAINER_CELIA                            580
#define TRAINER_BRYAN                            581
#define TRAINER_BRANDEN                          582
#define TRAINER_BRYANT                           583
#define TRAINER_SHAYLA                           584
#define TRAINER_KYRA                             585
#define TRAINER_JAIDEN                           586
#define TRAINER_ALIX                             587
#define TRAINER_HELENE                           588
#define TRAINER_MARLENE                          589
#define TRAINER_DEVAN                            590
#define TRAINER_JOHNSON                          591
#define TRAINER_MELINA                           592
#define TRAINER_BRANDI                           593
#define TRAINER_AISHA                            594
#define TRAINER_MAKAYLA                          595
#define TRAINER_FABIAN                           596
#define TRAINER_DAYTON                           597
#define TRAINER_RACHEL                           598
#define TRAINER_LEONEL                           599
#define TRAINER_CALLIE                           600
#define TRAINER_CALE                             601
#define TRAINER_MYLES                            602
#define TRAINER_PAT                              603
#define TRAINER_CRISTIN_1                        604
#define TRAINER_DAWN_2                           605
#define TRAINER_OVERLORD_RYU_REMATCH             606
#define TRAINER_ROXANNE_2                        607
#define TRAINER_ROXANNE_3                        608
#define TRAINER_ROXANNE_4                        609
#define TRAINER_SHANTI                           610
#define TRAINER_BRAWLY_2                         611
#define TRAINER_BRAWLY_3                         612
#define TRAINER_BRAWLY_4                         613
#define TRAINER_RANDOM_PARTY                     614
#define TRAINER_WATTSON_2                        615
#define TRAINER_WATTSON_3                        616
#define TRAINER_WATTSON_4                        617
#define TRAINER_DOPPELGANGER_F                   618
#define TRAINER_FLANNERY_2                       619
#define TRAINER_FLANNERY_3                       620
#define TRAINER_FLANNERY_4                       621
#define TRAINER_DOPPELGANGER_M                   622
#define TRAINER_NORMAN_2                         623
#define TRAINER_NORMAN_3                         624
#define TRAINER_NORMAN_4                         625
#define TRAINER_CHALLENGER_NORMAN                626
#define TRAINER_WINONA_2                         627
#define TRAINER_WINONA_3                         628
#define TRAINER_WINONA_4                         629
#define TRAINER_SHELLY_3                         630
#define TRAINER_TATE_AND_LIZA_2                  631
#define TRAINER_TATE_AND_LIZA_3                  632
#define TRAINER_TATE_AND_LIZA_4                  633
#define TRAINER_TATE_AND_LIZA_SINGLE             634
#define TRAINER_JUAN_2                           635
#define TRAINER_JUAN_3                           636
#define TRAINER_JUAN_4                           637
#define TRAINER_STORY_MEWTWO_2                   638
#define TRAINER_ANGELO                           639
#define TRAINER_DARIUS                           640
#define TRAINER_STEVEN                           641
#define TRAINER_ANABEL                           642
#define TRAINER_TUCKER                           643
#define TRAINER_SPENSER                          644
#define TRAINER_GRETA                            645
#define TRAINER_NOLAND                           646
#define TRAINER_LUCY                             647
#define TRAINER_BRANDON                          648
#define TRAINER_SIDNEY_REMATCH                   649
#define TRAINER_CHALLENGER_SIGMA                 650
#define TRAINER_CHALLENGER_JUAN                  651
#define TRAINER_CHALLENGER_GIOVANNI              652
#define TRAINER_CHALLENGER_ZOD                   653
#define TRAINER_CHALLENGER_LANCE                 654
#define TRAINER_CHALLENGER_ROBERT                655
#define TRAINER_CHALLENGER_JOHNATAN              656
#define TRAINER_STORY_LEAF                       657
#define TRAINER_GRUNT_AQUA_HIDEOUT_24            658
#define TRAINER_REL_LANA                         659
#define TRAINER_REL_BRENDAN                      660
#define TRAINER_REL_DAWN                         661
#define TRAINER_REL_SHELLY                       662
#define TRAINER_REL_LANETTE                      663
#define TRAINER_REL_MINNIE                       664
#define TRAINER_BETTY                            665
#define TRAINER_GRANT                            666
#define TRAINER_RYUJI                            667
#define TRAINER_CHARLES                          668
#define TRAINER_YUNA                             669
#define TRAINER_JASON                            670
#define TRAINER_RODETTE                          671
#define TRAINER_TYRONE                           672
#define TRAINER_LUNA                             673
#define TRAINER_MELANIE                          674
#define TRAINER_NERA                             675
#define TRAINER_ARNOLD                           676
#define TRAINER_DEO                              677
#define TRAINER_MALCOLM                          678
#define TRAINER_MAURICE                          679
#define TRAINER_REL_NURSE                        680
#define TRAINER_OVERLORD_RYU                     681
#define TRAINER_PHOEBE_REMATCH                   682
#define TRAINER_DRAKE_REMATCH                    683
#define TRAINER_GLACIA_REMATCH                   684
#define TRAINER_MARIELA                          685
#define TRAINER_ALVARO                           686
#define TRAINER_EVERETT                          687
#define TRAINER_RED                              688
#define TRAINER_LEAF                             689
#define TRAINER_BRENDAN_PLACEHOLDER              690
#define TRAINER_DAWN_PLACEHOLDER                 691

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      692
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
