gText_Birch_Welcome:: @ 82C897B
	.string "  $"

gText_Birch_Pokemon:: @ 82C89FB
	.string " $"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}Hello and welcome to\p"
	.string "             {COLOR LIGHT_GREEN}{SHADOW GREEN}Emerald Enhanced v7            \p" 
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}I have spared you Birch's speech.\p"
	.string "It's boring anyways.\n"
    .string "Emerald Enhanced is quite\p"
	.string "a bit more difficult than the\n"
	.string "vanilla game.\p"
	.string "Lastly, you should forget most\n"
	.string "of what you remember from the\l"
	.string "default story. $"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Would you like to play as a {COLOR LIGHT_BLUE}{SHADOW BLUE}male{COLOR DARK_GREY}{SHADOW LIGHT_GREY} or {COLOR LIGHT_RED}{SHADOW RED}female{SHADOW LIGHT_GREY}{COLOR DARK_GREY} \pcharacter?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "What name would you like to\n"
	.string "use for your character?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "You want to use {PLAYER}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "All right, here we go!\n"
	.string "Enjoy the suffering!             $"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string " $"

