gText_Birch_Welcome:: @ 82C897B
	.string "  $"

gText_Birch_Pokemon:: @ 82C89FB
	.string " $"


@         I don't know why, but the game is not clearing out the textbox after each line, so i filled in the extra space with... whitespace.


gText_Birch_MainSpeech:: @ 82C8A1F
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}Hello and welcome to\p"
	.string "             {COLOR LIGHT_GREEN}{SHADOW GREEN}Emerald Enhanced v{STR_VAR_1}      \p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}You can find us on Discord here:\n"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}https://discord.gg/UhmsDqHUHF {COLOR DARK_GREY}{SHADOW LIGHT_GREY}\p"
	.string "Join the discord for guides,   \n"
	.string "useful information, and bug reports.\p"
	.string "We look forward to seeing you! \p"
	.string "As for the game itself, expect \n"
	.string "it to be much harder than      \p"
	.string "vanilla, and don't try to follow\n"
	.string "the normal storyline.          \p"
	.string "  We have replaced the vanilla \n"
	.string "  storyline entirely.          $"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "                               \n"
	.string "                                  $"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Would you like to play as a {COLOR LIGHT_BLUE}{SHADOW BLUE}male{COLOR DARK_GREY}{SHADOW LIGHT_GREY} or {COLOR LIGHT_RED}{SHADOW RED}female{SHADOW LIGHT_GREY}{COLOR DARK_GREY} \ncharacter?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "What name would you like to      \n"
	.string "use for your character?        $"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "You want to use {PLAYER}?      $"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "All right, here we go!         \n"
	.string "Enjoy the suffering!           $"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "                              \n"
	.string "                              $"

