Underwater_SealedChamber_Braille_GoUpHere: @ 82A6B15
	.string "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC: @ 82A6B27
	.string "ABC$"

SealedChamber_OuterRoom_Braille_GHI: @ 82A6B31
	.string "GHI$"

SealedChamber_OuterRoom_Braille_MNO: @ 82A6B3B
	.string "MNO$"

SealedChamber_OuterRoom_Braille_TUV: @ 82A6B45
	.string "TUV$"

SealedChamber_OuterRoom_Braille_DEF: @ 82A6B4F
	.string "DEF$"

SealedChamber_OuterRoom_Braille_JKL: @ 82A6B59
	.string "JKL$"

SealedChamber_OuterRoom_Braille_PQRS: @ 82A6B63
	.string "PQRS$"

SealedChamber_OuterRoom_Braille_Period: @ 82A6B6E
	.string ".$"

SealedChamber_OuterRoom_Braille_WXYZ: @ 82A6B76
	.string "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma: @ 82A6B81
	.string ",$"

SealedChamber_OuterRoom_Braille_DigHere: @ 82A6B89
	.string "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth: @ 82A6B99
	.string "FIRST COMES\n"
	.string "WAILORD.\n"
	.string "LAST COMES\n"
	.string "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived: @ 82A6BCA
	.string "IN THIS\n"
	.string "CAVE WE\n"
	.string "HAVE\n"
	.string "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon: @ 82A6BEC
	.string "WE OWE ALL\n"
	.string "TO THE\n"
	.string "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway: @ 82A6C0D
	.string "BUT, WE\n"
	.string "SEALED THE\n"
	.string "POKEMON\n"
	.string "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt: @ 82A6C34
	.string "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope: @ 82A6C48
	.string "THOSE WITH\n"
	.string "COURAGE,\n"
	.string "THOSE WITH\n"
	.string "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits: @ 82A6C73
	.string "OPEN A DOOR.\n"
	.string "AN ETERNAL\n"
	.string "POKEMON\n"
	.string "WAITS.$"

DesertRuins_Braille_UseRockSmash: @ 82A6CA0
	.string "LEFT, LEFT,\n"
	.string "DOWN, DOWN.\n"
	.string "THEN, USE\n"
	.string "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall: @ 82A6CD4
	.string "STAY CLOSE\n"
	.string "TO THE WALL.\n"
	.string "RUN AROUND\n"
	.string "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle: @ 82A6D06
	.string "THOSE WHO\n"
	.string "INHERIT OUR\n"
	.string "WILL, SHINE\n"
	.string "IN THE MIDDLE.$"
