FallarborTown_CaveTown_MapScripts::
	.byte 0

FallarborTown_CaveTown_Text_GemRefinerSign::
	msgbox FTCT_GemRefinerSignMessage
	release
	end
	
FTCT_GemRefinerSignMessage:
	.string "Fallarbor Gem Ore Refiner\n"
	.string "“From rough rock to dazzling diamond”$"

FallarborTown_CaveTown_Text_ShardRefinerSign::
	msgbox FTCT_ShardRefinerSignMessage
	release
	end

FTCT_ShardRefinerSignMessage:
	.string "Fallarbor Shard Ore Refiner\n"
	.string "“Where ancient shards are unearthed”$"

FallarborTown_CaveTown_Text_FossilLabSign::
	msgbox FTCT_FossilLabSignMessage
	release
	end
	
FTCT_FossilLabSignMessage:
	.string "Fallarbor Fossil Lab\n"
	.string "“The study of the extinct.”$"

FallarborTown_CaveTown_Text_FossilManiacSign::
	msgbox FTCT_FossilManiacSignMessage
	release
	end
	
FTCT_FossilManiacSignMessage:
	.string "Fossil Maniac's House\n"
	.string "“All rare fossils are mine!”$"

FallarborTown_CaveTown_Text_MiningMasterSign::
	msgbox FTCT_MiningMasterSignMessage
	release
	end
	
FTCT_MiningMasterSignMessage:
	.string "Mining Master's House\n"
	.string "“Learn how to mine valuables.”$"

FallarborTown_CaveTown_Text_TownSign::
	msgbox FTCT_TownSignMessage
	release
	end
	
FTCT_TownSignMessage:
	.string "Fallarbor Mine\n"
	.string "“A humble mining town.”$"
	