Igloo3_MapScripts::
	.byte 0

Igloo3_EventScript_HintText::
	msgbox Igloo3_Text_HintText, MSGBOX_SIGN
	end

Igloo3_Text_HintText:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}(The text is old and faded.\n"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}It's hard to read.)\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}“…se …oc… S……sh in …ro…… of …h…\n"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}P……ar Pi…ar.”$"
