Igloo3_MapScripts::
	.byte 0

Igloo3_EventScript_HintText::
	msgbox Igloo3_Text_HintText, MSGBOX_SIGN
	end

Igloo3_Text_HintText:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}(The text is old and faded.\n"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}It's hard to read.)\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}“……i…g C……o…o……l …… M…\n"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}Fr……z… to ……i… e……r….”$"
