@====
DC_ThanksForJoining:
	.string "Thank you for joining us. The\n"
	.string "focus of this corporate meeting is\l"
	.string "to discuss the future of Devon.\p"
	.string "There have definitely been ups and\n"
	.string "downs as of late...and some of you\p"
	.string "are well aware of the causes\n"
	.string "behind it.$"

DC_BeforeIGoFurther:
	.string "Before I go further, however, we\n"
	.string "shall start on a positive note,\p"
	.string "with {PLAYER} giving us a full\n"
	.string "report on his first day as an\l"
	.string "official employee.$"

DC_FirstIMustSay:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}First, I must say that even with\n"
	.string "it being my first day, everyone\p"
	.string "has been friendly and easygoing,\n"
	.string "allowing me time to get accustomed\p"
	.string "to the work environment. I thank\l"
	.string "you all for that.\p"
	.string "In saying that, though, the events\n"
	.string "of today certainly piqued my\l"
	.string "interest.$"

DC_AfterTalking:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}After talking with everyone, I've\n"
	.string "learned that many employees have\l"
	.string "their own pressures to deal with...\p"
	.string "'When the company suffers, their\n"
	.string "employees suffer much harder.'$"

DC_WhatsThis:
	.string "What's this all about? I thought\n"
	.string "this meeting was to discuss the\l"
	.string "company's future.$"

DC_YouHaventLetMeFinish:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}It is, you just haven't let me\n"
	.string "finish...\p"
	.string "And besides that, Mr. Tadaki, why\n"
	.string "do you seem to be so...defensive?\p"
	.string "I'm simply stating what you told\n"
	.string "me to do.\p"
	.string "'Take a look around. Anyone here\n"
	.string "can tell you what a struggle it's\l"
	.string "been.'\p"
	.string "Am I not correct?$"

DC_CanSomeonePlease:
	.string "Can someone please tell us what's\n"
	.string "going on here?$"

DC_ToMakeALongStory:
	.string "To make a long story woefully\n"
	.string "short...{PLAYER} was tasked to\p"
	.string "look into the cause of the recent\n"
	.string "leaks our corporation has been\l"
	.string "having.$"

DC_HasAConclusion:
	.string "Has a conclusion been made?$"

DC_ItHasInFact:
	.string "It has. In fact, {PLAYER} can tell\n"
	.string "you how it was all done.$"

DC_IfYouWill:
	.string "If you will...$"

DC_InOrderToMake:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}In order to make sense of what had\n"
	.string "occurred, I first have to take you\l"
	.string "through my first day.\p"
	.string "At that point, my assignment was\n"
	.string "to simply introduce myself to the\p"
	.string "staff here, to which I started\n"
	.string "with those on the second floor.$"

DC_NoDoubt:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}No doubt everyone gave me a warm\n"
	.string "welcome, yet I couldn't help but\p"
	.string "notices certain gripes being\n"
	.string "present.$"

DC_NowMrHajio:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Now Mr. Hajio, the role of you and\n"
	.string "your partner here is to keep watch\p"
	.string "for any unauthorized persons to\n"
	.string "not enter the facility, correct?\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}That's right. They haven't a\n"
	.string "chance to get past us.\p"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}And yet, we had such an instance\n"
	.string "today...you two halted the news\p"
	.string "personnel in their tracks, and yet\n"
	.string "...inside the building. Care to\p"
	.string "explain?$"

DC_ThoseTwo:
	.string "Those two in particular are very\n"
	.string "persistent in getting what they\l"
	.string "want.$"

DC_AhYesTheNews:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Ah yes, the news...social media at\n"
	.string "its' finest...giving the people\p"
	.string "what they want...but at what\n"
	.string "price?$"

DC_HoldOnASec:
	.string "Hold on a sec! Are you implying\n"
	.string "that we take bribes and let them\p"
	.string "in on purpose!? Preposterous!$"

DC_IfMsIto:
	.string "If Ms. Ito would be where she\n"
	.string "ought to be in a timely manner,\l"
	.string "that would not have happened!$"

DC_ExcuseMe:
	.string "Excuse me? There were times when\n"
	.string "you two would be absent at a\l"
	.string "moment's notice!\p"
	.string "You expect me to stand guard all\n"
	.string "day and not even get a restroom\l"
	.string "break!?$"


DC_AndImDiabetic:
	.string "And I'm a diabetic, I have to eat\n"
	.string "on the regular.\p"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}So you admit that between the\n"
	.string "three of you...there are times\p"
	.string "when the entrance is unguarded?$"

DC_ISuppose:
	.string "I...suppose so.$"

DC_AtLeastImResponsible:
	.string "Hmph, at least I'm responsible\n"
	.string "enough to have a stand-in when I'm\p"
	.string "out of the office!$"

DC_HoweverJustLikeToday:
	.string "However, just like today, Ms. Ito,\n"
	.string "you seem to lose track of time\p"
	.string "when it comes to your breaks.\n"
	.string "I can't keep subbing for you if\p"
	.string "you continue this habit of\n"
	.string "tardiness. There's work to be done\p"
	.string "and not enough time to do it.$"

DC_IfIRecall:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}If I recall, Mr. Tadaki, you said\n"
	.string "you were 30 minutes late to your\p"
	.string "workstation. Did you, pray tell,\n"
	.string "wait for Ms. Ito to return?$"

DC_AreYouSerious:
	.string "Are you serious? If that was the\n"
	.string "case, Devon would be further\p"
	.string "behind schedule than it already is\n"
	.string "right now!$"

DC_SoIfImUnderstanding:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}So if I'm understanding right, not\n"
	.string "only would security be away on\p"
	.string "occasion, but the person manning\n"
	.string "the front desk can also not be\l"
	.string "present?\p"
	.string "Coupled with the fact that the\n"
	.string "Aqua member who stole the Devon\l"
	.string "Goods made such a clean break...$"

DC_ItsNoLonger:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}It's no longer a case of 'Who dun\n"
	.string "it?' Rather, the true culprit is\l"
	.string "none other than...negligence.$"


DC_Negligence:
	.string "'Negligence'?$"

DC_AccordingToPrez:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Mr. Tadaki, according to the Prez,\n"
	.string "you were in charge of handling the\p"
	.string "Devon Goods, on top of many other\l"
	.string "assignments.\p"
	.string "And at one point, Ms. Ito asked\n"
	.string "for someone to relieve her for\p"
	.string "noon break, which also ended up\l"
	.string "falling on you.\p"
	.string "You complied with the request,\n"
	.string "even taking your work with you.\p"
	.string "Again, Ms. Ito took longer than\n"
	.string "usual in returning, and in your\p"
	.string "haste to stay on time, you left\n"
	.string "her post unattended as you went\p"
	.string "upstairs, and yet, due to your\n"
	.string "mind constantly focusing on other\p"
	.string "things, forgot the Goods that was\n"
	.string "left on the counter.$"

DC_YouAndYourPartner:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Hajio...you and your partner had\n"
	.string "no recollection of the Goods being\p"
	.string "stolen because neither of you were\n"
	.string "there when the Aqua member went in\p"
	.string "and grabbed it. You assumed Tadaki\n"
	.string "took it back with him, which he\l"
	.string "should've.\p"
	.string "Finally, Ms. Ito returned to her\n"
	.string "station, the three of you none the\p"
	.string "wiser as to what took place until\n"
	.string "Tadaki rushed downstairs,\p"
	.string "wondering as to the whereabouts of\n"
	.string "the Goods...but it was too late,\l"
	.string "and long gone.$"

DC_ChainOfEvents:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Those chain of events led to that\n"
	.string "incident...same thing happened\l"
	.string "with the information leak.$"

DC_YouExpectMe:
	.string "You expect to believe that? For\n"
	.string "the same set of events to happen\l"
	.string "twice...\p"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Yes, I know it's somewhat unlikely\n"
	.string "for the two incidents to be that\p"
	.string "connected...but it's not...\n"
	.string "Unrealistic.$"

DC_OthersAddress:
	.string "Other colleagues do address that\n"
	.string "Mr. Tadaki has a tendency to leave\p"
	.string "his work scattered amongst various\n"
	.string "places, and when he has multiple\p"
	.string "tasks to complete, would stop all\n"
	.string "progress on previous work and\p"
	.string "quite literally, move on to the\n"
	.string "next one.\p"
	.string "More than likely, during the\n"
	.string "second incident, the papers that\p"
	.string "were laid out in the open were\n"
	.string "about the EXP Drive, and the news\p"
	.string "media caught a glimpse of it\n"
	.string "before security caught them in the\l"
	.string "act.$"

DC_ForgiveUs:
	.string "Forgive us, President Stone...\n"
	.string "I am ashamed...should've known\p"
	.string "from the get-go something like\n"
	.string "this would happen.$"

DC_WhatHeSaid:
	.string  "Yeah...what he said.\n"

DC_ItsNotJust:
	.string "It's not just security. I'm the\n"
	.string "main one to blame...I should be\p"
	.string "more careful of where I leave my\n"
	.string "documents, and also need to be\p"
	.string "more patient with my colleagues.$"

DC_AndINeed:
	.string "And I need to be more cognizant of\n"
	.string "the time I leave so that I don't\p"
	.string "cause unnecessary burdens for the\n"
	.string "others...$"

DC_WellThereYaGo:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Well, there ya go, Mr. Stone. I\n"
	.string "mean, Prez. Case closed!\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}So it has. Good work, {PLAYER}.\p"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}And great meeting everyone. Let us\n"
	.string "continue to learn fro-$"

DC_IsThatARing:
	.string "Ms. Ito...is that a ring I see on\n"
	.string "your left hand? Congratulations!\p"
	.string "Who's the lucky man? We outta\n"
	.string "celebrate!$"

DC_WellThats:
	.string "Well, that's...$"

DC_Shyness:
	.string "Feigning shyness, are you? No\n"
	.string "worries! I'm sure we'll get to see\l"
	.string "him real soon! Hahaha!$"
	
DC_OhBoy:
	.string " {COLOR LIGHT_BLUE}{SHADOW BLUE}(And when you do...ohh boy...)$"

DC_ToThinkThe:
	.string "To think...the real leak in the\n"
	.string "corporation was no leak at all...\p"
	.string "Nevertheless, I, and Devon as a\n"
	.string "whole, are very much indebted to\p"
	.string "you, {PLAYER}. You must be given\n"
	.string "a just reward! Here you go!$"

DC_TheExpDrive:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}The EXP Drive!?\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}As timing would have it, we\n"
	.string "recently completed it, and before\p"
	.string "we take it to Marketing and\n"
	.string "Production, I would like you to be\l"
	.string "the first to have it.\p"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Thank you very much! And this...?\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}It's an old artifact I found\n"
	.string "during my younger years. I've been\p"
	.string "meaning to look into what it\n"
	.string "entails, however my time as a\p"
	.string "successful entrepreneur has led me\n"
	.string "to forget about it. Perhaps you\p"
	.string "shall discover what treasure\n"
	.string "awaits you there! Take care,\l"
	.string "{PLAYER}!$"

@Movement
DC_ToHajio:@Red Suit Worker to the right
	walk_up
	walk_up
	walk_left
	walk_left
	walk_left
	walk_in_place_up
	step_end

DC_ReturnToPrez:
	walk_right
	walk_right
	walk_right
	walk_down
	walk_down
	walk_in_place_left
	step_end
