Igloo4_MapScripts::
	.byte 0

Igloo4_EventScript_HintText::
	msgbox Igloo4_Text_HintText, MSGBOX_SIGN
	end

Igloo4_Text_HintText:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}(The text is old and faded.\n"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}It's hard to read.)\p"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}“U…… R……k …ma…… …… F……nt …… t…e\n"
	.string "{COLOR DARK_GREY}{SHADOW LIGHT_GREY}…ol…… ……ll…….”$"
