#include "global.h"
#include "event_data.h"
#include "pokemon.h"
#include "pokemon_storage_system.h"
#include "random.h"

const u16 gRyuEggHatchFactionsQuestTable[8][5] ={
    [FACTION_NATURALISTS] = {SPECIES_NUZLEAF, SPECIES_SUNKERN, SPECIES_SNIVY, SPECIES_PIDGEY, SPECIES_ZIGZAGOON},
    [FACTION_STUDENTS] = {SPECIES_POOCHYENA, SPECIES_BUNEARY, SPECIES_ROCKRUFF, SPECIES_CATERPIE, SPECIES_MARILL},
    [FACTION_NOBLES] = {SPECIES_TRAPINCH, SPECIES_MEOWTH, SPECIES_MUDKIP, SPECIES_POPPLIO, SPECIES_PIKIPEK},
    [FACTION_POKEFANS] = {SPECIES_PIKACHU, SPECIES_PICHU, SPECIES_MINUN, SPECIES_JOLTIK, SPECIES_TEDDIURSA},
    [FACTION_OUTCASTS] = {SPECIES_GASTLY, SPECIES_MAWILE, SPECIES_SABLEYE, SPECIES_SNORUNT, SPECIES_TENTACOOL},
    [FACTION_PROFESSIONALS] = {SPECIES_ELEKID, SPECIES_MAGBY, SPECIES_ZANGOOSE, SPECIES_ELECTRIKE, SPECIES_NUMEL},
    [FACTION_ATHLETES] = {SPECIES_HITMONTOP, SPECIES_MIENFOO, SPECIES_DODUO, SPECIES_CLAWITZER, SPECIES_CARVANHA},
    [FACTION_OTHERS] = {0,0,0,0,0},
};

void RyuSetupEggHatchQuest(void)
{
    u8 faction = VarGet(VAR_RYU_DAILY_QUEST_ASSIGNEE_FACTION);
    u8 whichEgg = gSpecialVar_Result;
    u16 eggSpecies = gRyuEggHatchFactionsQuestTable[faction][whichEgg];
    VarSet(VAR_RYU_DAILY_QUEST_TARGET, eggSpecies);
}