MagmaHideout_3F_3R_MapScripts:: @ 823ACFF
	.byte 0
	
@===============================================================Aqua grunt fights here for magma event to keep organized

MH_AquaGrunt1::@F
	multi_fixed_2_vs_1 TRAINER_GRUNT_SEAFLOOR_CAVERN_4, SeafloorCavern_Room4_Text_Grunt4Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end

MH_AquaGrunt2::@M
	multi_fixed_2_vs_1 TRAINER_GRUNT_SEAFLOOR_CAVERN_2, SeafloorCavern_Room1_Text_Grunt2Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt3::@M
	multi_fixed_2_vs_1 TRAINER_GRUNT_SEAFLOOR_CAVERN_1, SeafloorCavern_Room1_Text_Grunt1Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt4::@F
	multi_fixed_2_vs_1 TRAINER_GRUNT_25, AquaHideout_B1F_Text_Grunt7Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt5::@M
	multi_fixed_2_vs_1 TRAINER_GRUNT_SEAFLOOR_CAVERN_3, SeafloorCavern_Room4_Text_Grunt3Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt6::@m
	multi_fixed_2_vs_1 TRAINER_GRUNT_AQUA_HIDEOUT_3, AquaHideout_B1F_Text_Grunt3Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt7::@F
	multi_fixed_2_vs_1 TRAINER_GRUNT_21, AquaHideout_B1F_Text_Grunt5Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt8::@m
	multi_fixed_2_vs_1 TRAINER_GRUNT_4, AquaHideout_B2F_Text_Grunt4Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt9::@m
	multi_fixed_2_vs_1 TRAINER_GRUNT_26, AquaHideout_B2F_Text_Grunt8Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end
	
MH_AquaGrunt10::@F
	multi_fixed_2_vs_1 TRAINER_GRUNT_22, AquaHideout_B2F_Text_Grunt6Defeat, TRAINER_REL_COURTNEY_1, TRAINER_BACK_PIC_COURTNEY
	release
	end









